version: 2
updates:
  - package-ecosystem: npm
    directory: /breeze.web
    schedule:
      interval: weekly
    groups:
      npm-minor-and-patch:
        update-types:
          - minor
          - patch
  - package-ecosystem: gomod
    directory: /breeze.api
    schedule:
      interval: weekly
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
