// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: assets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
  user_id,
  name,
  asset_type,
  current_value
)
VALUES ($1, $2, $3, $4)
RETURNING
  id,
  user_id,
  name,
  asset_type,
  current_value,
  last_value_updated_at,
  created_at,
  updated_at,
  deleted_at
`

type CreateAssetParams struct {
	UserID       uuid.UUID       `json:"user_id"`
	Name         string          `json:"name"`
	AssetType    AssetType       `json:"asset_type"`
	CurrentValue decimal.Decimal `json:"current_value"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.UserID,
		arg.Name,
		arg.AssetType,
		arg.CurrentValue,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AssetType,
		&i.CurrentValue,
		&i.LastValueUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT
  id,
  user_id,
  name,
  asset_type,
  current_value,
  last_value_updated_at,
  created_at,
  updated_at,
  deleted_at
FROM assets
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetAssetByID(ctx context.Context, id uuid.UUID) (Asset, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AssetType,
		&i.CurrentValue,
		&i.LastValueUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAssetsByUserID = `-- name: ListAssetsByUserID :many
SELECT
  id,
  user_id,
  name,
  asset_type,
  current_value,
  last_value_updated_at,
  created_at,
  updated_at,
  deleted_at
FROM assets
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListAssetsByUserID(ctx context.Context, userID uuid.UUID) ([]Asset, error) {
	rows, err := q.db.Query(ctx, listAssetsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Asset
	for rows.Next() {
		var i Asset
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AssetType,
			&i.CurrentValue,
			&i.LastValueUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAsset = `-- name: SoftDeleteAsset :execrows
UPDATE assets
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAsset(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAsset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets
SET
  name = $2,
  asset_type = $3,
  current_value = $4,
  last_value_updated_at = CASE
    WHEN current_value IS DISTINCT FROM $4 THEN now()
    ELSE last_value_updated_at
  END,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  user_id,
  name,
  asset_type,
  current_value,
  last_value_updated_at,
  created_at,
  updated_at,
  deleted_at
`

type UpdateAssetParams struct {
	ID           uuid.UUID       `json:"id"`
	Name         string          `json:"name"`
	AssetType    AssetType       `json:"asset_type"`
	CurrentValue decimal.Decimal `json:"current_value"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.ID,
		arg.Name,
		arg.AssetType,
		arg.CurrentValue,
	)
	var i Asset
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AssetType,
		&i.CurrentValue,
		&i.LastValueUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
