// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: assets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const createAsset = `-- name: CreateAsset :one
INSERT INTO assets (
  user_id,
  name,
  asset_type,
  current_value,
  owner,
  contribution_mode,
  contribution_value,
  employer_match_rate,
  employer_match_max_percent_of_salary,
  annual_rate,
  return_profile
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
RETURNING
  id,
  user_id,
  name,
  asset_type,
  current_value,
  owner,
  contribution_mode,
  contribution_value,
  employer_match_rate,
  employer_match_max_percent_of_salary,
  annual_rate,
  return_profile,
  last_value_updated_at,
  created_at,
  updated_at,
  deleted_at
`

type CreateAssetParams struct {
	UserID                          uuid.UUID       `json:"user_id"`
	Name                            string          `json:"name"`
	AssetType                       AssetType       `json:"asset_type"`
	CurrentValue                    decimal.Decimal `json:"current_value"`
	Owner                           string          `json:"owner"`
	ContributionMode                string          `json:"contribution_mode"`
	ContributionValue               decimal.Decimal `json:"contribution_value"`
	EmployerMatchRate               decimal.Decimal `json:"employer_match_rate"`
	EmployerMatchMaxPercentOfSalary decimal.Decimal `json:"employer_match_max_percent_of_salary"`
	AnnualRate                      decimal.Decimal `json:"annual_rate"`
	ReturnProfile                   *string         `json:"return_profile"`
}

type CreateAssetRow struct {
	ID                              uuid.UUID          `json:"id"`
	UserID                          uuid.UUID          `json:"user_id"`
	Name                            string             `json:"name"`
	AssetType                       AssetType          `json:"asset_type"`
	CurrentValue                    decimal.Decimal    `json:"current_value"`
	Owner                           string             `json:"owner"`
	ContributionMode                string             `json:"contribution_mode"`
	ContributionValue               decimal.Decimal    `json:"contribution_value"`
	EmployerMatchRate               decimal.Decimal    `json:"employer_match_rate"`
	EmployerMatchMaxPercentOfSalary decimal.Decimal    `json:"employer_match_max_percent_of_salary"`
	AnnualRate                      decimal.Decimal    `json:"annual_rate"`
	ReturnProfile                   *string            `json:"return_profile"`
	LastValueUpdatedAt              pgtype.Timestamptz `json:"last_value_updated_at"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateAsset(ctx context.Context, arg CreateAssetParams) (CreateAssetRow, error) {
	row := q.db.QueryRow(ctx, createAsset,
		arg.UserID,
		arg.Name,
		arg.AssetType,
		arg.CurrentValue,
		arg.Owner,
		arg.ContributionMode,
		arg.ContributionValue,
		arg.EmployerMatchRate,
		arg.EmployerMatchMaxPercentOfSalary,
		arg.AnnualRate,
		arg.ReturnProfile,
	)
	var i CreateAssetRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AssetType,
		&i.CurrentValue,
		&i.Owner,
		&i.ContributionMode,
		&i.ContributionValue,
		&i.EmployerMatchRate,
		&i.EmployerMatchMaxPercentOfSalary,
		&i.AnnualRate,
		&i.ReturnProfile,
		&i.LastValueUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getAssetByID = `-- name: GetAssetByID :one
SELECT
  id,
  user_id,
  name,
  asset_type,
  current_value,
  owner,
  contribution_mode,
  contribution_value,
  employer_match_rate,
  employer_match_max_percent_of_salary,
  annual_rate,
  return_profile,
  last_value_updated_at,
  created_at,
  updated_at,
  deleted_at
FROM assets
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

type GetAssetByIDRow struct {
	ID                              uuid.UUID          `json:"id"`
	UserID                          uuid.UUID          `json:"user_id"`
	Name                            string             `json:"name"`
	AssetType                       AssetType          `json:"asset_type"`
	CurrentValue                    decimal.Decimal    `json:"current_value"`
	Owner                           string             `json:"owner"`
	ContributionMode                string             `json:"contribution_mode"`
	ContributionValue               decimal.Decimal    `json:"contribution_value"`
	EmployerMatchRate               decimal.Decimal    `json:"employer_match_rate"`
	EmployerMatchMaxPercentOfSalary decimal.Decimal    `json:"employer_match_max_percent_of_salary"`
	AnnualRate                      decimal.Decimal    `json:"annual_rate"`
	ReturnProfile                   *string            `json:"return_profile"`
	LastValueUpdatedAt              pgtype.Timestamptz `json:"last_value_updated_at"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetAssetByID(ctx context.Context, id uuid.UUID) (GetAssetByIDRow, error) {
	row := q.db.QueryRow(ctx, getAssetByID, id)
	var i GetAssetByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AssetType,
		&i.CurrentValue,
		&i.Owner,
		&i.ContributionMode,
		&i.ContributionValue,
		&i.EmployerMatchRate,
		&i.EmployerMatchMaxPercentOfSalary,
		&i.AnnualRate,
		&i.ReturnProfile,
		&i.LastValueUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listAssetsByUserID = `-- name: ListAssetsByUserID :many
SELECT
  id,
  user_id,
  name,
  asset_type,
  current_value,
  owner,
  contribution_mode,
  contribution_value,
  employer_match_rate,
  employer_match_max_percent_of_salary,
  annual_rate,
  return_profile,
  last_value_updated_at,
  created_at,
  updated_at,
  deleted_at
FROM assets
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

type ListAssetsByUserIDRow struct {
	ID                              uuid.UUID          `json:"id"`
	UserID                          uuid.UUID          `json:"user_id"`
	Name                            string             `json:"name"`
	AssetType                       AssetType          `json:"asset_type"`
	CurrentValue                    decimal.Decimal    `json:"current_value"`
	Owner                           string             `json:"owner"`
	ContributionMode                string             `json:"contribution_mode"`
	ContributionValue               decimal.Decimal    `json:"contribution_value"`
	EmployerMatchRate               decimal.Decimal    `json:"employer_match_rate"`
	EmployerMatchMaxPercentOfSalary decimal.Decimal    `json:"employer_match_max_percent_of_salary"`
	AnnualRate                      decimal.Decimal    `json:"annual_rate"`
	ReturnProfile                   *string            `json:"return_profile"`
	LastValueUpdatedAt              pgtype.Timestamptz `json:"last_value_updated_at"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListAssetsByUserID(ctx context.Context, userID uuid.UUID) ([]ListAssetsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listAssetsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListAssetsByUserIDRow
	for rows.Next() {
		var i ListAssetsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AssetType,
			&i.CurrentValue,
			&i.Owner,
			&i.ContributionMode,
			&i.ContributionValue,
			&i.EmployerMatchRate,
			&i.EmployerMatchMaxPercentOfSalary,
			&i.AnnualRate,
			&i.ReturnProfile,
			&i.LastValueUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteAsset = `-- name: SoftDeleteAsset :execrows
UPDATE assets
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteAsset(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteAsset, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateAsset = `-- name: UpdateAsset :one
UPDATE assets
SET
  name = $2,
  asset_type = $3,
  current_value = $4,
  owner = $5,
  contribution_mode = $6,
  contribution_value = $7,
  employer_match_rate = $8,
  employer_match_max_percent_of_salary = $9,
  annual_rate = $10,
  return_profile = $11,
  last_value_updated_at = CASE
    WHEN current_value IS DISTINCT FROM $4 THEN now()
    ELSE last_value_updated_at
  END,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  user_id,
  name,
  asset_type,
  current_value,
  owner,
  contribution_mode,
  contribution_value,
  employer_match_rate,
  employer_match_max_percent_of_salary,
  annual_rate,
  return_profile,
  last_value_updated_at,
  created_at,
  updated_at,
  deleted_at
`

type UpdateAssetParams struct {
	ID                              uuid.UUID       `json:"id"`
	Name                            string          `json:"name"`
	AssetType                       AssetType       `json:"asset_type"`
	CurrentValue                    decimal.Decimal `json:"current_value"`
	Owner                           string          `json:"owner"`
	ContributionMode                string          `json:"contribution_mode"`
	ContributionValue               decimal.Decimal `json:"contribution_value"`
	EmployerMatchRate               decimal.Decimal `json:"employer_match_rate"`
	EmployerMatchMaxPercentOfSalary decimal.Decimal `json:"employer_match_max_percent_of_salary"`
	AnnualRate                      decimal.Decimal `json:"annual_rate"`
	ReturnProfile                   *string         `json:"return_profile"`
}

type UpdateAssetRow struct {
	ID                              uuid.UUID          `json:"id"`
	UserID                          uuid.UUID          `json:"user_id"`
	Name                            string             `json:"name"`
	AssetType                       AssetType          `json:"asset_type"`
	CurrentValue                    decimal.Decimal    `json:"current_value"`
	Owner                           string             `json:"owner"`
	ContributionMode                string             `json:"contribution_mode"`
	ContributionValue               decimal.Decimal    `json:"contribution_value"`
	EmployerMatchRate               decimal.Decimal    `json:"employer_match_rate"`
	EmployerMatchMaxPercentOfSalary decimal.Decimal    `json:"employer_match_max_percent_of_salary"`
	AnnualRate                      decimal.Decimal    `json:"annual_rate"`
	ReturnProfile                   *string            `json:"return_profile"`
	LastValueUpdatedAt              pgtype.Timestamptz `json:"last_value_updated_at"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateAsset(ctx context.Context, arg UpdateAssetParams) (UpdateAssetRow, error) {
	row := q.db.QueryRow(ctx, updateAsset,
		arg.ID,
		arg.Name,
		arg.AssetType,
		arg.CurrentValue,
		arg.Owner,
		arg.ContributionMode,
		arg.ContributionValue,
		arg.EmployerMatchRate,
		arg.EmployerMatchMaxPercentOfSalary,
		arg.AnnualRate,
		arg.ReturnProfile,
	)
	var i UpdateAssetRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AssetType,
		&i.CurrentValue,
		&i.Owner,
		&i.ContributionMode,
		&i.ContributionValue,
		&i.EmployerMatchRate,
		&i.EmployerMatchMaxPercentOfSalary,
		&i.AnnualRate,
		&i.ReturnProfile,
		&i.LastValueUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
