// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: budgets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const createBudget = `-- name: CreateBudget :one
INSERT INTO budgets (
  user_id,
  date,
  monthly_income,
  monthly_expenses
) VALUES ($1, $2, $3, $4)
RETURNING
  id,
  user_id,
  date,
  monthly_income,
  monthly_expenses,
  created_at,
  updated_at,
  deleted_at
`

type CreateBudgetParams struct {
	UserID          uuid.UUID       `json:"user_id"`
	Date            pgtype.Date     `json:"date"`
	MonthlyIncome   decimal.Decimal `json:"monthly_income"`
	MonthlyExpenses decimal.Decimal `json:"monthly_expenses"`
}

func (q *Queries) CreateBudget(ctx context.Context, arg CreateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, createBudget,
		arg.UserID,
		arg.Date,
		arg.MonthlyIncome,
		arg.MonthlyExpenses,
	)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.MonthlyIncome,
		&i.MonthlyExpenses,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBudgetByDate = `-- name: GetBudgetByDate :one
SELECT
  id,
  user_id,
  date,
  monthly_income,
  monthly_expenses,
  created_at,
  updated_at,
  deleted_at
FROM budgets
WHERE user_id = $1
  AND date = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetBudgetByDateParams struct {
	UserID uuid.UUID   `json:"user_id"`
	Date   pgtype.Date `json:"date"`
}

func (q *Queries) GetBudgetByDate(ctx context.Context, arg GetBudgetByDateParams) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByDate, arg.UserID, arg.Date)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.MonthlyIncome,
		&i.MonthlyExpenses,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getBudgetByID = `-- name: GetBudgetByID :one
SELECT
  id,
  user_id,
  date,
  monthly_income,
  monthly_expenses,
  created_at,
  updated_at,
  deleted_at
FROM budgets
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetBudgetByID(ctx context.Context, id uuid.UUID) (Budget, error) {
	row := q.db.QueryRow(ctx, getBudgetByID, id)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.MonthlyIncome,
		&i.MonthlyExpenses,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listBudgetsByUserID = `-- name: ListBudgetsByUserID :many
SELECT
  id,
  user_id,
  date,
  monthly_income,
  monthly_expenses,
  created_at,
  updated_at,
  deleted_at
FROM budgets
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY date DESC
`

func (q *Queries) ListBudgetsByUserID(ctx context.Context, userID uuid.UUID) ([]Budget, error) {
	rows, err := q.db.Query(ctx, listBudgetsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Budget
	for rows.Next() {
		var i Budget
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Date,
			&i.MonthlyIncome,
			&i.MonthlyExpenses,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteBudget = `-- name: SoftDeleteBudget :execrows
UPDATE budgets
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteBudget(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteBudget, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateBudget = `-- name: UpdateBudget :one
UPDATE budgets
SET
  monthly_income = $2,
  monthly_expenses = $3,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  user_id,
  date,
  monthly_income,
  monthly_expenses,
  created_at,
  updated_at,
  deleted_at
`

type UpdateBudgetParams struct {
	ID              uuid.UUID       `json:"id"`
	MonthlyIncome   decimal.Decimal `json:"monthly_income"`
	MonthlyExpenses decimal.Decimal `json:"monthly_expenses"`
}

func (q *Queries) UpdateBudget(ctx context.Context, arg UpdateBudgetParams) (Budget, error) {
	row := q.db.QueryRow(ctx, updateBudget, arg.ID, arg.MonthlyIncome, arg.MonthlyExpenses)
	var i Budget
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Date,
		&i.MonthlyIncome,
		&i.MonthlyExpenses,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
