// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: contribution_limits.sql

package sqlc

import (
	"context"
)

const getContributionLimitByAccountTypeAndTaxYear = `-- name: GetContributionLimitByAccountTypeAndTaxYear :one
SELECT id, account_type, tax_year, annual_limit, catch_up_age, catch_up_amount, created_at, updated_at, deleted_at, family_annual_limit, super_catch_up_amount FROM contribution_limits
WHERE account_type = $1
  AND tax_year = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetContributionLimitByAccountTypeAndTaxYearParams struct {
	AccountType RetirementAccountType `json:"account_type"`
	TaxYear     int32                 `json:"tax_year"`
}

func (q *Queries) GetContributionLimitByAccountTypeAndTaxYear(ctx context.Context, arg GetContributionLimitByAccountTypeAndTaxYearParams) (ContributionLimit, error) {
	row := q.db.QueryRow(ctx, getContributionLimitByAccountTypeAndTaxYear, arg.AccountType, arg.TaxYear)
	var i ContributionLimit
	err := row.Scan(
		&i.ID,
		&i.AccountType,
		&i.TaxYear,
		&i.AnnualLimit,
		&i.CatchUpAge,
		&i.CatchUpAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.FamilyAnnualLimit,
		&i.SuperCatchUpAmount,
	)
	return i, err
}

const listContributionLimitsByTaxYear = `-- name: ListContributionLimitsByTaxYear :many
SELECT id, account_type, tax_year, annual_limit, catch_up_age, catch_up_amount, created_at, updated_at, deleted_at, family_annual_limit, super_catch_up_amount FROM contribution_limits
WHERE tax_year = $1
  AND deleted_at IS NULL
ORDER BY account_type
`

func (q *Queries) ListContributionLimitsByTaxYear(ctx context.Context, taxYear int32) ([]ContributionLimit, error) {
	rows, err := q.db.Query(ctx, listContributionLimitsByTaxYear, taxYear)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ContributionLimit
	for rows.Next() {
		var i ContributionLimit
		if err := rows.Scan(
			&i.ID,
			&i.AccountType,
			&i.TaxYear,
			&i.AnnualLimit,
			&i.CatchUpAge,
			&i.CatchUpAmount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.FamilyAnnualLimit,
			&i.SuperCatchUpAmount,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
