// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expenses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const createExpense = `-- name: CreateExpense :one
INSERT INTO expenses (
  user_id,
  budget_id,
  amount,
  date,
  description,
  recurring_source_id
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING
  id,
  user_id,
  budget_id,
  amount,
  date,
  description,
  recurring_source_id,
  created_at,
  updated_at,
  deleted_at
`

type CreateExpenseParams struct {
	UserID            uuid.UUID       `json:"user_id"`
	BudgetID          uuid.UUID       `json:"budget_id"`
	Amount            decimal.Decimal `json:"amount"`
	Date              pgtype.Date     `json:"date"`
	Description       string          `json:"description"`
	RecurringSourceID pgtype.UUID     `json:"recurring_source_id"`
}

func (q *Queries) CreateExpense(ctx context.Context, arg CreateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, createExpense,
		arg.UserID,
		arg.BudgetID,
		arg.Amount,
		arg.Date,
		arg.Description,
		arg.RecurringSourceID,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetID,
		&i.Amount,
		&i.Date,
		&i.Description,
		&i.RecurringSourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createExpenseSplit = `-- name: CreateExpenseSplit :one
INSERT INTO expense_splits (
  expense_id,
  category_id,
  amount,
  description
) VALUES ($1, $2, $3, $4)
RETURNING
  id,
  expense_id,
  category_id,
  amount,
  description,
  created_at,
  updated_at,
  deleted_at
`

type CreateExpenseSplitParams struct {
	ExpenseID   uuid.UUID       `json:"expense_id"`
	CategoryID  uuid.UUID       `json:"category_id"`
	Amount      decimal.Decimal `json:"amount"`
	Description *string         `json:"description"`
}

func (q *Queries) CreateExpenseSplit(ctx context.Context, arg CreateExpenseSplitParams) (ExpenseSplit, error) {
	row := q.db.QueryRow(ctx, createExpenseSplit,
		arg.ExpenseID,
		arg.CategoryID,
		arg.Amount,
		arg.Description,
	)
	var i ExpenseSplit
	err := row.Scan(
		&i.ID,
		&i.ExpenseID,
		&i.CategoryID,
		&i.Amount,
		&i.Description,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExpenseByID = `-- name: GetExpenseByID :one
SELECT
  id,
  user_id,
  budget_id,
  amount,
  date,
  description,
  recurring_source_id,
  created_at,
  updated_at,
  deleted_at
FROM expenses
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetExpenseByID(ctx context.Context, id uuid.UUID) (Expense, error) {
	row := q.db.QueryRow(ctx, getExpenseByID, id)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetID,
		&i.Amount,
		&i.Date,
		&i.Description,
		&i.RecurringSourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listExpenseSplitsByExpenseIDs = `-- name: ListExpenseSplitsByExpenseIDs :many
SELECT
  id,
  expense_id,
  category_id,
  amount,
  description,
  created_at,
  updated_at,
  deleted_at
FROM expense_splits
WHERE expense_id = ANY($1::uuid[])
  AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListExpenseSplitsByExpenseIDs(ctx context.Context, dollar_1 []uuid.UUID) ([]ExpenseSplit, error) {
	rows, err := q.db.Query(ctx, listExpenseSplitsByExpenseIDs, dollar_1)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseSplit
	for rows.Next() {
		var i ExpenseSplit
		if err := rows.Scan(
			&i.ID,
			&i.ExpenseID,
			&i.CategoryID,
			&i.Amount,
			&i.Description,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listExpensesByBudgetID = `-- name: ListExpensesByBudgetID :many
SELECT
  id,
  user_id,
  budget_id,
  amount,
  date,
  description,
  recurring_source_id,
  created_at,
  updated_at,
  deleted_at
FROM expenses
WHERE budget_id = $1
  AND deleted_at IS NULL
ORDER BY date DESC, created_at DESC
`

func (q *Queries) ListExpensesByBudgetID(ctx context.Context, budgetID uuid.UUID) ([]Expense, error) {
	rows, err := q.db.Query(ctx, listExpensesByBudgetID, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Expense
	for rows.Next() {
		var i Expense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BudgetID,
			&i.Amount,
			&i.Date,
			&i.Description,
			&i.RecurringSourceID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExpense = `-- name: SoftDeleteExpense :execrows
UPDATE expenses
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteExpense(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteExpense, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteExpenseSplitsByExpenseID = `-- name: SoftDeleteExpenseSplitsByExpenseID :execrows
UPDATE expense_splits
SET deleted_at = now(),
    updated_at = now()
WHERE expense_id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteExpenseSplitsByExpenseID(ctx context.Context, expenseID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteExpenseSplitsByExpenseID, expenseID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateExpense = `-- name: UpdateExpense :one
UPDATE expenses
SET
  amount = $2,
  date = $3,
  description = $4,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  user_id,
  budget_id,
  amount,
  date,
  description,
  recurring_source_id,
  created_at,
  updated_at,
  deleted_at
`

type UpdateExpenseParams struct {
	ID          uuid.UUID       `json:"id"`
	Amount      decimal.Decimal `json:"amount"`
	Date        pgtype.Date     `json:"date"`
	Description string          `json:"description"`
}

func (q *Queries) UpdateExpense(ctx context.Context, arg UpdateExpenseParams) (Expense, error) {
	row := q.db.QueryRow(ctx, updateExpense,
		arg.ID,
		arg.Amount,
		arg.Date,
		arg.Description,
	)
	var i Expense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetID,
		&i.Amount,
		&i.Date,
		&i.Description,
		&i.RecurringSourceID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
