// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: expense_categories.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
)

const createExpenseCategory = `-- name: CreateExpenseCategory :one
INSERT INTO expense_categories (
  user_id,
  budget_id,
  name,
  allocation,
  current_spend
) VALUES ($1, $2, $3, $4, $5)
RETURNING
  id,
  user_id,
  budget_id,
  name,
  allocation,
  current_spend,
  created_at,
  updated_at,
  deleted_at
`

type CreateExpenseCategoryParams struct {
	UserID       uuid.UUID       `json:"user_id"`
	BudgetID     uuid.UUID       `json:"budget_id"`
	Name         string          `json:"name"`
	Allocation   decimal.Decimal `json:"allocation"`
	CurrentSpend decimal.Decimal `json:"current_spend"`
}

func (q *Queries) CreateExpenseCategory(ctx context.Context, arg CreateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, createExpenseCategory,
		arg.UserID,
		arg.BudgetID,
		arg.Name,
		arg.Allocation,
		arg.CurrentSpend,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetID,
		&i.Name,
		&i.Allocation,
		&i.CurrentSpend,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getExpenseCategoryByID = `-- name: GetExpenseCategoryByID :one
SELECT
  id,
  user_id,
  budget_id,
  name,
  allocation,
  current_spend,
  created_at,
  updated_at,
  deleted_at
FROM expense_categories
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetExpenseCategoryByID(ctx context.Context, id uuid.UUID) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, getExpenseCategoryByID, id)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetID,
		&i.Name,
		&i.Allocation,
		&i.CurrentSpend,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listExpenseCategoriesByBudgetID = `-- name: ListExpenseCategoriesByBudgetID :many
SELECT
  id,
  user_id,
  budget_id,
  name,
  allocation,
  current_spend,
  created_at,
  updated_at,
  deleted_at
FROM expense_categories
WHERE budget_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListExpenseCategoriesByBudgetID(ctx context.Context, budgetID uuid.UUID) ([]ExpenseCategory, error) {
	rows, err := q.db.Query(ctx, listExpenseCategoriesByBudgetID, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ExpenseCategory
	for rows.Next() {
		var i ExpenseCategory
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BudgetID,
			&i.Name,
			&i.Allocation,
			&i.CurrentSpend,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteExpenseCategory = `-- name: SoftDeleteExpenseCategory :execrows
UPDATE expense_categories
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteExpenseCategory(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteExpenseCategory, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateExpenseCategory = `-- name: UpdateExpenseCategory :one
UPDATE expense_categories
SET
  name = $2,
  allocation = $3,
  current_spend = $4,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  user_id,
  budget_id,
  name,
  allocation,
  current_spend,
  created_at,
  updated_at,
  deleted_at
`

type UpdateExpenseCategoryParams struct {
	ID           uuid.UUID       `json:"id"`
	Name         string          `json:"name"`
	Allocation   decimal.Decimal `json:"allocation"`
	CurrentSpend decimal.Decimal `json:"current_spend"`
}

func (q *Queries) UpdateExpenseCategory(ctx context.Context, arg UpdateExpenseCategoryParams) (ExpenseCategory, error) {
	row := q.db.QueryRow(ctx, updateExpenseCategory,
		arg.ID,
		arg.Name,
		arg.Allocation,
		arg.CurrentSpend,
	)
	var i ExpenseCategory
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetID,
		&i.Name,
		&i.Allocation,
		&i.CurrentSpend,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
