// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createFinancialOrderSteps = `-- name: CreateFinancialOrderSteps :many
INSERT INTO goals (
  user_id,
  description,
  is_completed,
  category,
  priority,
  notes,
  is_financial_order_step,
  financial_order_step
) VALUES
  ($1, 'Build emergency fund (3-6 months expenses)', false, 'emergency-fund', 100, 'Save 3-6 months of essential expenses in a high-yield savings account', true, 1),
  ($1, 'Get employer 401k match', false, 'retirement', 99, 'Contribute enough to get full employer match', true, 2),
  ($1, 'Pay off high-interest debt', false, 'debt-payoff', 98, 'Pay off credit cards and loans with interest rates above 7%', true, 3),
  ($1, 'Max out HSA', false, 'retirement', 97, 'Max out Health Savings Account if eligible', true, 4),
  ($1, 'Max out Roth IRA', false, 'retirement', 96, 'Contribute maximum to Roth IRA ($7,000/year in 2024)', true, 5),
  ($1, 'Pay off medium-interest debt', false, 'debt-payoff', 95, 'Pay off student loans and car loans (5-7% interest)', true, 6),
  ($1, 'Max out 401k', false, 'retirement', 94, 'Max out 401k contributions ($23,000/year in 2024)', true, 7),
  ($1, 'Mega backdoor Roth', false, 'retirement', 93, 'If available through employer plan', true, 8),
  ($1, 'Invest in taxable brokerage', false, 'investment', 92, 'Invest in taxable accounts after tax-advantaged accounts are maxed', true, 9),
  ($1, 'Other financial goals', false, 'other', 91, 'Real estate, business, or other goals', true, 10)
RETURNING
  id,
  user_id,
  description,
  is_completed,
  target_amount,
  target_date,
  category,
  custom_category,
  priority,
  notes,
  connected_account_ids,
  is_financial_order_step,
  financial_order_step,
  created_at,
  updated_at,
  deleted_at
`

type CreateFinancialOrderStepsRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	Description          string             `json:"description"`
	IsCompleted          bool               `json:"is_completed"`
	TargetAmount         pgtype.Numeric     `json:"target_amount"`
	TargetDate           pgtype.Date        `json:"target_date"`
	Category             *string            `json:"category"`
	CustomCategory       *string            `json:"custom_category"`
	Priority             int32              `json:"priority"`
	Notes                *string            `json:"notes"`
	ConnectedAccountIds  []uuid.UUID        `json:"connected_account_ids"`
	IsFinancialOrderStep bool               `json:"is_financial_order_step"`
	FinancialOrderStep   *int32             `json:"financial_order_step"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateFinancialOrderSteps(ctx context.Context, userID uuid.UUID) ([]CreateFinancialOrderStepsRow, error) {
	rows, err := q.db.Query(ctx, createFinancialOrderSteps, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []CreateFinancialOrderStepsRow
	for rows.Next() {
		var i CreateFinancialOrderStepsRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.IsCompleted,
			&i.TargetAmount,
			&i.TargetDate,
			&i.Category,
			&i.CustomCategory,
			&i.Priority,
			&i.Notes,
			&i.ConnectedAccountIds,
			&i.IsFinancialOrderStep,
			&i.FinancialOrderStep,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (
  user_id,
  description,
  is_completed,
  target_amount,
  target_date,
  category,
  custom_category,
  priority,
  notes,
  connected_account_ids,
  is_financial_order_step,
  financial_order_step
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING
  id,
  user_id,
  description,
  is_completed,
  target_amount,
  target_date,
  category,
  custom_category,
  priority,
  notes,
  connected_account_ids,
  is_financial_order_step,
  financial_order_step,
  created_at,
  updated_at,
  deleted_at
`

type CreateGoalParams struct {
	UserID               uuid.UUID      `json:"user_id"`
	Description          string         `json:"description"`
	IsCompleted          bool           `json:"is_completed"`
	TargetAmount         pgtype.Numeric `json:"target_amount"`
	TargetDate           pgtype.Date    `json:"target_date"`
	Category             *string        `json:"category"`
	CustomCategory       *string        `json:"custom_category"`
	Priority             int32          `json:"priority"`
	Notes                *string        `json:"notes"`
	ConnectedAccountIds  []uuid.UUID    `json:"connected_account_ids"`
	IsFinancialOrderStep bool           `json:"is_financial_order_step"`
	FinancialOrderStep   *int32         `json:"financial_order_step"`
}

type CreateGoalRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	Description          string             `json:"description"`
	IsCompleted          bool               `json:"is_completed"`
	TargetAmount         pgtype.Numeric     `json:"target_amount"`
	TargetDate           pgtype.Date        `json:"target_date"`
	Category             *string            `json:"category"`
	CustomCategory       *string            `json:"custom_category"`
	Priority             int32              `json:"priority"`
	Notes                *string            `json:"notes"`
	ConnectedAccountIds  []uuid.UUID        `json:"connected_account_ids"`
	IsFinancialOrderStep bool               `json:"is_financial_order_step"`
	FinancialOrderStep   *int32             `json:"financial_order_step"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (CreateGoalRow, error) {
	row := q.db.QueryRow(ctx, createGoal,
		arg.UserID,
		arg.Description,
		arg.IsCompleted,
		arg.TargetAmount,
		arg.TargetDate,
		arg.Category,
		arg.CustomCategory,
		arg.Priority,
		arg.Notes,
		arg.ConnectedAccountIds,
		arg.IsFinancialOrderStep,
		arg.FinancialOrderStep,
	)
	var i CreateGoalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.IsCompleted,
		&i.TargetAmount,
		&i.TargetDate,
		&i.Category,
		&i.CustomCategory,
		&i.Priority,
		&i.Notes,
		&i.ConnectedAccountIds,
		&i.IsFinancialOrderStep,
		&i.FinancialOrderStep,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGoalByID = `-- name: GetGoalByID :one
SELECT
  id,
  user_id,
  description,
  is_completed,
  target_amount,
  target_date,
  category,
  custom_category,
  priority,
  notes,
  connected_account_ids,
  is_financial_order_step,
  financial_order_step,
  created_at,
  updated_at,
  deleted_at
FROM goals
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

type GetGoalByIDRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	Description          string             `json:"description"`
	IsCompleted          bool               `json:"is_completed"`
	TargetAmount         pgtype.Numeric     `json:"target_amount"`
	TargetDate           pgtype.Date        `json:"target_date"`
	Category             *string            `json:"category"`
	CustomCategory       *string            `json:"custom_category"`
	Priority             int32              `json:"priority"`
	Notes                *string            `json:"notes"`
	ConnectedAccountIds  []uuid.UUID        `json:"connected_account_ids"`
	IsFinancialOrderStep bool               `json:"is_financial_order_step"`
	FinancialOrderStep   *int32             `json:"financial_order_step"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) GetGoalByID(ctx context.Context, id uuid.UUID) (GetGoalByIDRow, error) {
	row := q.db.QueryRow(ctx, getGoalByID, id)
	var i GetGoalByIDRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.IsCompleted,
		&i.TargetAmount,
		&i.TargetDate,
		&i.Category,
		&i.CustomCategory,
		&i.Priority,
		&i.Notes,
		&i.ConnectedAccountIds,
		&i.IsFinancialOrderStep,
		&i.FinancialOrderStep,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listFinancialOrderStepsByUserID = `-- name: ListFinancialOrderStepsByUserID :many
SELECT
  id,
  user_id,
  description,
  is_completed,
  target_amount,
  target_date,
  category,
  custom_category,
  priority,
  notes,
  connected_account_ids,
  is_financial_order_step,
  financial_order_step,
  created_at,
  updated_at,
  deleted_at
FROM goals
WHERE user_id = $1
  AND is_financial_order_step = true
  AND deleted_at IS NULL
ORDER BY financial_order_step ASC
`

type ListFinancialOrderStepsByUserIDRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	Description          string             `json:"description"`
	IsCompleted          bool               `json:"is_completed"`
	TargetAmount         pgtype.Numeric     `json:"target_amount"`
	TargetDate           pgtype.Date        `json:"target_date"`
	Category             *string            `json:"category"`
	CustomCategory       *string            `json:"custom_category"`
	Priority             int32              `json:"priority"`
	Notes                *string            `json:"notes"`
	ConnectedAccountIds  []uuid.UUID        `json:"connected_account_ids"`
	IsFinancialOrderStep bool               `json:"is_financial_order_step"`
	FinancialOrderStep   *int32             `json:"financial_order_step"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListFinancialOrderStepsByUserID(ctx context.Context, userID uuid.UUID) ([]ListFinancialOrderStepsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listFinancialOrderStepsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListFinancialOrderStepsByUserIDRow
	for rows.Next() {
		var i ListFinancialOrderStepsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.IsCompleted,
			&i.TargetAmount,
			&i.TargetDate,
			&i.Category,
			&i.CustomCategory,
			&i.Priority,
			&i.Notes,
			&i.ConnectedAccountIds,
			&i.IsFinancialOrderStep,
			&i.FinancialOrderStep,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listGoalsByUserID = `-- name: ListGoalsByUserID :many
SELECT
  id,
  user_id,
  description,
  is_completed,
  target_amount,
  target_date,
  category,
  custom_category,
  priority,
  notes,
  connected_account_ids,
  is_financial_order_step,
  financial_order_step,
  created_at,
  updated_at,
  deleted_at
FROM goals
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY
  is_financial_order_step DESC,
  financial_order_step ASC NULLS LAST,
  is_completed ASC,
  priority DESC,
  created_at DESC
`

type ListGoalsByUserIDRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	Description          string             `json:"description"`
	IsCompleted          bool               `json:"is_completed"`
	TargetAmount         pgtype.Numeric     `json:"target_amount"`
	TargetDate           pgtype.Date        `json:"target_date"`
	Category             *string            `json:"category"`
	CustomCategory       *string            `json:"custom_category"`
	Priority             int32              `json:"priority"`
	Notes                *string            `json:"notes"`
	ConnectedAccountIds  []uuid.UUID        `json:"connected_account_ids"`
	IsFinancialOrderStep bool               `json:"is_financial_order_step"`
	FinancialOrderStep   *int32             `json:"financial_order_step"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) ListGoalsByUserID(ctx context.Context, userID uuid.UUID) ([]ListGoalsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listGoalsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListGoalsByUserIDRow
	for rows.Next() {
		var i ListGoalsByUserIDRow
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.IsCompleted,
			&i.TargetAmount,
			&i.TargetDate,
			&i.Category,
			&i.CustomCategory,
			&i.Priority,
			&i.Notes,
			&i.ConnectedAccountIds,
			&i.IsFinancialOrderStep,
			&i.FinancialOrderStep,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGoal = `-- name: SoftDeleteGoal :execrows
UPDATE goals
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteGoal(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteGoal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET
  description = $2,
  is_completed = $3,
  target_amount = $4,
  target_date = $5,
  category = $6,
  custom_category = $7,
  priority = $8,
  notes = $9,
  connected_account_ids = $10,
  is_financial_order_step = $11,
  financial_order_step = $12,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  user_id,
  description,
  is_completed,
  target_amount,
  target_date,
  category,
  custom_category,
  priority,
  notes,
  connected_account_ids,
  is_financial_order_step,
  financial_order_step,
  created_at,
  updated_at,
  deleted_at
`

type UpdateGoalParams struct {
	ID                   uuid.UUID      `json:"id"`
	Description          string         `json:"description"`
	IsCompleted          bool           `json:"is_completed"`
	TargetAmount         pgtype.Numeric `json:"target_amount"`
	TargetDate           pgtype.Date    `json:"target_date"`
	Category             *string        `json:"category"`
	CustomCategory       *string        `json:"custom_category"`
	Priority             int32          `json:"priority"`
	Notes                *string        `json:"notes"`
	ConnectedAccountIds  []uuid.UUID    `json:"connected_account_ids"`
	IsFinancialOrderStep bool           `json:"is_financial_order_step"`
	FinancialOrderStep   *int32         `json:"financial_order_step"`
}

type UpdateGoalRow struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	Description          string             `json:"description"`
	IsCompleted          bool               `json:"is_completed"`
	TargetAmount         pgtype.Numeric     `json:"target_amount"`
	TargetDate           pgtype.Date        `json:"target_date"`
	Category             *string            `json:"category"`
	CustomCategory       *string            `json:"custom_category"`
	Priority             int32              `json:"priority"`
	Notes                *string            `json:"notes"`
	ConnectedAccountIds  []uuid.UUID        `json:"connected_account_ids"`
	IsFinancialOrderStep bool               `json:"is_financial_order_step"`
	FinancialOrderStep   *int32             `json:"financial_order_step"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (UpdateGoalRow, error) {
	row := q.db.QueryRow(ctx, updateGoal,
		arg.ID,
		arg.Description,
		arg.IsCompleted,
		arg.TargetAmount,
		arg.TargetDate,
		arg.Category,
		arg.CustomCategory,
		arg.Priority,
		arg.Notes,
		arg.ConnectedAccountIds,
		arg.IsFinancialOrderStep,
		arg.FinancialOrderStep,
	)
	var i UpdateGoalRow
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.IsCompleted,
		&i.TargetAmount,
		&i.TargetDate,
		&i.Category,
		&i.CustomCategory,
		&i.Priority,
		&i.Notes,
		&i.ConnectedAccountIds,
		&i.IsFinancialOrderStep,
		&i.FinancialOrderStep,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
