// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: goals.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

const createGoal = `-- name: CreateGoal :one
INSERT INTO goals (
  user_id,
  description,
  is_completed
) VALUES ($1, $2, $3)
RETURNING
  id,
  user_id,
  description,
  is_completed,
  created_at,
  updated_at,
  deleted_at
`

type CreateGoalParams struct {
	UserID      uuid.UUID `json:"user_id"`
	Description string    `json:"description"`
	IsCompleted bool      `json:"is_completed"`
}

func (q *Queries) CreateGoal(ctx context.Context, arg CreateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, createGoal, arg.UserID, arg.Description, arg.IsCompleted)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getGoalByID = `-- name: GetGoalByID :one
SELECT
  id,
  user_id,
  description,
  is_completed,
  created_at,
  updated_at,
  deleted_at
FROM goals
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetGoalByID(ctx context.Context, id uuid.UUID) (Goal, error) {
	row := q.db.QueryRow(ctx, getGoalByID, id)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listGoalsByUserID = `-- name: ListGoalsByUserID :many
SELECT
  id,
  user_id,
  description,
  is_completed,
  created_at,
  updated_at,
  deleted_at
FROM goals
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY is_completed ASC, created_at DESC
`

func (q *Queries) ListGoalsByUserID(ctx context.Context, userID uuid.UUID) ([]Goal, error) {
	rows, err := q.db.Query(ctx, listGoalsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Goal
	for rows.Next() {
		var i Goal
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Description,
			&i.IsCompleted,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteGoal = `-- name: SoftDeleteGoal :execrows
UPDATE goals
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteGoal(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteGoal, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateGoal = `-- name: UpdateGoal :one
UPDATE goals
SET
  description = $2,
  is_completed = $3,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  user_id,
  description,
  is_completed,
  created_at,
  updated_at,
  deleted_at
`

type UpdateGoalParams struct {
	ID          uuid.UUID `json:"id"`
	Description string    `json:"description"`
	IsCompleted bool      `json:"is_completed"`
}

func (q *Queries) UpdateGoal(ctx context.Context, arg UpdateGoalParams) (Goal, error) {
	row := q.db.QueryRow(ctx, updateGoal, arg.ID, arg.Description, arg.IsCompleted)
	var i Goal
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Description,
		&i.IsCompleted,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
