// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: income.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const createIncome = `-- name: CreateIncome :one
INSERT INTO income (
  user_id,
  budget_id,
  name,
  amount,
  date,
  source_type,
  source_template_id,
  source_occurrence_date,
  generation_month
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
  id,
  user_id,
  budget_id,
  name,
  amount,
  date,
  source_type,
  source_template_id,
  source_occurrence_date,
  generation_month,
  created_at,
  updated_at,
  deleted_at
`

type CreateIncomeParams struct {
	UserID               uuid.UUID        `json:"user_id"`
	BudgetID             uuid.UUID        `json:"budget_id"`
	Name                 string           `json:"name"`
	Amount               decimal.Decimal  `json:"amount"`
	Date                 pgtype.Date      `json:"date"`
	SourceType           IncomeSourceType `json:"source_type"`
	SourceTemplateID     pgtype.UUID      `json:"source_template_id"`
	SourceOccurrenceDate pgtype.Date      `json:"source_occurrence_date"`
	GenerationMonth      pgtype.Date      `json:"generation_month"`
}

func (q *Queries) CreateIncome(ctx context.Context, arg CreateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, createIncome,
		arg.UserID,
		arg.BudgetID,
		arg.Name,
		arg.Amount,
		arg.Date,
		arg.SourceType,
		arg.SourceTemplateID,
		arg.SourceOccurrenceDate,
		arg.GenerationMonth,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetID,
		&i.Name,
		&i.Amount,
		&i.Date,
		&i.SourceType,
		&i.SourceTemplateID,
		&i.SourceOccurrenceDate,
		&i.GenerationMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createRecurringIncome = `-- name: CreateRecurringIncome :one
INSERT INTO recurring_income (
  user_id,
  name,
  amount,
  recurrence_interval,
  payday_day_of_month,
  start_date,
  end_date
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
  id,
  user_id,
  name,
  amount,
  recurrence_interval,
  payday_day_of_month,
  start_date,
  end_date,
  created_at,
  updated_at,
  deleted_at
`

type CreateRecurringIncomeParams struct {
	UserID             uuid.UUID          `json:"user_id"`
	Name               string             `json:"name"`
	Amount             decimal.Decimal    `json:"amount"`
	RecurrenceInterval RecurrenceInterval `json:"recurrence_interval"`
	PaydayDayOfMonth   *int32             `json:"payday_day_of_month"`
	StartDate          pgtype.Date        `json:"start_date"`
	EndDate            pgtype.Date        `json:"end_date"`
}

func (q *Queries) CreateRecurringIncome(ctx context.Context, arg CreateRecurringIncomeParams) (RecurringIncome, error) {
	row := q.db.QueryRow(ctx, createRecurringIncome,
		arg.UserID,
		arg.Name,
		arg.Amount,
		arg.RecurrenceInterval,
		arg.PaydayDayOfMonth,
		arg.StartDate,
		arg.EndDate,
	)
	var i RecurringIncome
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.RecurrenceInterval,
		&i.PaydayDayOfMonth,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getIncomeByID = `-- name: GetIncomeByID :one
SELECT
  id,
  user_id,
  budget_id,
  name,
  amount,
  date,
  source_type,
  source_template_id,
  source_occurrence_date,
  generation_month,
  created_at,
  updated_at,
  deleted_at
FROM income
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetIncomeByID(ctx context.Context, id uuid.UUID) (Income, error) {
	row := q.db.QueryRow(ctx, getIncomeByID, id)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetID,
		&i.Name,
		&i.Amount,
		&i.Date,
		&i.SourceType,
		&i.SourceTemplateID,
		&i.SourceOccurrenceDate,
		&i.GenerationMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRecurringIncomeByID = `-- name: GetRecurringIncomeByID :one
SELECT
  id,
  user_id,
  name,
  amount,
  recurrence_interval,
  payday_day_of_month,
  start_date,
  end_date,
  created_at,
  updated_at,
  deleted_at
FROM recurring_income
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetRecurringIncomeByID(ctx context.Context, id uuid.UUID) (RecurringIncome, error) {
	row := q.db.QueryRow(ctx, getRecurringIncomeByID, id)
	var i RecurringIncome
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.RecurrenceInterval,
		&i.PaydayDayOfMonth,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listIncomeByBudgetID = `-- name: ListIncomeByBudgetID :many
SELECT
  id,
  user_id,
  budget_id,
  name,
  amount,
  date,
  source_type,
  source_template_id,
  source_occurrence_date,
  generation_month,
  created_at,
  updated_at,
  deleted_at
FROM income
WHERE budget_id = $1
  AND deleted_at IS NULL
ORDER BY date DESC, created_at DESC
`

func (q *Queries) ListIncomeByBudgetID(ctx context.Context, budgetID uuid.UUID) ([]Income, error) {
	rows, err := q.db.Query(ctx, listIncomeByBudgetID, budgetID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Income
	for rows.Next() {
		var i Income
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.BudgetID,
			&i.Name,
			&i.Amount,
			&i.Date,
			&i.SourceType,
			&i.SourceTemplateID,
			&i.SourceOccurrenceDate,
			&i.GenerationMonth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRecurringIncomeByUserID = `-- name: ListRecurringIncomeByUserID :many
SELECT
  id,
  user_id,
  name,
  amount,
  recurrence_interval,
  payday_day_of_month,
  start_date,
  end_date,
  created_at,
  updated_at,
  deleted_at
FROM recurring_income
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListRecurringIncomeByUserID(ctx context.Context, userID uuid.UUID) ([]RecurringIncome, error) {
	rows, err := q.db.Query(ctx, listRecurringIncomeByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringIncome
	for rows.Next() {
		var i RecurringIncome
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Amount,
			&i.RecurrenceInterval,
			&i.PaydayDayOfMonth,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteIncome = `-- name: SoftDeleteIncome :execrows
UPDATE income
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteIncome(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteIncome, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeleteRecurringIncome = `-- name: SoftDeleteRecurringIncome :execrows
UPDATE recurring_income
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRecurringIncome(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteRecurringIncome, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateIncome = `-- name: UpdateIncome :one
UPDATE income
SET
  name = $2,
  amount = $3,
  date = $4,
  source_type = $5,
  source_template_id = $6,
  source_occurrence_date = $7,
  generation_month = $8,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  user_id,
  budget_id,
  name,
  amount,
  date,
  source_type,
  source_template_id,
  source_occurrence_date,
  generation_month,
  created_at,
  updated_at,
  deleted_at
`

type UpdateIncomeParams struct {
	ID                   uuid.UUID        `json:"id"`
	Name                 string           `json:"name"`
	Amount               decimal.Decimal  `json:"amount"`
	Date                 pgtype.Date      `json:"date"`
	SourceType           IncomeSourceType `json:"source_type"`
	SourceTemplateID     pgtype.UUID      `json:"source_template_id"`
	SourceOccurrenceDate pgtype.Date      `json:"source_occurrence_date"`
	GenerationMonth      pgtype.Date      `json:"generation_month"`
}

func (q *Queries) UpdateIncome(ctx context.Context, arg UpdateIncomeParams) (Income, error) {
	row := q.db.QueryRow(ctx, updateIncome,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.Date,
		arg.SourceType,
		arg.SourceTemplateID,
		arg.SourceOccurrenceDate,
		arg.GenerationMonth,
	)
	var i Income
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.BudgetID,
		&i.Name,
		&i.Amount,
		&i.Date,
		&i.SourceType,
		&i.SourceTemplateID,
		&i.SourceOccurrenceDate,
		&i.GenerationMonth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const updateRecurringIncome = `-- name: UpdateRecurringIncome :one
UPDATE recurring_income
SET
  name = $2,
  amount = $3,
  recurrence_interval = $4,
  payday_day_of_month = $5,
  start_date = $6,
  end_date = $7,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  user_id,
  name,
  amount,
  recurrence_interval,
  payday_day_of_month,
  start_date,
  end_date,
  created_at,
  updated_at,
  deleted_at
`

type UpdateRecurringIncomeParams struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Amount             decimal.Decimal    `json:"amount"`
	RecurrenceInterval RecurrenceInterval `json:"recurrence_interval"`
	PaydayDayOfMonth   *int32             `json:"payday_day_of_month"`
	StartDate          pgtype.Date        `json:"start_date"`
	EndDate            pgtype.Date        `json:"end_date"`
}

func (q *Queries) UpdateRecurringIncome(ctx context.Context, arg UpdateRecurringIncomeParams) (RecurringIncome, error) {
	row := q.db.QueryRow(ctx, updateRecurringIncome,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.RecurrenceInterval,
		arg.PaydayDayOfMonth,
		arg.StartDate,
		arg.EndDate,
	)
	var i RecurringIncome
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.RecurrenceInterval,
		&i.PaydayDayOfMonth,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
