// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: liabilities.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
)

const createLiability = `-- name: CreateLiability :one
INSERT INTO liabilities (
  user_id,
  name,
  liability_type,
  current_balance,
  interest_rate,
  minimum_payment,
  target_extra_payment,
  payoff_priority
)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING
  id,
  user_id,
  name,
  liability_type,
  current_balance,
  interest_rate,
  minimum_payment,
  target_extra_payment,
  payoff_priority,
  last_balance_updated_at,
  created_at,
  updated_at,
  deleted_at
`

type CreateLiabilityParams struct {
	UserID             uuid.UUID       `json:"user_id"`
	Name               string          `json:"name"`
	LiabilityType      LiabilityType   `json:"liability_type"`
	CurrentBalance     decimal.Decimal `json:"current_balance"`
	InterestRate       decimal.Decimal `json:"interest_rate"`
	MinimumPayment     decimal.Decimal `json:"minimum_payment"`
	TargetExtraPayment decimal.Decimal `json:"target_extra_payment"`
	PayoffPriority     int32           `json:"payoff_priority"`
}

func (q *Queries) CreateLiability(ctx context.Context, arg CreateLiabilityParams) (Liability, error) {
	row := q.db.QueryRow(ctx, createLiability,
		arg.UserID,
		arg.Name,
		arg.LiabilityType,
		arg.CurrentBalance,
		arg.InterestRate,
		arg.MinimumPayment,
		arg.TargetExtraPayment,
		arg.PayoffPriority,
	)
	var i Liability
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.LiabilityType,
		&i.CurrentBalance,
		&i.InterestRate,
		&i.MinimumPayment,
		&i.TargetExtraPayment,
		&i.PayoffPriority,
		&i.LastBalanceUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLiabilityByID = `-- name: GetLiabilityByID :one
SELECT
  id,
  user_id,
  name,
  liability_type,
  current_balance,
  interest_rate,
  minimum_payment,
  target_extra_payment,
  payoff_priority,
  last_balance_updated_at,
  created_at,
  updated_at,
  deleted_at
FROM liabilities
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetLiabilityByID(ctx context.Context, id uuid.UUID) (Liability, error) {
	row := q.db.QueryRow(ctx, getLiabilityByID, id)
	var i Liability
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.LiabilityType,
		&i.CurrentBalance,
		&i.InterestRate,
		&i.MinimumPayment,
		&i.TargetExtraPayment,
		&i.PayoffPriority,
		&i.LastBalanceUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listLiabilitiesByUserID = `-- name: ListLiabilitiesByUserID :many
SELECT
  id,
  user_id,
  name,
  liability_type,
  current_balance,
  interest_rate,
  minimum_payment,
  target_extra_payment,
  payoff_priority,
  last_balance_updated_at,
  created_at,
  updated_at,
  deleted_at
FROM liabilities
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListLiabilitiesByUserID(ctx context.Context, userID uuid.UUID) ([]Liability, error) {
	rows, err := q.db.Query(ctx, listLiabilitiesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Liability
	for rows.Next() {
		var i Liability
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.LiabilityType,
			&i.CurrentBalance,
			&i.InterestRate,
			&i.MinimumPayment,
			&i.TargetExtraPayment,
			&i.PayoffPriority,
			&i.LastBalanceUpdatedAt,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteLiability = `-- name: SoftDeleteLiability :execrows
UPDATE liabilities
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteLiability(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteLiability, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateLiability = `-- name: UpdateLiability :one
UPDATE liabilities
SET
  name = $2,
  liability_type = $3,
  current_balance = $4,
  interest_rate = $5,
  minimum_payment = $6,
  target_extra_payment = $7,
  payoff_priority = $8,
  last_balance_updated_at = CASE
    WHEN current_balance IS DISTINCT FROM $4 THEN now()
    ELSE last_balance_updated_at
  END,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  user_id,
  name,
  liability_type,
  current_balance,
  interest_rate,
  minimum_payment,
  target_extra_payment,
  payoff_priority,
  last_balance_updated_at,
  created_at,
  updated_at,
  deleted_at
`

type UpdateLiabilityParams struct {
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	LiabilityType      LiabilityType   `json:"liability_type"`
	CurrentBalance     decimal.Decimal `json:"current_balance"`
	InterestRate       decimal.Decimal `json:"interest_rate"`
	MinimumPayment     decimal.Decimal `json:"minimum_payment"`
	TargetExtraPayment decimal.Decimal `json:"target_extra_payment"`
	PayoffPriority     int32           `json:"payoff_priority"`
}

func (q *Queries) UpdateLiability(ctx context.Context, arg UpdateLiabilityParams) (Liability, error) {
	row := q.db.QueryRow(ctx, updateLiability,
		arg.ID,
		arg.Name,
		arg.LiabilityType,
		arg.CurrentBalance,
		arg.InterestRate,
		arg.MinimumPayment,
		arg.TargetExtraPayment,
		arg.PayoffPriority,
	)
	var i Liability
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.LiabilityType,
		&i.CurrentBalance,
		&i.InterestRate,
		&i.MinimumPayment,
		&i.TargetExtraPayment,
		&i.PayoffPriority,
		&i.LastBalanceUpdatedAt,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
