// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"database/sql/driver"
	"fmt"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

type AssetType string

const (
	AssetTypeCHECKING       AssetType = "CHECKING"
	AssetTypeEMERGENCYFUND  AssetType = "EMERGENCY_FUND"
	AssetTypeBROKERAGE      AssetType = "BROKERAGE"
	AssetType401K           AssetType = "_401K"
	AssetType403B           AssetType = "_403B"
	AssetType457            AssetType = "_457"
	AssetTypeROTHIRA        AssetType = "ROTH_IRA"
	AssetTypeTRADITIONALIRA AssetType = "TRADITIONAL_IRA"
	AssetTypeHSA            AssetType = "HSA"
	AssetTypeHOME           AssetType = "HOME"
	AssetTypeVEHICLE        AssetType = "VEHICLE"
	AssetTypeOTHER          AssetType = "OTHER"
)

func (e *AssetType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = AssetType(s)
	case string:
		*e = AssetType(s)
	default:
		return fmt.Errorf("unsupported scan type for AssetType: %T", src)
	}
	return nil
}

type NullAssetType struct {
	AssetType AssetType `json:"asset_type"`
	Valid     bool      `json:"valid"` // Valid is true if AssetType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullAssetType) Scan(value interface{}) error {
	if value == nil {
		ns.AssetType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.AssetType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullAssetType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.AssetType), nil
}

type DeductionType string

const (
	DeductionTypeSTANDARD DeductionType = "STANDARD"
	DeductionTypeITEMIZED DeductionType = "ITEMIZED"
)

func (e *DeductionType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = DeductionType(s)
	case string:
		*e = DeductionType(s)
	default:
		return fmt.Errorf("unsupported scan type for DeductionType: %T", src)
	}
	return nil
}

type NullDeductionType struct {
	DeductionType DeductionType `json:"deduction_type"`
	Valid         bool          `json:"valid"` // Valid is true if DeductionType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullDeductionType) Scan(value interface{}) error {
	if value == nil {
		ns.DeductionType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.DeductionType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullDeductionType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.DeductionType), nil
}

type ExpenseSourceType string

const (
	ExpenseSourceTypeMANUAL            ExpenseSourceType = "MANUAL"
	ExpenseSourceTypeRECURRINGTEMPLATE ExpenseSourceType = "RECURRING_TEMPLATE"
)

func (e *ExpenseSourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ExpenseSourceType(s)
	case string:
		*e = ExpenseSourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for ExpenseSourceType: %T", src)
	}
	return nil
}

type NullExpenseSourceType struct {
	ExpenseSourceType ExpenseSourceType `json:"expense_source_type"`
	Valid             bool              `json:"valid"` // Valid is true if ExpenseSourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullExpenseSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.ExpenseSourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ExpenseSourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullExpenseSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ExpenseSourceType), nil
}

type FilingStatus string

const (
	FilingStatusSINGLE FilingStatus = "SINGLE"
	FilingStatusMFJ    FilingStatus = "MFJ"
	FilingStatusMFS    FilingStatus = "MFS"
	FilingStatusHOH    FilingStatus = "HOH"
)

func (e *FilingStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = FilingStatus(s)
	case string:
		*e = FilingStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for FilingStatus: %T", src)
	}
	return nil
}

type NullFilingStatus struct {
	FilingStatus FilingStatus `json:"filing_status"`
	Valid        bool         `json:"valid"` // Valid is true if FilingStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullFilingStatus) Scan(value interface{}) error {
	if value == nil {
		ns.FilingStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.FilingStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullFilingStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.FilingStatus), nil
}

type IncomeSourceType string

const (
	IncomeSourceTypeMANUAL            IncomeSourceType = "MANUAL"
	IncomeSourceTypeRECURRINGTEMPLATE IncomeSourceType = "RECURRING_TEMPLATE"
)

func (e *IncomeSourceType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = IncomeSourceType(s)
	case string:
		*e = IncomeSourceType(s)
	default:
		return fmt.Errorf("unsupported scan type for IncomeSourceType: %T", src)
	}
	return nil
}

type NullIncomeSourceType struct {
	IncomeSourceType IncomeSourceType `json:"income_source_type"`
	Valid            bool             `json:"valid"` // Valid is true if IncomeSourceType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullIncomeSourceType) Scan(value interface{}) error {
	if value == nil {
		ns.IncomeSourceType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.IncomeSourceType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullIncomeSourceType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.IncomeSourceType), nil
}

type LiabilityType string

const (
	LiabilityTypeMORTGAGE     LiabilityType = "MORTGAGE"
	LiabilityTypeCREDITCARD   LiabilityType = "CREDIT_CARD"
	LiabilityTypeSTUDENTLOAN  LiabilityType = "STUDENT_LOAN"
	LiabilityTypeAUTOLOAN     LiabilityType = "AUTO_LOAN"
	LiabilityTypePERSONALLOAN LiabilityType = "PERSONAL_LOAN"
	LiabilityTypeOTHER        LiabilityType = "OTHER"
)

func (e *LiabilityType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = LiabilityType(s)
	case string:
		*e = LiabilityType(s)
	default:
		return fmt.Errorf("unsupported scan type for LiabilityType: %T", src)
	}
	return nil
}

type NullLiabilityType struct {
	LiabilityType LiabilityType `json:"liability_type"`
	Valid         bool          `json:"valid"` // Valid is true if LiabilityType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullLiabilityType) Scan(value interface{}) error {
	if value == nil {
		ns.LiabilityType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.LiabilityType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullLiabilityType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.LiabilityType), nil
}

type PayoffStrategy string

const (
	PayoffStrategyAVALANCHE PayoffStrategy = "AVALANCHE"
	PayoffStrategySNOWBALL  PayoffStrategy = "SNOWBALL"
)

func (e *PayoffStrategy) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = PayoffStrategy(s)
	case string:
		*e = PayoffStrategy(s)
	default:
		return fmt.Errorf("unsupported scan type for PayoffStrategy: %T", src)
	}
	return nil
}

type NullPayoffStrategy struct {
	PayoffStrategy PayoffStrategy `json:"payoff_strategy"`
	Valid          bool           `json:"valid"` // Valid is true if PayoffStrategy is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullPayoffStrategy) Scan(value interface{}) error {
	if value == nil {
		ns.PayoffStrategy, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.PayoffStrategy.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullPayoffStrategy) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.PayoffStrategy), nil
}

type RecurrenceInterval string

const (
	RecurrenceIntervalNONE      RecurrenceInterval = "NONE"
	RecurrenceIntervalWEEKLY    RecurrenceInterval = "WEEKLY"
	RecurrenceIntervalBIWEEKLY  RecurrenceInterval = "BIWEEKLY"
	RecurrenceIntervalMONTHLY   RecurrenceInterval = "MONTHLY"
	RecurrenceIntervalQUARTERLY RecurrenceInterval = "QUARTERLY"
	RecurrenceIntervalYEARLY    RecurrenceInterval = "YEARLY"
)

func (e *RecurrenceInterval) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RecurrenceInterval(s)
	case string:
		*e = RecurrenceInterval(s)
	default:
		return fmt.Errorf("unsupported scan type for RecurrenceInterval: %T", src)
	}
	return nil
}

type NullRecurrenceInterval struct {
	RecurrenceInterval RecurrenceInterval `json:"recurrence_interval"`
	Valid              bool               `json:"valid"` // Valid is true if RecurrenceInterval is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRecurrenceInterval) Scan(value interface{}) error {
	if value == nil {
		ns.RecurrenceInterval, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RecurrenceInterval.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRecurrenceInterval) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RecurrenceInterval), nil
}

type RetirementAccountOwner string

const (
	RetirementAccountOwnerSELF   RetirementAccountOwner = "SELF"
	RetirementAccountOwnerSPOUSE RetirementAccountOwner = "SPOUSE"
)

func (e *RetirementAccountOwner) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RetirementAccountOwner(s)
	case string:
		*e = RetirementAccountOwner(s)
	default:
		return fmt.Errorf("unsupported scan type for RetirementAccountOwner: %T", src)
	}
	return nil
}

type NullRetirementAccountOwner struct {
	RetirementAccountOwner RetirementAccountOwner `json:"retirement_account_owner"`
	Valid                  bool                   `json:"valid"` // Valid is true if RetirementAccountOwner is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRetirementAccountOwner) Scan(value interface{}) error {
	if value == nil {
		ns.RetirementAccountOwner, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RetirementAccountOwner.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRetirementAccountOwner) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RetirementAccountOwner), nil
}

type RetirementAccountType string

const (
	RetirementAccountTypeACCOUNT401K    RetirementAccountType = "ACCOUNT_401K"
	RetirementAccountTypeACCOUNT403B    RetirementAccountType = "ACCOUNT_403B"
	RetirementAccountTypeACCOUNT457     RetirementAccountType = "ACCOUNT_457"
	RetirementAccountTypeROTHIRA        RetirementAccountType = "ROTH_IRA"
	RetirementAccountTypeTRADITIONALIRA RetirementAccountType = "TRADITIONAL_IRA"
	RetirementAccountTypeHSA            RetirementAccountType = "HSA"
	RetirementAccountTypeOTHER          RetirementAccountType = "OTHER"
)

func (e *RetirementAccountType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RetirementAccountType(s)
	case string:
		*e = RetirementAccountType(s)
	default:
		return fmt.Errorf("unsupported scan type for RetirementAccountType: %T", src)
	}
	return nil
}

type NullRetirementAccountType struct {
	RetirementAccountType RetirementAccountType `json:"retirement_account_type"`
	Valid                 bool                  `json:"valid"` // Valid is true if RetirementAccountType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRetirementAccountType) Scan(value interface{}) error {
	if value == nil {
		ns.RetirementAccountType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RetirementAccountType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRetirementAccountType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RetirementAccountType), nil
}

type RetirementTaxTreatment string

const (
	RetirementTaxTreatmentPRETAX      RetirementTaxTreatment = "PRE_TAX"
	RetirementTaxTreatmentROTH        RetirementTaxTreatment = "ROTH"
	RetirementTaxTreatmentTAXDEFERRED RetirementTaxTreatment = "TAX_DEFERRED"
	RetirementTaxTreatmentTAXABLE     RetirementTaxTreatment = "TAXABLE"
	RetirementTaxTreatmentOTHER       RetirementTaxTreatment = "OTHER"
)

func (e *RetirementTaxTreatment) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = RetirementTaxTreatment(s)
	case string:
		*e = RetirementTaxTreatment(s)
	default:
		return fmt.Errorf("unsupported scan type for RetirementTaxTreatment: %T", src)
	}
	return nil
}

type NullRetirementTaxTreatment struct {
	RetirementTaxTreatment RetirementTaxTreatment `json:"retirement_tax_treatment"`
	Valid                  bool                   `json:"valid"` // Valid is true if RetirementTaxTreatment is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullRetirementTaxTreatment) Scan(value interface{}) error {
	if value == nil {
		ns.RetirementTaxTreatment, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.RetirementTaxTreatment.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullRetirementTaxTreatment) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.RetirementTaxTreatment), nil
}

type ReturnType string

const (
	ReturnTypeREAL    ReturnType = "REAL"
	ReturnTypeNOMINAL ReturnType = "NOMINAL"
)

func (e *ReturnType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = ReturnType(s)
	case string:
		*e = ReturnType(s)
	default:
		return fmt.Errorf("unsupported scan type for ReturnType: %T", src)
	}
	return nil
}

type NullReturnType struct {
	ReturnType ReturnType `json:"return_type"`
	Valid      bool       `json:"valid"` // Valid is true if ReturnType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullReturnType) Scan(value interface{}) error {
	if value == nil {
		ns.ReturnType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.ReturnType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullReturnType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.ReturnType), nil
}

type Asset struct {
	ID                              uuid.UUID          `json:"id"`
	UserID                          uuid.UUID          `json:"user_id"`
	Name                            string             `json:"name"`
	AssetType                       AssetType          `json:"asset_type"`
	CurrentValue                    decimal.Decimal    `json:"current_value"`
	LastValueUpdatedAt              pgtype.Timestamptz `json:"last_value_updated_at"`
	CreatedAt                       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt                       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt                       pgtype.Timestamptz `json:"deleted_at"`
	ContributionMode                string             `json:"contribution_mode"`
	ContributionValue               decimal.Decimal    `json:"contribution_value"`
	EmployerMatchRate               decimal.Decimal    `json:"employer_match_rate"`
	EmployerMatchMaxPercentOfSalary decimal.Decimal    `json:"employer_match_max_percent_of_salary"`
	AnnualRate                      decimal.Decimal    `json:"annual_rate"`
	PersonIds                       []uuid.UUID        `json:"person_ids"`
	PurchaseDate                    pgtype.Date        `json:"purchase_date"`
	PurchasePrice                   pgtype.Numeric     `json:"purchase_price"`
	HomeGrowthProfile               *string            `json:"home_growth_profile"`
	VehicleDepreciationProfile      *string            `json:"vehicle_depreciation_profile"`
	LinkedLiabilityID               pgtype.UUID        `json:"linked_liability_id"`
}

type Budget struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Date            pgtype.Date        `json:"date"`
	MonthlyIncome   decimal.Decimal    `json:"monthly_income"`
	MonthlyExpenses decimal.Decimal    `json:"monthly_expenses"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type ContributionEntry struct {
	ID                  uuid.UUID          `json:"id"`
	RetirementAccountID uuid.UUID          `json:"retirement_account_id"`
	TaxYear             int32              `json:"tax_year"`
	ContributionDate    pgtype.Date        `json:"contribution_date"`
	Amount              decimal.Decimal    `json:"amount"`
	CreatedAt           pgtype.Timestamptz `json:"created_at"`
	UpdatedAt           pgtype.Timestamptz `json:"updated_at"`
	DeletedAt           pgtype.Timestamptz `json:"deleted_at"`
}

type ContributionLimit struct {
	ID            uuid.UUID             `json:"id"`
	AccountType   RetirementAccountType `json:"account_type"`
	TaxYear       int32                 `json:"tax_year"`
	AnnualLimit   decimal.Decimal       `json:"annual_limit"`
	CatchUpAge    int32                 `json:"catch_up_age"`
	CatchUpAmount decimal.Decimal       `json:"catch_up_amount"`
	CreatedAt     pgtype.Timestamptz    `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz    `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz    `json:"deleted_at"`
}

type Expense struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	BudgetID         uuid.UUID          `json:"budget_id"`
	Amount           decimal.Decimal    `json:"amount"`
	Date             pgtype.Date        `json:"date"`
	Description      string             `json:"description"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	SourceType       ExpenseSourceType  `json:"source_type"`
	SourceTemplateID pgtype.UUID        `json:"source_template_id"`
	GenerationMonth  pgtype.Date        `json:"generation_month"`
	PersonID         pgtype.UUID        `json:"person_id"`
}

type ExpenseCategory struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	BudgetID         uuid.UUID          `json:"budget_id"`
	Name             string             `json:"name"`
	Allocation       decimal.Decimal    `json:"allocation"`
	CurrentSpend     decimal.Decimal    `json:"current_spend"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
	SourceType       ExpenseSourceType  `json:"source_type"`
	SourceTemplateID pgtype.UUID        `json:"source_template_id"`
	GenerationMonth  pgtype.Date        `json:"generation_month"`
}

type ExpenseSplit struct {
	ID          uuid.UUID          `json:"id"`
	ExpenseID   uuid.UUID          `json:"expense_id"`
	CategoryID  uuid.UUID          `json:"category_id"`
	Amount      decimal.Decimal    `json:"amount"`
	Description *string            `json:"description"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Goal struct {
	ID          uuid.UUID          `json:"id"`
	UserID      uuid.UUID          `json:"user_id"`
	Description string             `json:"description"`
	IsCompleted bool               `json:"is_completed"`
	CreatedAt   pgtype.Timestamptz `json:"created_at"`
	UpdatedAt   pgtype.Timestamptz `json:"updated_at"`
	DeletedAt   pgtype.Timestamptz `json:"deleted_at"`
}

type Income struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	BudgetID             uuid.UUID          `json:"budget_id"`
	Name                 string             `json:"name"`
	Amount               decimal.Decimal    `json:"amount"`
	Date                 pgtype.Date        `json:"date"`
	SourceType           IncomeSourceType   `json:"source_type"`
	SourceTemplateID     pgtype.UUID        `json:"source_template_id"`
	SourceOccurrenceDate pgtype.Date        `json:"source_occurrence_date"`
	GenerationMonth      pgtype.Date        `json:"generation_month"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	PersonID             pgtype.UUID        `json:"person_id"`
}

type Liability struct {
	ID                   uuid.UUID          `json:"id"`
	UserID               uuid.UUID          `json:"user_id"`
	Name                 string             `json:"name"`
	LiabilityType        LiabilityType      `json:"liability_type"`
	CurrentBalance       decimal.Decimal    `json:"current_balance"`
	InterestRate         decimal.Decimal    `json:"interest_rate"`
	MinimumPayment       decimal.Decimal    `json:"minimum_payment"`
	TargetExtraPayment   decimal.Decimal    `json:"target_extra_payment"`
	PayoffPriority       int32              `json:"payoff_priority"`
	LastBalanceUpdatedAt pgtype.Timestamptz `json:"last_balance_updated_at"`
	CreatedAt            pgtype.Timestamptz `json:"created_at"`
	UpdatedAt            pgtype.Timestamptz `json:"updated_at"`
	DeletedAt            pgtype.Timestamptz `json:"deleted_at"`
	ContributionMode     string             `json:"contribution_mode"`
	ContributionValue    decimal.Decimal    `json:"contribution_value"`
	PersonIds            []uuid.UUID        `json:"person_ids"`
	OriginalLoanAmount   pgtype.Numeric     `json:"original_loan_amount"`
}

type NetWorthSnapshot struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	SnapshotDate     pgtype.Date        `json:"snapshot_date"`
	TotalAssets      decimal.Decimal    `json:"total_assets"`
	TotalLiabilities decimal.Decimal    `json:"total_liabilities"`
	NetWorth         decimal.Decimal    `json:"net_worth"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type PlaidAccount struct {
	ID                uuid.UUID          `json:"id"`
	PlaidConnectionID uuid.UUID          `json:"plaid_connection_id"`
	ExternalID        string             `json:"external_id"`
	Name              string             `json:"name"`
	OfficialName      *string            `json:"official_name"`
	Type              *string            `json:"type"`
	Subtype           *string            `json:"subtype"`
	CurrentBalance    pgtype.Numeric     `json:"current_balance"`
	IsoCurrencyCode   *string            `json:"iso_currency_code"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type PlaidConnection struct {
	ID              uuid.UUID          `json:"id"`
	UserID          uuid.UUID          `json:"user_id"`
	Environment     string             `json:"environment"`
	InstitutionID   *string            `json:"institution_id"`
	InstitutionName *string            `json:"institution_name"`
	AccessToken     string             `json:"access_token"`
	ItemID          string             `json:"item_id"`
	CreatedAt       pgtype.Timestamptz `json:"created_at"`
	UpdatedAt       pgtype.Timestamptz `json:"updated_at"`
	DeletedAt       pgtype.Timestamptz `json:"deleted_at"`
}

type PlannerPerson struct {
	ID               uuid.UUID          `json:"id"`
	UserID           uuid.UUID          `json:"user_id"`
	Name             string             `json:"name"`
	Birthday         string             `json:"birthday"`
	RetirementAge    int32              `json:"retirement_age"`
	AnnualSalary     decimal.Decimal    `json:"annual_salary"`
	BonusMode        string             `json:"bonus_mode"`
	AnnualBonus      decimal.Decimal    `json:"annual_bonus"`
	IncomeGrowthRate decimal.Decimal    `json:"income_growth_rate"`
	CreatedAt        pgtype.Timestamptz `json:"created_at"`
	UpdatedAt        pgtype.Timestamptz `json:"updated_at"`
	DeletedAt        pgtype.Timestamptz `json:"deleted_at"`
}

type RecurringExpense struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	Name               string             `json:"name"`
	Amount             decimal.Decimal    `json:"amount"`
	RecurrenceInterval RecurrenceInterval `json:"recurrence_interval"`
	PaydayDayOfMonth   *int32             `json:"payday_day_of_month"`
	StartDate          pgtype.Date        `json:"start_date"`
	EndDate            pgtype.Date        `json:"end_date"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	PersonID           pgtype.UUID        `json:"person_id"`
}

type RecurringIncome struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	Name               string             `json:"name"`
	Amount             decimal.Decimal    `json:"amount"`
	RecurrenceInterval RecurrenceInterval `json:"recurrence_interval"`
	PaydayDayOfMonth   *int32             `json:"payday_day_of_month"`
	StartDate          pgtype.Date        `json:"start_date"`
	EndDate            pgtype.Date        `json:"end_date"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	PersonID           pgtype.UUID        `json:"person_id"`
}

type RetirementAccount struct {
	ID                      uuid.UUID              `json:"id"`
	UserID                  uuid.UUID              `json:"user_id"`
	Name                    string                 `json:"name"`
	AccountType             RetirementAccountType  `json:"account_type"`
	Owner                   RetirementAccountOwner `json:"owner"`
	TaxTreatment            RetirementTaxTreatment `json:"tax_treatment"`
	CurrentBalance          decimal.Decimal        `json:"current_balance"`
	AnnualContributionLimit decimal.Decimal        `json:"annual_contribution_limit"`
	CreatedAt               pgtype.Timestamptz     `json:"created_at"`
	UpdatedAt               pgtype.Timestamptz     `json:"updated_at"`
	DeletedAt               pgtype.Timestamptz     `json:"deleted_at"`
}

type ScenarioOverride struct {
	ID                uuid.UUID          `json:"id"`
	ScenarioProfileID uuid.UUID          `json:"scenario_profile_id"`
	OverrideKey       string             `json:"override_key"`
	OverrideValue     decimal.Decimal    `json:"override_value"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
	DeletedAt         pgtype.Timestamptz `json:"deleted_at"`
}

type ScenarioProfile struct {
	ID                 uuid.UUID          `json:"id"`
	UserID             uuid.UUID          `json:"user_id"`
	Name               string             `json:"name"`
	CurrentAge         int32              `json:"current_age"`
	RetirementAge      int32              `json:"retirement_age"`
	AnnualSpend        decimal.Decimal    `json:"annual_spend"`
	SafeWithdrawalRate decimal.Decimal    `json:"safe_withdrawal_rate"`
	InflationRate      decimal.Decimal    `json:"inflation_rate"`
	ReturnRate         decimal.Decimal    `json:"return_rate"`
	CurrentPortfolio   decimal.Decimal    `json:"current_portfolio"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
}

type ScenarioResultsCache struct {
	ID                    uuid.UUID          `json:"id"`
	ScenarioProfileID     uuid.UUID          `json:"scenario_profile_id"`
	PortfolioAtRetirement decimal.Decimal    `json:"portfolio_at_retirement"`
	RequiredPortfolio     decimal.Decimal    `json:"required_portfolio"`
	ProjectedDepletionAge *int32             `json:"projected_depletion_age"`
	IsSustainable         bool               `json:"is_sustainable"`
	CreatedAt             pgtype.Timestamptz `json:"created_at"`
	UpdatedAt             pgtype.Timestamptz `json:"updated_at"`
	DeletedAt             pgtype.Timestamptz `json:"deleted_at"`
}

type TaxBracket struct {
	ID            uuid.UUID          `json:"id"`
	Year          int32              `json:"year"`
	FilingStatus  FilingStatus       `json:"filing_status"`
	MinimumAmount decimal.Decimal    `json:"minimum_amount"`
	MaximumAmount pgtype.Numeric     `json:"maximum_amount"`
	Rate          decimal.Decimal    `json:"rate"`
	CreatedAt     pgtype.Timestamptz `json:"created_at"`
	UpdatedAt     pgtype.Timestamptz `json:"updated_at"`
	DeletedAt     pgtype.Timestamptz `json:"deleted_at"`
}

type User struct {
	ID                 uuid.UUID          `json:"id"`
	Email              string             `json:"email"`
	CreatedAt          pgtype.Timestamptz `json:"created_at"`
	UpdatedAt          pgtype.Timestamptz `json:"updated_at"`
	DeletedAt          pgtype.Timestamptz `json:"deleted_at"`
	IdentityProviderID string             `json:"identity_provider_id"`
	ReturnType         ReturnType         `json:"return_type"`
	SafeWithdrawalRate decimal.Decimal    `json:"safe_withdrawal_rate"`
	CurrencyType       string             `json:"currency_type"`
	InflationRate      decimal.Decimal    `json:"inflation_rate"`
	DeductionType      DeductionType      `json:"deduction_type"`
	DeductionAmount    pgtype.Numeric     `json:"deduction_amount"`
	MaxTaxBracketID    pgtype.UUID        `json:"max_tax_bracket_id"`
	FilingStatus       FilingStatus       `json:"filing_status"`
	PayoffStrategy     PayoffStrategy     `json:"payoff_strategy"`
}
