// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: net_worth_snapshots.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const createNetWorthSnapshot = `-- name: CreateNetWorthSnapshot :one
INSERT INTO net_worth_snapshots (
    user_id,
    snapshot_date,
    total_assets,
    total_liabilities,
    net_worth
) VALUES (
    $1, $2, $3, $4, $5
) RETURNING id, user_id, snapshot_date, total_assets, total_liabilities, net_worth, created_at, updated_at, deleted_at
`

type CreateNetWorthSnapshotParams struct {
	UserID           uuid.UUID       `json:"user_id"`
	SnapshotDate     pgtype.Date     `json:"snapshot_date"`
	TotalAssets      decimal.Decimal `json:"total_assets"`
	TotalLiabilities decimal.Decimal `json:"total_liabilities"`
	NetWorth         decimal.Decimal `json:"net_worth"`
}

func (q *Queries) CreateNetWorthSnapshot(ctx context.Context, arg CreateNetWorthSnapshotParams) (NetWorthSnapshot, error) {
	row := q.db.QueryRow(ctx, createNetWorthSnapshot,
		arg.UserID,
		arg.SnapshotDate,
		arg.TotalAssets,
		arg.TotalLiabilities,
		arg.NetWorth,
	)
	var i NetWorthSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SnapshotDate,
		&i.TotalAssets,
		&i.TotalLiabilities,
		&i.NetWorth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const deleteNetWorthSnapshot = `-- name: DeleteNetWorthSnapshot :exec
UPDATE net_worth_snapshots
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) DeleteNetWorthSnapshot(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, deleteNetWorthSnapshot, id)
	return err
}

const getNetWorthSnapshot = `-- name: GetNetWorthSnapshot :one
SELECT id, user_id, snapshot_date, total_assets, total_liabilities, net_worth, created_at, updated_at, deleted_at FROM net_worth_snapshots
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) GetNetWorthSnapshot(ctx context.Context, id uuid.UUID) (NetWorthSnapshot, error) {
	row := q.db.QueryRow(ctx, getNetWorthSnapshot, id)
	var i NetWorthSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SnapshotDate,
		&i.TotalAssets,
		&i.TotalLiabilities,
		&i.NetWorth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getNetWorthSnapshotByDate = `-- name: GetNetWorthSnapshotByDate :one
SELECT id, user_id, snapshot_date, total_assets, total_liabilities, net_worth, created_at, updated_at, deleted_at FROM net_worth_snapshots
WHERE user_id = $1 AND snapshot_date = $2 AND deleted_at IS NULL
`

type GetNetWorthSnapshotByDateParams struct {
	UserID       uuid.UUID   `json:"user_id"`
	SnapshotDate pgtype.Date `json:"snapshot_date"`
}

func (q *Queries) GetNetWorthSnapshotByDate(ctx context.Context, arg GetNetWorthSnapshotByDateParams) (NetWorthSnapshot, error) {
	row := q.db.QueryRow(ctx, getNetWorthSnapshotByDate, arg.UserID, arg.SnapshotDate)
	var i NetWorthSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SnapshotDate,
		&i.TotalAssets,
		&i.TotalLiabilities,
		&i.NetWorth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listNetWorthSnapshots = `-- name: ListNetWorthSnapshots :many
SELECT id, user_id, snapshot_date, total_assets, total_liabilities, net_worth, created_at, updated_at, deleted_at FROM net_worth_snapshots
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY snapshot_date ASC
`

func (q *Queries) ListNetWorthSnapshots(ctx context.Context, userID uuid.UUID) ([]NetWorthSnapshot, error) {
	rows, err := q.db.Query(ctx, listNetWorthSnapshots, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []NetWorthSnapshot
	for rows.Next() {
		var i NetWorthSnapshot
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.SnapshotDate,
			&i.TotalAssets,
			&i.TotalLiabilities,
			&i.NetWorth,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateNetWorthSnapshot = `-- name: UpdateNetWorthSnapshot :one
UPDATE net_worth_snapshots
SET 
    total_assets = COALESCE($2, total_assets),
    total_liabilities = COALESCE($3, total_liabilities),
    net_worth = COALESCE($4, net_worth),
    updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, snapshot_date, total_assets, total_liabilities, net_worth, created_at, updated_at, deleted_at
`

type UpdateNetWorthSnapshotParams struct {
	ID               uuid.UUID      `json:"id"`
	TotalAssets      pgtype.Numeric `json:"total_assets"`
	TotalLiabilities pgtype.Numeric `json:"total_liabilities"`
	NetWorth         pgtype.Numeric `json:"net_worth"`
}

func (q *Queries) UpdateNetWorthSnapshot(ctx context.Context, arg UpdateNetWorthSnapshotParams) (NetWorthSnapshot, error) {
	row := q.db.QueryRow(ctx, updateNetWorthSnapshot,
		arg.ID,
		arg.TotalAssets,
		arg.TotalLiabilities,
		arg.NetWorth,
	)
	var i NetWorthSnapshot
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.SnapshotDate,
		&i.TotalAssets,
		&i.TotalLiabilities,
		&i.NetWorth,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
