// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: paycheck_deductions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const listPaycheckDeductionsByPersonID = `-- name: ListPaycheckDeductionsByPersonID :many
SELECT id, user_id, person_id, name, amount, pretax, kind, linked_account_id, created_at, updated_at, deleted_at FROM paycheck_deductions
WHERE user_id = $1 AND person_id = $2 AND deleted_at IS NULL
ORDER BY created_at ASC
`

type ListPaycheckDeductionsByPersonIDParams struct {
	UserID   uuid.UUID `json:"user_id"`
	PersonID uuid.UUID `json:"person_id"`
}

func (q *Queries) ListPaycheckDeductionsByPersonID(ctx context.Context, arg ListPaycheckDeductionsByPersonIDParams) ([]PaycheckDeduction, error) {
	rows, err := q.db.Query(ctx, listPaycheckDeductionsByPersonID, arg.UserID, arg.PersonID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaycheckDeduction
	for rows.Next() {
		var i PaycheckDeduction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PersonID,
			&i.Name,
			&i.Amount,
			&i.Pretax,
			&i.Kind,
			&i.LinkedAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listPaycheckDeductionsByUserID = `-- name: ListPaycheckDeductionsByUserID :many
SELECT id, user_id, person_id, name, amount, pretax, kind, linked_account_id, created_at, updated_at, deleted_at FROM paycheck_deductions
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListPaycheckDeductionsByUserID(ctx context.Context, userID uuid.UUID) ([]PaycheckDeduction, error) {
	rows, err := q.db.Query(ctx, listPaycheckDeductionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PaycheckDeduction
	for rows.Next() {
		var i PaycheckDeduction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PersonID,
			&i.Name,
			&i.Amount,
			&i.Pretax,
			&i.Kind,
			&i.LinkedAccountID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePaycheckDeduction = `-- name: SoftDeletePaycheckDeduction :execrows
UPDATE paycheck_deductions
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeletePaycheckDeductionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeletePaycheckDeduction(ctx context.Context, arg SoftDeletePaycheckDeductionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePaycheckDeduction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPaycheckDeduction = `-- name: UpsertPaycheckDeduction :one
INSERT INTO paycheck_deductions (id, user_id, person_id, name, amount, pretax, kind, linked_account_id)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    amount = EXCLUDED.amount,
    pretax = EXCLUDED.pretax,
    updated_at = now()
WHERE paycheck_deductions.user_id = EXCLUDED.user_id
RETURNING id, user_id, person_id, name, amount, pretax, kind, linked_account_id, created_at, updated_at, deleted_at
`

type UpsertPaycheckDeductionParams struct {
	ID              uuid.UUID       `json:"id"`
	UserID          uuid.UUID       `json:"user_id"`
	PersonID        uuid.UUID       `json:"person_id"`
	Name            string          `json:"name"`
	Amount          decimal.Decimal `json:"amount"`
	Pretax          bool            `json:"pretax"`
	Kind            string          `json:"kind"`
	LinkedAccountID pgtype.UUID     `json:"linked_account_id"`
}

func (q *Queries) UpsertPaycheckDeduction(ctx context.Context, arg UpsertPaycheckDeductionParams) (PaycheckDeduction, error) {
	row := q.db.QueryRow(ctx, upsertPaycheckDeduction,
		arg.ID,
		arg.UserID,
		arg.PersonID,
		arg.Name,
		arg.Amount,
		arg.Pretax,
		arg.Kind,
		arg.LinkedAccountID,
	)
	var i PaycheckDeduction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PersonID,
		&i.Name,
		&i.Amount,
		&i.Pretax,
		&i.Kind,
		&i.LinkedAccountID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
