// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plaid.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/jackc/pgx/v5/pgtype"
)

const createPlaidAccount = `-- name: CreatePlaidAccount :one
INSERT INTO plaid_accounts (
  plaid_connection_id, external_id, name, official_name, type, subtype, current_balance, iso_currency_code
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
RETURNING id, plaid_connection_id, external_id, name, official_name, type, subtype, current_balance, iso_currency_code, created_at, updated_at, deleted_at
`

type CreatePlaidAccountParams struct {
	PlaidConnectionID uuid.UUID      `json:"plaid_connection_id"`
	ExternalID        string         `json:"external_id"`
	Name              string         `json:"name"`
	OfficialName      *string        `json:"official_name"`
	Type              *string        `json:"type"`
	Subtype           *string        `json:"subtype"`
	CurrentBalance    pgtype.Numeric `json:"current_balance"`
	IsoCurrencyCode   *string        `json:"iso_currency_code"`
}

func (q *Queries) CreatePlaidAccount(ctx context.Context, arg CreatePlaidAccountParams) (PlaidAccount, error) {
	row := q.db.QueryRow(ctx, createPlaidAccount,
		arg.PlaidConnectionID,
		arg.ExternalID,
		arg.Name,
		arg.OfficialName,
		arg.Type,
		arg.Subtype,
		arg.CurrentBalance,
		arg.IsoCurrencyCode,
	)
	var i PlaidAccount
	err := row.Scan(
		&i.ID,
		&i.PlaidConnectionID,
		&i.ExternalID,
		&i.Name,
		&i.OfficialName,
		&i.Type,
		&i.Subtype,
		&i.CurrentBalance,
		&i.IsoCurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createPlaidConnection = `-- name: CreatePlaidConnection :one
INSERT INTO plaid_connections (
  user_id, environment, institution_id, institution_name, access_token, item_id
) VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id, user_id, environment, institution_id, institution_name, access_token, item_id, created_at, updated_at, deleted_at
`

type CreatePlaidConnectionParams struct {
	UserID          uuid.UUID `json:"user_id"`
	Environment     string    `json:"environment"`
	InstitutionID   *string   `json:"institution_id"`
	InstitutionName *string   `json:"institution_name"`
	AccessToken     string    `json:"access_token"`
	ItemID          string    `json:"item_id"`
}

func (q *Queries) CreatePlaidConnection(ctx context.Context, arg CreatePlaidConnectionParams) (PlaidConnection, error) {
	row := q.db.QueryRow(ctx, createPlaidConnection,
		arg.UserID,
		arg.Environment,
		arg.InstitutionID,
		arg.InstitutionName,
		arg.AccessToken,
		arg.ItemID,
	)
	var i PlaidConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Environment,
		&i.InstitutionID,
		&i.InstitutionName,
		&i.AccessToken,
		&i.ItemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getPlaidAccountsByConnectionID = `-- name: GetPlaidAccountsByConnectionID :many
SELECT id, plaid_connection_id, external_id, name, official_name, type, subtype, current_balance, iso_currency_code, created_at, updated_at, deleted_at
FROM plaid_accounts
WHERE plaid_connection_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) GetPlaidAccountsByConnectionID(ctx context.Context, plaidConnectionID uuid.UUID) ([]PlaidAccount, error) {
	rows, err := q.db.Query(ctx, getPlaidAccountsByConnectionID, plaidConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaidAccount
	for rows.Next() {
		var i PlaidAccount
		if err := rows.Scan(
			&i.ID,
			&i.PlaidConnectionID,
			&i.ExternalID,
			&i.Name,
			&i.OfficialName,
			&i.Type,
			&i.Subtype,
			&i.CurrentBalance,
			&i.IsoCurrencyCode,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getPlaidConnectionByID = `-- name: GetPlaidConnectionByID :one
SELECT id, user_id, environment, institution_id, institution_name, access_token, item_id, created_at, updated_at, deleted_at
FROM plaid_connections
WHERE id = $1 AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetPlaidConnectionByID(ctx context.Context, id uuid.UUID) (PlaidConnection, error) {
	row := q.db.QueryRow(ctx, getPlaidConnectionByID, id)
	var i PlaidConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Environment,
		&i.InstitutionID,
		&i.InstitutionName,
		&i.AccessToken,
		&i.ItemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listPlaidConnectionsByUserID = `-- name: ListPlaidConnectionsByUserID :many
SELECT id, user_id, environment, institution_id, institution_name, access_token, item_id, created_at, updated_at, deleted_at
FROM plaid_connections
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListPlaidConnectionsByUserID(ctx context.Context, userID uuid.UUID) ([]PlaidConnection, error) {
	rows, err := q.db.Query(ctx, listPlaidConnectionsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlaidConnection
	for rows.Next() {
		var i PlaidConnection
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Environment,
			&i.InstitutionID,
			&i.InstitutionName,
			&i.AccessToken,
			&i.ItemID,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePlaidAccount = `-- name: SoftDeletePlaidAccount :execrows
UPDATE plaid_accounts SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePlaidAccount(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePlaidAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeletePlaidConnection = `-- name: SoftDeletePlaidConnection :execrows
UPDATE plaid_connections SET deleted_at = now(), updated_at = now() WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePlaidConnection(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePlaidConnection, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updatePlaidConnection = `-- name: UpdatePlaidConnection :one
UPDATE plaid_connections SET
  institution_id = $2,
  institution_name = $3,
  access_token = $4,
  item_id = $5,
  updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
RETURNING id, user_id, environment, institution_id, institution_name, access_token, item_id, created_at, updated_at, deleted_at
`

type UpdatePlaidConnectionParams struct {
	ID              uuid.UUID `json:"id"`
	InstitutionID   *string   `json:"institution_id"`
	InstitutionName *string   `json:"institution_name"`
	AccessToken     string    `json:"access_token"`
	ItemID          string    `json:"item_id"`
}

func (q *Queries) UpdatePlaidConnection(ctx context.Context, arg UpdatePlaidConnectionParams) (PlaidConnection, error) {
	row := q.db.QueryRow(ctx, updatePlaidConnection,
		arg.ID,
		arg.InstitutionID,
		arg.InstitutionName,
		arg.AccessToken,
		arg.ItemID,
	)
	var i PlaidConnection
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Environment,
		&i.InstitutionID,
		&i.InstitutionName,
		&i.AccessToken,
		&i.ItemID,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertPlaidAccount = `-- name: UpsertPlaidAccount :one
INSERT INTO plaid_accounts (
  plaid_connection_id, external_id, name, official_name, type, subtype, current_balance, iso_currency_code
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8)
ON CONFLICT (external_id) DO UPDATE SET
  name = EXCLUDED.name,
  official_name = EXCLUDED.official_name,
  type = EXCLUDED.type,
  subtype = EXCLUDED.subtype,
  current_balance = EXCLUDED.current_balance,
  iso_currency_code = EXCLUDED.iso_currency_code,
  updated_at = now()
RETURNING id, plaid_connection_id, external_id, name, official_name, type, subtype, current_balance, iso_currency_code, created_at, updated_at, deleted_at
`

type UpsertPlaidAccountParams struct {
	PlaidConnectionID uuid.UUID      `json:"plaid_connection_id"`
	ExternalID        string         `json:"external_id"`
	Name              string         `json:"name"`
	OfficialName      *string        `json:"official_name"`
	Type              *string        `json:"type"`
	Subtype           *string        `json:"subtype"`
	CurrentBalance    pgtype.Numeric `json:"current_balance"`
	IsoCurrencyCode   *string        `json:"iso_currency_code"`
}

func (q *Queries) UpsertPlaidAccount(ctx context.Context, arg UpsertPlaidAccountParams) (PlaidAccount, error) {
	row := q.db.QueryRow(ctx, upsertPlaidAccount,
		arg.PlaidConnectionID,
		arg.ExternalID,
		arg.Name,
		arg.OfficialName,
		arg.Type,
		arg.Subtype,
		arg.CurrentBalance,
		arg.IsoCurrencyCode,
	)
	var i PlaidAccount
	err := row.Scan(
		&i.ID,
		&i.PlaidConnectionID,
		&i.ExternalID,
		&i.Name,
		&i.OfficialName,
		&i.Type,
		&i.Subtype,
		&i.CurrentBalance,
		&i.IsoCurrencyCode,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
