// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: plaid_linking.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const getAssetsByPlaidAccountID = `-- name: GetAssetsByPlaidAccountID :many
SELECT a.id, a.name, a.asset_type, a.current_value
FROM assets a
WHERE a.plaid_account_id = $1
  AND a.deleted_at IS NULL
`

type GetAssetsByPlaidAccountIDRow struct {
	ID           uuid.UUID       `json:"id"`
	Name         string          `json:"name"`
	AssetType    AssetType       `json:"asset_type"`
	CurrentValue decimal.Decimal `json:"current_value"`
}

func (q *Queries) GetAssetsByPlaidAccountID(ctx context.Context, plaidAccountID pgtype.UUID) ([]GetAssetsByPlaidAccountIDRow, error) {
	rows, err := q.db.Query(ctx, getAssetsByPlaidAccountID, plaidAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetAssetsByPlaidAccountIDRow
	for rows.Next() {
		var i GetAssetsByPlaidAccountIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.AssetType,
			&i.CurrentValue,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const getLiabilitiesByPlaidAccountID = `-- name: GetLiabilitiesByPlaidAccountID :many
SELECT l.id, l.name, l.liability_type, l.current_balance
FROM liabilities l
WHERE l.plaid_account_id = $1
  AND l.deleted_at IS NULL
`

type GetLiabilitiesByPlaidAccountIDRow struct {
	ID             uuid.UUID       `json:"id"`
	Name           string          `json:"name"`
	LiabilityType  LiabilityType   `json:"liability_type"`
	CurrentBalance decimal.Decimal `json:"current_balance"`
}

func (q *Queries) GetLiabilitiesByPlaidAccountID(ctx context.Context, plaidAccountID pgtype.UUID) ([]GetLiabilitiesByPlaidAccountIDRow, error) {
	rows, err := q.db.Query(ctx, getLiabilitiesByPlaidAccountID, plaidAccountID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GetLiabilitiesByPlaidAccountIDRow
	for rows.Next() {
		var i GetLiabilitiesByPlaidAccountIDRow
		if err := rows.Scan(
			&i.ID,
			&i.Name,
			&i.LiabilityType,
			&i.CurrentBalance,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const linkAssetToPlaidAccount = `-- name: LinkAssetToPlaidAccount :exec
UPDATE assets
SET plaid_account_id = $2,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

type LinkAssetToPlaidAccountParams struct {
	ID             uuid.UUID   `json:"id"`
	PlaidAccountID pgtype.UUID `json:"plaid_account_id"`
}

func (q *Queries) LinkAssetToPlaidAccount(ctx context.Context, arg LinkAssetToPlaidAccountParams) error {
	_, err := q.db.Exec(ctx, linkAssetToPlaidAccount, arg.ID, arg.PlaidAccountID)
	return err
}

const linkLiabilityToPlaidAccount = `-- name: LinkLiabilityToPlaidAccount :exec
UPDATE liabilities
SET plaid_account_id = $2,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

type LinkLiabilityToPlaidAccountParams struct {
	ID             uuid.UUID   `json:"id"`
	PlaidAccountID pgtype.UUID `json:"plaid_account_id"`
}

func (q *Queries) LinkLiabilityToPlaidAccount(ctx context.Context, arg LinkLiabilityToPlaidAccountParams) error {
	_, err := q.db.Exec(ctx, linkLiabilityToPlaidAccount, arg.ID, arg.PlaidAccountID)
	return err
}

const listPlaidAccountsByConnectionID = `-- name: ListPlaidAccountsByConnectionID :many
SELECT id, plaid_connection_id, external_id, name, official_name, type, subtype, current_balance, iso_currency_code, created_at, updated_at
FROM plaid_accounts
WHERE plaid_connection_id = $1
ORDER BY name
`

type ListPlaidAccountsByConnectionIDRow struct {
	ID                uuid.UUID          `json:"id"`
	PlaidConnectionID uuid.UUID          `json:"plaid_connection_id"`
	ExternalID        string             `json:"external_id"`
	Name              string             `json:"name"`
	OfficialName      *string            `json:"official_name"`
	Type              *string            `json:"type"`
	Subtype           *string            `json:"subtype"`
	CurrentBalance    pgtype.Numeric     `json:"current_balance"`
	IsoCurrencyCode   *string            `json:"iso_currency_code"`
	CreatedAt         pgtype.Timestamptz `json:"created_at"`
	UpdatedAt         pgtype.Timestamptz `json:"updated_at"`
}

func (q *Queries) ListPlaidAccountsByConnectionID(ctx context.Context, plaidConnectionID uuid.UUID) ([]ListPlaidAccountsByConnectionIDRow, error) {
	rows, err := q.db.Query(ctx, listPlaidAccountsByConnectionID, plaidConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListPlaidAccountsByConnectionIDRow
	for rows.Next() {
		var i ListPlaidAccountsByConnectionIDRow
		if err := rows.Scan(
			&i.ID,
			&i.PlaidConnectionID,
			&i.ExternalID,
			&i.Name,
			&i.OfficialName,
			&i.Type,
			&i.Subtype,
			&i.CurrentBalance,
			&i.IsoCurrencyCode,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const unlinkAssetFromPlaidAccount = `-- name: UnlinkAssetFromPlaidAccount :exec
UPDATE assets
SET plaid_account_id = NULL,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) UnlinkAssetFromPlaidAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unlinkAssetFromPlaidAccount, id)
	return err
}

const unlinkLiabilityFromPlaidAccount = `-- name: UnlinkLiabilityFromPlaidAccount :exec
UPDATE liabilities
SET plaid_account_id = NULL,
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) UnlinkLiabilityFromPlaidAccount(ctx context.Context, id uuid.UUID) error {
	_, err := q.db.Exec(ctx, unlinkLiabilityFromPlaidAccount, id)
	return err
}
