// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planner_people.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
)

const listPlannerPeopleByUserID = `-- name: ListPlannerPeopleByUserID :many
SELECT id, user_id, name, birthday, retirement_age, annual_salary, bonus_mode, bonus_frequency, annual_bonus, income_growth_rate, pay_type, pay_day, pay_cadence, hourly_rate, expected_hours_per_week, created_at, updated_at, deleted_at
FROM planner_people
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListPlannerPeopleByUserID(ctx context.Context, userID uuid.UUID) ([]PlannerPerson, error) {
	rows, err := q.db.Query(ctx, listPlannerPeopleByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannerPerson
	for rows.Next() {
		var i PlannerPerson
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Birthday,
			&i.RetirementAge,
			&i.AnnualSalary,
			&i.BonusMode,
			&i.BonusFrequency,
			&i.AnnualBonus,
			&i.IncomeGrowthRate,
			&i.PayType,
			&i.PayDay,
			&i.PayCadence,
			&i.HourlyRate,
			&i.ExpectedHoursPerWeek,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePlannerPeopleByUserID = `-- name: SoftDeletePlannerPeopleByUserID :execrows
UPDATE planner_people
SET deleted_at = now(), updated_at = now()
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePlannerPeopleByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePlannerPeopleByUserID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeletePlannerPerson = `-- name: SoftDeletePlannerPerson :execrows
UPDATE planner_people
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeletePlannerPersonParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeletePlannerPerson(ctx context.Context, arg SoftDeletePlannerPersonParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePlannerPerson, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPlannerPerson = `-- name: UpsertPlannerPerson :one
INSERT INTO planner_people (id, user_id, name, birthday, retirement_age, annual_salary, bonus_mode, bonus_frequency, annual_bonus, income_growth_rate, pay_type, pay_day, pay_cadence, hourly_rate, expected_hours_per_week)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, $13, $14, $15)
ON CONFLICT (id) DO UPDATE
SET name = EXCLUDED.name,
    birthday = EXCLUDED.birthday,
    retirement_age = EXCLUDED.retirement_age,
    annual_salary = EXCLUDED.annual_salary,
    bonus_mode = EXCLUDED.bonus_mode,
    bonus_frequency = EXCLUDED.bonus_frequency,
    annual_bonus = EXCLUDED.annual_bonus,
    income_growth_rate = EXCLUDED.income_growth_rate,
    pay_type = EXCLUDED.pay_type,
    pay_day = EXCLUDED.pay_day,
    pay_cadence = EXCLUDED.pay_cadence,
    hourly_rate = EXCLUDED.hourly_rate,
    expected_hours_per_week = EXCLUDED.expected_hours_per_week,
    updated_at = now()
RETURNING id, user_id, name, birthday, retirement_age, annual_salary, bonus_mode, bonus_frequency, annual_bonus, income_growth_rate, pay_type, pay_day, pay_cadence, hourly_rate, expected_hours_per_week, created_at, updated_at, deleted_at
`

type UpsertPlannerPersonParams struct {
	ID                   uuid.UUID       `json:"id"`
	UserID               uuid.UUID       `json:"user_id"`
	Name                 string          `json:"name"`
	Birthday             string          `json:"birthday"`
	RetirementAge        int32           `json:"retirement_age"`
	AnnualSalary         decimal.Decimal `json:"annual_salary"`
	BonusMode            string          `json:"bonus_mode"`
	BonusFrequency       string          `json:"bonus_frequency"`
	AnnualBonus          decimal.Decimal `json:"annual_bonus"`
	IncomeGrowthRate     decimal.Decimal `json:"income_growth_rate"`
	PayType              string          `json:"pay_type"`
	PayDay               int32           `json:"pay_day"`
	PayCadence           string          `json:"pay_cadence"`
	HourlyRate           decimal.Decimal `json:"hourly_rate"`
	ExpectedHoursPerWeek decimal.Decimal `json:"expected_hours_per_week"`
}

func (q *Queries) UpsertPlannerPerson(ctx context.Context, arg UpsertPlannerPersonParams) (PlannerPerson, error) {
	row := q.db.QueryRow(ctx, upsertPlannerPerson,
		arg.ID,
		arg.UserID,
		arg.Name,
		arg.Birthday,
		arg.RetirementAge,
		arg.AnnualSalary,
		arg.BonusMode,
		arg.BonusFrequency,
		arg.AnnualBonus,
		arg.IncomeGrowthRate,
		arg.PayType,
		arg.PayDay,
		arg.PayCadence,
		arg.HourlyRate,
		arg.ExpectedHoursPerWeek,
	)
	var i PlannerPerson
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Birthday,
		&i.RetirementAge,
		&i.AnnualSalary,
		&i.BonusMode,
		&i.BonusFrequency,
		&i.AnnualBonus,
		&i.IncomeGrowthRate,
		&i.PayType,
		&i.PayDay,
		&i.PayCadence,
		&i.HourlyRate,
		&i.ExpectedHoursPerWeek,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
