// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: planner_people.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
)

const listPlannerPeopleByUserID = `-- name: ListPlannerPeopleByUserID :many
SELECT id, user_id, person_type, name, birthday, retirement_age, annual_salary, bonus_mode, annual_bonus, income_growth_rate, created_at, updated_at, deleted_at
FROM planner_people
WHERE user_id = $1 AND deleted_at IS NULL
ORDER BY created_at ASC
`

func (q *Queries) ListPlannerPeopleByUserID(ctx context.Context, userID uuid.UUID) ([]PlannerPerson, error) {
	rows, err := q.db.Query(ctx, listPlannerPeopleByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []PlannerPerson
	for rows.Next() {
		var i PlannerPerson
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PersonType,
			&i.Name,
			&i.Birthday,
			&i.RetirementAge,
			&i.AnnualSalary,
			&i.BonusMode,
			&i.AnnualBonus,
			&i.IncomeGrowthRate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeletePlannerPeopleByUserID = `-- name: SoftDeletePlannerPeopleByUserID :execrows
UPDATE planner_people
SET deleted_at = now(), updated_at = now()
WHERE user_id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePlannerPeopleByUserID(ctx context.Context, userID uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePlannerPeopleByUserID, userID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const softDeletePlannerPerson = `-- name: SoftDeletePlannerPerson :execrows
UPDATE planner_people
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND deleted_at IS NULL
`

func (q *Queries) SoftDeletePlannerPerson(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeletePlannerPerson, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPlannerPerson = `-- name: UpsertPlannerPerson :one
INSERT INTO planner_people (id, user_id, person_type, name, birthday, retirement_age, annual_salary, bonus_mode, annual_bonus, income_growth_rate)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10)
ON CONFLICT (id) DO UPDATE
SET person_type = EXCLUDED.person_type,
    name = EXCLUDED.name,
    birthday = EXCLUDED.birthday,
    retirement_age = EXCLUDED.retirement_age,
    annual_salary = EXCLUDED.annual_salary,
    bonus_mode = EXCLUDED.bonus_mode,
    annual_bonus = EXCLUDED.annual_bonus,
    income_growth_rate = EXCLUDED.income_growth_rate,
    updated_at = now()
RETURNING id, user_id, person_type, name, birthday, retirement_age, annual_salary, bonus_mode, annual_bonus, income_growth_rate, created_at, updated_at, deleted_at
`

type UpsertPlannerPersonParams struct {
	ID               uuid.UUID       `json:"id"`
	UserID           uuid.UUID       `json:"user_id"`
	PersonType       string          `json:"person_type"`
	Name             string          `json:"name"`
	Birthday         string          `json:"birthday"`
	RetirementAge    int32           `json:"retirement_age"`
	AnnualSalary     decimal.Decimal `json:"annual_salary"`
	BonusMode        string          `json:"bonus_mode"`
	AnnualBonus      decimal.Decimal `json:"annual_bonus"`
	IncomeGrowthRate decimal.Decimal `json:"income_growth_rate"`
}

func (q *Queries) UpsertPlannerPerson(ctx context.Context, arg UpsertPlannerPersonParams) (PlannerPerson, error) {
	row := q.db.QueryRow(ctx, upsertPlannerPerson,
		arg.ID,
		arg.UserID,
		arg.PersonType,
		arg.Name,
		arg.Birthday,
		arg.RetirementAge,
		arg.AnnualSalary,
		arg.BonusMode,
		arg.AnnualBonus,
		arg.IncomeGrowthRate,
	)
	var i PlannerPerson
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PersonType,
		&i.Name,
		&i.Birthday,
		&i.RetirementAge,
		&i.AnnualSalary,
		&i.BonusMode,
		&i.AnnualBonus,
		&i.IncomeGrowthRate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
