// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateTaxBracket(ctx context.Context, arg CreateTaxBracketParams) (TaxBracket, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetAssetByID(ctx context.Context, id uuid.UUID) (Asset, error)
	GetTaxBracketByID(ctx context.Context, id uuid.UUID) (TaxBracket, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByIdentityProviderID(ctx context.Context, identityProviderID string) (GetUserByIdentityProviderIDRow, error)
	ListAssetsByUserID(ctx context.Context, userID uuid.UUID) ([]Asset, error)
	ListTaxBracketsByYearAndFilingStatus(ctx context.Context, arg ListTaxBracketsByYearAndFilingStatusParams) ([]TaxBracket, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	SoftDeleteAsset(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteTaxBracket(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error)
	UpdateTaxBracket(ctx context.Context, arg UpdateTaxBracketParams) (TaxBracket, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
