// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package sqlc

import (
	"context"

	"github.com/google/uuid"
)

type Querier interface {
	CreateAsset(ctx context.Context, arg CreateAssetParams) (Asset, error)
	CreateUser(ctx context.Context, arg CreateUserParams) (CreateUserRow, error)
	GetAssetByID(ctx context.Context, id uuid.UUID) (Asset, error)
	GetUserByID(ctx context.Context, id uuid.UUID) (GetUserByIDRow, error)
	GetUserByIdentityProviderID(ctx context.Context, identityProviderID string) (GetUserByIdentityProviderIDRow, error)
	ListAssetsByUserID(ctx context.Context, userID uuid.UUID) ([]Asset, error)
	ListUsers(ctx context.Context) ([]ListUsersRow, error)
	SoftDeleteAsset(ctx context.Context, id uuid.UUID) (int64, error)
	SoftDeleteUser(ctx context.Context, id uuid.UUID) (int64, error)
	UpdateAsset(ctx context.Context, arg UpdateAssetParams) (Asset, error)
	UpdateUser(ctx context.Context, arg UpdateUserParams) (UpdateUserRow, error)
}

var _ Querier = (*Queries)(nil)
