// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: recurring_expenses.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const createRecurringExpense = `-- name: CreateRecurringExpense :one
INSERT INTO recurring_expenses (
  user_id,
  name,
  amount,
  recurrence_interval,
  payday_day_of_month,
  start_date,
  end_date
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
  id,
  user_id,
  name,
  amount,
  recurrence_interval,
  payday_day_of_month,
  start_date,
  end_date,
  created_at,
  updated_at,
  deleted_at
`

type CreateRecurringExpenseParams struct {
	UserID             uuid.UUID          `json:"user_id"`
	Name               string             `json:"name"`
	Amount             decimal.Decimal    `json:"amount"`
	RecurrenceInterval RecurrenceInterval `json:"recurrence_interval"`
	PaydayDayOfMonth   *int32             `json:"payday_day_of_month"`
	StartDate          pgtype.Date        `json:"start_date"`
	EndDate            pgtype.Date        `json:"end_date"`
}

func (q *Queries) CreateRecurringExpense(ctx context.Context, arg CreateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, createRecurringExpense,
		arg.UserID,
		arg.Name,
		arg.Amount,
		arg.RecurrenceInterval,
		arg.PaydayDayOfMonth,
		arg.StartDate,
		arg.EndDate,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.RecurrenceInterval,
		&i.PaydayDayOfMonth,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getRecurringExpenseByID = `-- name: GetRecurringExpenseByID :one
SELECT
  id,
  user_id,
  name,
  amount,
  recurrence_interval,
  payday_day_of_month,
  start_date,
  end_date,
  created_at,
  updated_at,
  deleted_at
FROM recurring_expenses
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetRecurringExpenseByID(ctx context.Context, id uuid.UUID) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, getRecurringExpenseByID, id)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.RecurrenceInterval,
		&i.PaydayDayOfMonth,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listRecurringExpensesByUserID = `-- name: ListRecurringExpensesByUserID :many
SELECT
  id,
  user_id,
  name,
  amount,
  recurrence_interval,
  payday_day_of_month,
  start_date,
  end_date,
  created_at,
  updated_at,
  deleted_at
FROM recurring_expenses
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListRecurringExpensesByUserID(ctx context.Context, userID uuid.UUID) ([]RecurringExpense, error) {
	rows, err := q.db.Query(ctx, listRecurringExpensesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RecurringExpense
	for rows.Next() {
		var i RecurringExpense
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.Amount,
			&i.RecurrenceInterval,
			&i.PaydayDayOfMonth,
			&i.StartDate,
			&i.EndDate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRecurringExpense = `-- name: SoftDeleteRecurringExpense :execrows
UPDATE recurring_expenses
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRecurringExpense(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteRecurringExpense, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRecurringExpense = `-- name: UpdateRecurringExpense :one
UPDATE recurring_expenses
SET
  name = $2,
  amount = $3,
  recurrence_interval = $4,
  payday_day_of_month = $5,
  start_date = $6,
  end_date = $7,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  user_id,
  name,
  amount,
  recurrence_interval,
  payday_day_of_month,
  start_date,
  end_date,
  created_at,
  updated_at,
  deleted_at
`

type UpdateRecurringExpenseParams struct {
	ID                 uuid.UUID          `json:"id"`
	Name               string             `json:"name"`
	Amount             decimal.Decimal    `json:"amount"`
	RecurrenceInterval RecurrenceInterval `json:"recurrence_interval"`
	PaydayDayOfMonth   *int32             `json:"payday_day_of_month"`
	StartDate          pgtype.Date        `json:"start_date"`
	EndDate            pgtype.Date        `json:"end_date"`
}

func (q *Queries) UpdateRecurringExpense(ctx context.Context, arg UpdateRecurringExpenseParams) (RecurringExpense, error) {
	row := q.db.QueryRow(ctx, updateRecurringExpense,
		arg.ID,
		arg.Name,
		arg.Amount,
		arg.RecurrenceInterval,
		arg.PaydayDayOfMonth,
		arg.StartDate,
		arg.EndDate,
	)
	var i RecurringExpense
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.Amount,
		&i.RecurrenceInterval,
		&i.PaydayDayOfMonth,
		&i.StartDate,
		&i.EndDate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
