// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: retirement.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const createContributionEntry = `-- name: CreateContributionEntry :one
INSERT INTO contribution_entries (
  retirement_account_id,
  tax_year,
  contribution_date,
  amount
) VALUES ($1, $2, $3, $4)
RETURNING
  id,
  retirement_account_id,
  tax_year,
  contribution_date,
  amount,
  created_at,
  updated_at,
  deleted_at
`

type CreateContributionEntryParams struct {
	RetirementAccountID uuid.UUID       `json:"retirement_account_id"`
	TaxYear             int32           `json:"tax_year"`
	ContributionDate    pgtype.Date     `json:"contribution_date"`
	Amount              decimal.Decimal `json:"amount"`
}

func (q *Queries) CreateContributionEntry(ctx context.Context, arg CreateContributionEntryParams) (ContributionEntry, error) {
	row := q.db.QueryRow(ctx, createContributionEntry,
		arg.RetirementAccountID,
		arg.TaxYear,
		arg.ContributionDate,
		arg.Amount,
	)
	var i ContributionEntry
	err := row.Scan(
		&i.ID,
		&i.RetirementAccountID,
		&i.TaxYear,
		&i.ContributionDate,
		&i.Amount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const createRetirementAccount = `-- name: CreateRetirementAccount :one
INSERT INTO retirement_accounts (
  user_id,
  name,
  account_type,
  owner,
  tax_treatment,
  current_balance,
  annual_contribution_limit
) VALUES ($1, $2, $3, $4, $5, $6, $7)
RETURNING
  id,
  user_id,
  name,
  account_type,
  owner,
  tax_treatment,
  current_balance,
  annual_contribution_limit,
  created_at,
  updated_at,
  deleted_at
`

type CreateRetirementAccountParams struct {
	UserID                  uuid.UUID              `json:"user_id"`
	Name                    string                 `json:"name"`
	AccountType             RetirementAccountType  `json:"account_type"`
	Owner                   RetirementAccountOwner `json:"owner"`
	TaxTreatment            RetirementTaxTreatment `json:"tax_treatment"`
	CurrentBalance          decimal.Decimal        `json:"current_balance"`
	AnnualContributionLimit decimal.Decimal        `json:"annual_contribution_limit"`
}

func (q *Queries) CreateRetirementAccount(ctx context.Context, arg CreateRetirementAccountParams) (RetirementAccount, error) {
	row := q.db.QueryRow(ctx, createRetirementAccount,
		arg.UserID,
		arg.Name,
		arg.AccountType,
		arg.Owner,
		arg.TaxTreatment,
		arg.CurrentBalance,
		arg.AnnualContributionLimit,
	)
	var i RetirementAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountType,
		&i.Owner,
		&i.TaxTreatment,
		&i.CurrentBalance,
		&i.AnnualContributionLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getContributionLimitByAccountTypeAndTaxYear = `-- name: GetContributionLimitByAccountTypeAndTaxYear :one
SELECT
  id,
  account_type,
  tax_year,
  annual_limit,
  catch_up_age,
  catch_up_amount,
  created_at,
  updated_at,
  deleted_at
FROM contribution_limits
WHERE account_type = $1
  AND tax_year = $2
  AND deleted_at IS NULL
LIMIT 1
`

type GetContributionLimitByAccountTypeAndTaxYearParams struct {
	AccountType RetirementAccountType `json:"account_type"`
	TaxYear     int32                 `json:"tax_year"`
}

func (q *Queries) GetContributionLimitByAccountTypeAndTaxYear(ctx context.Context, arg GetContributionLimitByAccountTypeAndTaxYearParams) (ContributionLimit, error) {
	row := q.db.QueryRow(ctx, getContributionLimitByAccountTypeAndTaxYear, arg.AccountType, arg.TaxYear)
	var i ContributionLimit
	err := row.Scan(
		&i.ID,
		&i.AccountType,
		&i.TaxYear,
		&i.AnnualLimit,
		&i.CatchUpAge,
		&i.CatchUpAmount,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getContributionProgress = `-- name: GetContributionProgress :one
SELECT
  ra.id AS retirement_account_id,
  cl.tax_year,
  cl.annual_limit,
  COALESCE(SUM(ce.amount), 0)::numeric(12,2) AS contributed_ytd
FROM retirement_accounts ra
JOIN contribution_limits cl
  ON cl.account_type = ra.account_type
  AND cl.tax_year = $2
  AND cl.deleted_at IS NULL
LEFT JOIN contribution_entries ce
  ON ce.retirement_account_id = ra.id
  AND ce.tax_year = $2
  AND ce.deleted_at IS NULL
WHERE ra.id = $1
  AND ra.deleted_at IS NULL
GROUP BY ra.id, cl.tax_year, cl.annual_limit
LIMIT 1
`

type GetContributionProgressParams struct {
	ID      uuid.UUID `json:"id"`
	TaxYear int32     `json:"tax_year"`
}

type GetContributionProgressRow struct {
	RetirementAccountID uuid.UUID       `json:"retirement_account_id"`
	TaxYear             int32           `json:"tax_year"`
	AnnualLimit         decimal.Decimal `json:"annual_limit"`
	ContributedYtd      decimal.Decimal `json:"contributed_ytd"`
}

func (q *Queries) GetContributionProgress(ctx context.Context, arg GetContributionProgressParams) (GetContributionProgressRow, error) {
	row := q.db.QueryRow(ctx, getContributionProgress, arg.ID, arg.TaxYear)
	var i GetContributionProgressRow
	err := row.Scan(
		&i.RetirementAccountID,
		&i.TaxYear,
		&i.AnnualLimit,
		&i.ContributedYtd,
	)
	return i, err
}

const getRetirementAccountByID = `-- name: GetRetirementAccountByID :one
SELECT
  id,
  user_id,
  name,
  account_type,
  owner,
  tax_treatment,
  current_balance,
  annual_contribution_limit,
  created_at,
  updated_at,
  deleted_at
FROM retirement_accounts
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetRetirementAccountByID(ctx context.Context, id uuid.UUID) (RetirementAccount, error) {
	row := q.db.QueryRow(ctx, getRetirementAccountByID, id)
	var i RetirementAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountType,
		&i.Owner,
		&i.TaxTreatment,
		&i.CurrentBalance,
		&i.AnnualContributionLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listRetirementAccountsByUserID = `-- name: ListRetirementAccountsByUserID :many
SELECT
  id,
  user_id,
  name,
  account_type,
  owner,
  tax_treatment,
  current_balance,
  annual_contribution_limit,
  created_at,
  updated_at,
  deleted_at
FROM retirement_accounts
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListRetirementAccountsByUserID(ctx context.Context, userID uuid.UUID) ([]RetirementAccount, error) {
	rows, err := q.db.Query(ctx, listRetirementAccountsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []RetirementAccount
	for rows.Next() {
		var i RetirementAccount
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.AccountType,
			&i.Owner,
			&i.TaxTreatment,
			&i.CurrentBalance,
			&i.AnnualContributionLimit,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteRetirementAccount = `-- name: SoftDeleteRetirementAccount :execrows
UPDATE retirement_accounts
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteRetirementAccount(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteRetirementAccount, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateRetirementAccount = `-- name: UpdateRetirementAccount :one
UPDATE retirement_accounts
SET
  name = $2,
  account_type = $3,
  owner = $4,
  tax_treatment = $5,
  current_balance = $6,
  annual_contribution_limit = $7,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  user_id,
  name,
  account_type,
  owner,
  tax_treatment,
  current_balance,
  annual_contribution_limit,
  created_at,
  updated_at,
  deleted_at
`

type UpdateRetirementAccountParams struct {
	ID                      uuid.UUID              `json:"id"`
	Name                    string                 `json:"name"`
	AccountType             RetirementAccountType  `json:"account_type"`
	Owner                   RetirementAccountOwner `json:"owner"`
	TaxTreatment            RetirementTaxTreatment `json:"tax_treatment"`
	CurrentBalance          decimal.Decimal        `json:"current_balance"`
	AnnualContributionLimit decimal.Decimal        `json:"annual_contribution_limit"`
}

func (q *Queries) UpdateRetirementAccount(ctx context.Context, arg UpdateRetirementAccountParams) (RetirementAccount, error) {
	row := q.db.QueryRow(ctx, updateRetirementAccount,
		arg.ID,
		arg.Name,
		arg.AccountType,
		arg.Owner,
		arg.TaxTreatment,
		arg.CurrentBalance,
		arg.AnnualContributionLimit,
	)
	var i RetirementAccount
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.AccountType,
		&i.Owner,
		&i.TaxTreatment,
		&i.CurrentBalance,
		&i.AnnualContributionLimit,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
