// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: scenarios.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const createScenarioProfile = `-- name: CreateScenarioProfile :one
INSERT INTO scenario_profiles (
  user_id,
  name,
  current_age,
  retirement_age,
  annual_spend,
  safe_withdrawal_rate,
  inflation_rate,
  return_rate,
  current_portfolio
) VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
RETURNING
  id,
  user_id,
  name,
  current_age,
  retirement_age,
  annual_spend,
  safe_withdrawal_rate,
  inflation_rate,
  return_rate,
  current_portfolio,
  created_at,
  updated_at,
  deleted_at
`

type CreateScenarioProfileParams struct {
	UserID             uuid.UUID       `json:"user_id"`
	Name               string          `json:"name"`
	CurrentAge         int32           `json:"current_age"`
	RetirementAge      int32           `json:"retirement_age"`
	AnnualSpend        decimal.Decimal `json:"annual_spend"`
	SafeWithdrawalRate decimal.Decimal `json:"safe_withdrawal_rate"`
	InflationRate      decimal.Decimal `json:"inflation_rate"`
	ReturnRate         decimal.Decimal `json:"return_rate"`
	CurrentPortfolio   decimal.Decimal `json:"current_portfolio"`
}

func (q *Queries) CreateScenarioProfile(ctx context.Context, arg CreateScenarioProfileParams) (ScenarioProfile, error) {
	row := q.db.QueryRow(ctx, createScenarioProfile,
		arg.UserID,
		arg.Name,
		arg.CurrentAge,
		arg.RetirementAge,
		arg.AnnualSpend,
		arg.SafeWithdrawalRate,
		arg.InflationRate,
		arg.ReturnRate,
		arg.CurrentPortfolio,
	)
	var i ScenarioProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CurrentAge,
		&i.RetirementAge,
		&i.AnnualSpend,
		&i.SafeWithdrawalRate,
		&i.InflationRate,
		&i.ReturnRate,
		&i.CurrentPortfolio,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getScenarioProfileByID = `-- name: GetScenarioProfileByID :one
SELECT
  id,
  user_id,
  name,
  current_age,
  retirement_age,
  annual_spend,
  safe_withdrawal_rate,
  inflation_rate,
  return_rate,
  current_portfolio,
  created_at,
  updated_at,
  deleted_at
FROM scenario_profiles
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetScenarioProfileByID(ctx context.Context, id uuid.UUID) (ScenarioProfile, error) {
	row := q.db.QueryRow(ctx, getScenarioProfileByID, id)
	var i ScenarioProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CurrentAge,
		&i.RetirementAge,
		&i.AnnualSpend,
		&i.SafeWithdrawalRate,
		&i.InflationRate,
		&i.ReturnRate,
		&i.CurrentPortfolio,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getScenarioResultCacheByScenarioProfileID = `-- name: GetScenarioResultCacheByScenarioProfileID :one
SELECT
  id,
  scenario_profile_id,
  portfolio_at_retirement,
  required_portfolio,
  projected_depletion_age,
  is_sustainable,
  created_at,
  updated_at,
  deleted_at
FROM scenario_results_cache
WHERE scenario_profile_id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetScenarioResultCacheByScenarioProfileID(ctx context.Context, scenarioProfileID uuid.UUID) (ScenarioResultsCache, error) {
	row := q.db.QueryRow(ctx, getScenarioResultCacheByScenarioProfileID, scenarioProfileID)
	var i ScenarioResultsCache
	err := row.Scan(
		&i.ID,
		&i.ScenarioProfileID,
		&i.PortfolioAtRetirement,
		&i.RequiredPortfolio,
		&i.ProjectedDepletionAge,
		&i.IsSustainable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listScenarioComparisonsByUserID = `-- name: ListScenarioComparisonsByUserID :many
SELECT
  sp.id AS scenario_profile_id,
  sp.user_id,
  sp.name,
  sp.current_age,
  sp.retirement_age,
  sp.annual_spend,
  sp.safe_withdrawal_rate,
  sp.inflation_rate,
  sp.return_rate,
  sp.current_portfolio,
  sp.created_at AS profile_created_at,
  sp.updated_at AS profile_updated_at,
  src.portfolio_at_retirement,
  src.required_portfolio,
  src.projected_depletion_age,
  src.is_sustainable,
  src.created_at AS result_created_at,
  src.updated_at AS result_updated_at
FROM scenario_profiles sp
JOIN scenario_results_cache src
  ON src.scenario_profile_id = sp.id
  AND src.deleted_at IS NULL
WHERE sp.user_id = $1
  AND sp.deleted_at IS NULL
ORDER BY sp.created_at DESC
`

type ListScenarioComparisonsByUserIDRow struct {
	ScenarioProfileID     uuid.UUID          `json:"scenario_profile_id"`
	UserID                uuid.UUID          `json:"user_id"`
	Name                  string             `json:"name"`
	CurrentAge            int32              `json:"current_age"`
	RetirementAge         int32              `json:"retirement_age"`
	AnnualSpend           decimal.Decimal    `json:"annual_spend"`
	SafeWithdrawalRate    decimal.Decimal    `json:"safe_withdrawal_rate"`
	InflationRate         decimal.Decimal    `json:"inflation_rate"`
	ReturnRate            decimal.Decimal    `json:"return_rate"`
	CurrentPortfolio      decimal.Decimal    `json:"current_portfolio"`
	ProfileCreatedAt      pgtype.Timestamptz `json:"profile_created_at"`
	ProfileUpdatedAt      pgtype.Timestamptz `json:"profile_updated_at"`
	PortfolioAtRetirement decimal.Decimal    `json:"portfolio_at_retirement"`
	RequiredPortfolio     decimal.Decimal    `json:"required_portfolio"`
	ProjectedDepletionAge *int32             `json:"projected_depletion_age"`
	IsSustainable         bool               `json:"is_sustainable"`
	ResultCreatedAt       pgtype.Timestamptz `json:"result_created_at"`
	ResultUpdatedAt       pgtype.Timestamptz `json:"result_updated_at"`
}

func (q *Queries) ListScenarioComparisonsByUserID(ctx context.Context, userID uuid.UUID) ([]ListScenarioComparisonsByUserIDRow, error) {
	rows, err := q.db.Query(ctx, listScenarioComparisonsByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListScenarioComparisonsByUserIDRow
	for rows.Next() {
		var i ListScenarioComparisonsByUserIDRow
		if err := rows.Scan(
			&i.ScenarioProfileID,
			&i.UserID,
			&i.Name,
			&i.CurrentAge,
			&i.RetirementAge,
			&i.AnnualSpend,
			&i.SafeWithdrawalRate,
			&i.InflationRate,
			&i.ReturnRate,
			&i.CurrentPortfolio,
			&i.ProfileCreatedAt,
			&i.ProfileUpdatedAt,
			&i.PortfolioAtRetirement,
			&i.RequiredPortfolio,
			&i.ProjectedDepletionAge,
			&i.IsSustainable,
			&i.ResultCreatedAt,
			&i.ResultUpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listScenarioProfilesByUserID = `-- name: ListScenarioProfilesByUserID :many
SELECT
  id,
  user_id,
  name,
  current_age,
  retirement_age,
  annual_spend,
  safe_withdrawal_rate,
  inflation_rate,
  return_rate,
  current_portfolio,
  created_at,
  updated_at,
  deleted_at
FROM scenario_profiles
WHERE user_id = $1
  AND deleted_at IS NULL
ORDER BY created_at DESC
`

func (q *Queries) ListScenarioProfilesByUserID(ctx context.Context, userID uuid.UUID) ([]ScenarioProfile, error) {
	rows, err := q.db.Query(ctx, listScenarioProfilesByUserID, userID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ScenarioProfile
	for rows.Next() {
		var i ScenarioProfile
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.Name,
			&i.CurrentAge,
			&i.RetirementAge,
			&i.AnnualSpend,
			&i.SafeWithdrawalRate,
			&i.InflationRate,
			&i.ReturnRate,
			&i.CurrentPortfolio,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteScenarioProfile = `-- name: SoftDeleteScenarioProfile :execrows
UPDATE scenario_profiles
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteScenarioProfile(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteScenarioProfile, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateScenarioProfile = `-- name: UpdateScenarioProfile :one
UPDATE scenario_profiles
SET
  name = $2,
  current_age = $3,
  retirement_age = $4,
  annual_spend = $5,
  safe_withdrawal_rate = $6,
  inflation_rate = $7,
  return_rate = $8,
  current_portfolio = $9,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  user_id,
  name,
  current_age,
  retirement_age,
  annual_spend,
  safe_withdrawal_rate,
  inflation_rate,
  return_rate,
  current_portfolio,
  created_at,
  updated_at,
  deleted_at
`

type UpdateScenarioProfileParams struct {
	ID                 uuid.UUID       `json:"id"`
	Name               string          `json:"name"`
	CurrentAge         int32           `json:"current_age"`
	RetirementAge      int32           `json:"retirement_age"`
	AnnualSpend        decimal.Decimal `json:"annual_spend"`
	SafeWithdrawalRate decimal.Decimal `json:"safe_withdrawal_rate"`
	InflationRate      decimal.Decimal `json:"inflation_rate"`
	ReturnRate         decimal.Decimal `json:"return_rate"`
	CurrentPortfolio   decimal.Decimal `json:"current_portfolio"`
}

func (q *Queries) UpdateScenarioProfile(ctx context.Context, arg UpdateScenarioProfileParams) (ScenarioProfile, error) {
	row := q.db.QueryRow(ctx, updateScenarioProfile,
		arg.ID,
		arg.Name,
		arg.CurrentAge,
		arg.RetirementAge,
		arg.AnnualSpend,
		arg.SafeWithdrawalRate,
		arg.InflationRate,
		arg.ReturnRate,
		arg.CurrentPortfolio,
	)
	var i ScenarioProfile
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.Name,
		&i.CurrentAge,
		&i.RetirementAge,
		&i.AnnualSpend,
		&i.SafeWithdrawalRate,
		&i.InflationRate,
		&i.ReturnRate,
		&i.CurrentPortfolio,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const upsertScenarioResultCache = `-- name: UpsertScenarioResultCache :one
INSERT INTO scenario_results_cache (
  scenario_profile_id,
  portfolio_at_retirement,
  required_portfolio,
  projected_depletion_age,
  is_sustainable
) VALUES ($1, $2, $3, $4, $5)
ON CONFLICT (scenario_profile_id) DO UPDATE SET
  portfolio_at_retirement = EXCLUDED.portfolio_at_retirement,
  required_portfolio = EXCLUDED.required_portfolio,
  projected_depletion_age = EXCLUDED.projected_depletion_age,
  is_sustainable = EXCLUDED.is_sustainable,
  updated_at = now()
RETURNING
  id,
  scenario_profile_id,
  portfolio_at_retirement,
  required_portfolio,
  projected_depletion_age,
  is_sustainable,
  created_at,
  updated_at,
  deleted_at
`

type UpsertScenarioResultCacheParams struct {
	ScenarioProfileID     uuid.UUID       `json:"scenario_profile_id"`
	PortfolioAtRetirement decimal.Decimal `json:"portfolio_at_retirement"`
	RequiredPortfolio     decimal.Decimal `json:"required_portfolio"`
	ProjectedDepletionAge *int32          `json:"projected_depletion_age"`
	IsSustainable         bool            `json:"is_sustainable"`
}

func (q *Queries) UpsertScenarioResultCache(ctx context.Context, arg UpsertScenarioResultCacheParams) (ScenarioResultsCache, error) {
	row := q.db.QueryRow(ctx, upsertScenarioResultCache,
		arg.ScenarioProfileID,
		arg.PortfolioAtRetirement,
		arg.RequiredPortfolio,
		arg.ProjectedDepletionAge,
		arg.IsSustainable,
	)
	var i ScenarioResultsCache
	err := row.Scan(
		&i.ID,
		&i.ScenarioProfileID,
		&i.PortfolioAtRetirement,
		&i.RequiredPortfolio,
		&i.ProjectedDepletionAge,
		&i.IsSustainable,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
