// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tax_brackets.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const createTaxBracket = `-- name: CreateTaxBracket :one
INSERT INTO tax_brackets (
  year,
  filing_status,
  minimum_amount,
  maximum_amount,
  rate
)
VALUES ($1, $2, $3, $4, $5)
RETURNING
  id,
  year,
  filing_status,
  minimum_amount,
  maximum_amount,
  rate,
  created_at,
  updated_at,
  deleted_at
`

type CreateTaxBracketParams struct {
	Year          int32           `json:"year"`
	FilingStatus  FilingStatus    `json:"filing_status"`
	MinimumAmount decimal.Decimal `json:"minimum_amount"`
	MaximumAmount pgtype.Numeric  `json:"maximum_amount"`
	Rate          decimal.Decimal `json:"rate"`
}

func (q *Queries) CreateTaxBracket(ctx context.Context, arg CreateTaxBracketParams) (TaxBracket, error) {
	row := q.db.QueryRow(ctx, createTaxBracket,
		arg.Year,
		arg.FilingStatus,
		arg.MinimumAmount,
		arg.MaximumAmount,
		arg.Rate,
	)
	var i TaxBracket
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.FilingStatus,
		&i.MinimumAmount,
		&i.MaximumAmount,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getTaxBracketByID = `-- name: GetTaxBracketByID :one
SELECT
  id,
  year,
  filing_status,
  minimum_amount,
  maximum_amount,
  rate,
  created_at,
  updated_at,
  deleted_at
FROM tax_brackets
WHERE id = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetTaxBracketByID(ctx context.Context, id uuid.UUID) (TaxBracket, error) {
	row := q.db.QueryRow(ctx, getTaxBracketByID, id)
	var i TaxBracket
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.FilingStatus,
		&i.MinimumAmount,
		&i.MaximumAmount,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const listTaxBracketsByYearAndFilingStatus = `-- name: ListTaxBracketsByYearAndFilingStatus :many
SELECT
  id,
  year,
  filing_status,
  minimum_amount,
  maximum_amount,
  rate,
  created_at,
  updated_at,
  deleted_at
FROM tax_brackets
WHERE year = $1
  AND filing_status = $2
  AND deleted_at IS NULL
ORDER BY minimum_amount ASC
`

type ListTaxBracketsByYearAndFilingStatusParams struct {
	Year         int32        `json:"year"`
	FilingStatus FilingStatus `json:"filing_status"`
}

func (q *Queries) ListTaxBracketsByYearAndFilingStatus(ctx context.Context, arg ListTaxBracketsByYearAndFilingStatusParams) ([]TaxBracket, error) {
	rows, err := q.db.Query(ctx, listTaxBracketsByYearAndFilingStatus, arg.Year, arg.FilingStatus)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TaxBracket
	for rows.Next() {
		var i TaxBracket
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.FilingStatus,
			&i.MinimumAmount,
			&i.MaximumAmount,
			&i.Rate,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const softDeleteTaxBracket = `-- name: SoftDeleteTaxBracket :execrows
UPDATE tax_brackets
SET deleted_at = now(),
    updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
`

func (q *Queries) SoftDeleteTaxBracket(ctx context.Context, id uuid.UUID) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTaxBracket, id)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const updateTaxBracket = `-- name: UpdateTaxBracket :one
UPDATE tax_brackets
SET
  year = $2,
  filing_status = $3,
  minimum_amount = $4,
  maximum_amount = $5,
  rate = $6,
  updated_at = now()
WHERE id = $1
  AND deleted_at IS NULL
RETURNING
  id,
  year,
  filing_status,
  minimum_amount,
  maximum_amount,
  rate,
  created_at,
  updated_at,
  deleted_at
`

type UpdateTaxBracketParams struct {
	ID            uuid.UUID       `json:"id"`
	Year          int32           `json:"year"`
	FilingStatus  FilingStatus    `json:"filing_status"`
	MinimumAmount decimal.Decimal `json:"minimum_amount"`
	MaximumAmount pgtype.Numeric  `json:"maximum_amount"`
	Rate          decimal.Decimal `json:"rate"`
}

func (q *Queries) UpdateTaxBracket(ctx context.Context, arg UpdateTaxBracketParams) (TaxBracket, error) {
	row := q.db.QueryRow(ctx, updateTaxBracket,
		arg.ID,
		arg.Year,
		arg.FilingStatus,
		arg.MinimumAmount,
		arg.MaximumAmount,
		arg.Rate,
	)
	var i TaxBracket
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.FilingStatus,
		&i.MinimumAmount,
		&i.MaximumAmount,
		&i.Rate,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}
