// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: tax_year.sql

package sqlc

import (
	"context"
)

const getFicaParametersByYear = `-- name: GetFicaParametersByYear :one
SELECT
  id,
  year,
  ss_wage_base,
  created_at,
  updated_at,
  deleted_at
FROM fica_parameters
WHERE year = $1
  AND deleted_at IS NULL
LIMIT 1
`

func (q *Queries) GetFicaParametersByYear(ctx context.Context, year int32) (FicaParameter, error) {
	row := q.db.QueryRow(ctx, getFicaParametersByYear, year)
	var i FicaParameter
	err := row.Scan(
		&i.ID,
		&i.Year,
		&i.SsWageBase,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
	)
	return i, err
}

const getLatestTaxYear = `-- name: GetLatestTaxYear :one
SELECT MAX(year)::int AS year
FROM tax_brackets
WHERE deleted_at IS NULL
`

func (q *Queries) GetLatestTaxYear(ctx context.Context) (int32, error) {
	row := q.db.QueryRow(ctx, getLatestTaxYear)
	var year int32
	err := row.Scan(&year)
	return year, err
}

const listStandardDeductionsByYear = `-- name: ListStandardDeductionsByYear :many
SELECT
  id,
  year,
  filing_status,
  amount,
  created_at,
  updated_at,
  deleted_at
FROM standard_deductions
WHERE year = $1
  AND deleted_at IS NULL
`

func (q *Queries) ListStandardDeductionsByYear(ctx context.Context, year int32) ([]StandardDeduction, error) {
	rows, err := q.db.Query(ctx, listStandardDeductionsByYear, year)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []StandardDeduction
	for rows.Next() {
		var i StandardDeduction
		if err := rows.Scan(
			&i.ID,
			&i.Year,
			&i.FilingStatus,
			&i.Amount,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
