// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: transactions.sql

package sqlc

import (
	"context"

	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

const assignTransactionCategory = `-- name: AssignTransactionCategory :one
UPDATE transactions
SET expense_category_id = $1,
    updated_at = now()
WHERE id = $2 AND user_id = $3 AND deleted_at IS NULL
RETURNING id, user_id, plaid_account_id, plaid_transaction_id, date, amount, name, expense_category_id, pending, created_at, updated_at, deleted_at, expense_id
`

type AssignTransactionCategoryParams struct {
	ExpenseCategoryID pgtype.UUID `json:"expense_category_id"`
	ID                uuid.UUID   `json:"id"`
	UserID            uuid.UUID   `json:"user_id"`
}

func (q *Queries) AssignTransactionCategory(ctx context.Context, arg AssignTransactionCategoryParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, assignTransactionCategory, arg.ExpenseCategoryID, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaidAccountID,
		&i.PlaidTransactionID,
		&i.Date,
		&i.Amount,
		&i.Name,
		&i.ExpenseCategoryID,
		&i.Pending,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpenseID,
	)
	return i, err
}

const createTransaction = `-- name: CreateTransaction :one
INSERT INTO transactions (
    user_id,
    plaid_account_id,
    plaid_transaction_id,
    date,
    amount,
    name,
    expense_category_id,
    pending
) VALUES (
    $1, $2, $3, $4, $5, $6, $7, $8
) RETURNING id, user_id, plaid_account_id, plaid_transaction_id, date, amount, name, expense_category_id, pending, created_at, updated_at, deleted_at, expense_id
`

type CreateTransactionParams struct {
	UserID             uuid.UUID       `json:"user_id"`
	PlaidAccountID     pgtype.UUID     `json:"plaid_account_id"`
	PlaidTransactionID *string         `json:"plaid_transaction_id"`
	Date               pgtype.Date     `json:"date"`
	Amount             decimal.Decimal `json:"amount"`
	Name               string          `json:"name"`
	ExpenseCategoryID  pgtype.UUID     `json:"expense_category_id"`
	Pending            bool            `json:"pending"`
}

func (q *Queries) CreateTransaction(ctx context.Context, arg CreateTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, createTransaction,
		arg.UserID,
		arg.PlaidAccountID,
		arg.PlaidTransactionID,
		arg.Date,
		arg.Amount,
		arg.Name,
		arg.ExpenseCategoryID,
		arg.Pending,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaidAccountID,
		&i.PlaidTransactionID,
		&i.Date,
		&i.Amount,
		&i.Name,
		&i.ExpenseCategoryID,
		&i.Pending,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpenseID,
	)
	return i, err
}

const getTransaction = `-- name: GetTransaction :one
SELECT id, user_id, plaid_account_id, plaid_transaction_id, date, amount, name, expense_category_id, pending, created_at, updated_at, deleted_at, expense_id FROM transactions
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type GetTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) GetTransaction(ctx context.Context, arg GetTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, getTransaction, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaidAccountID,
		&i.PlaidTransactionID,
		&i.Date,
		&i.Amount,
		&i.Name,
		&i.ExpenseCategoryID,
		&i.Pending,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpenseID,
	)
	return i, err
}

const listPlaidAccountIDsByConnectionID = `-- name: ListPlaidAccountIDsByConnectionID :many
SELECT id FROM plaid_accounts
WHERE plaid_connection_id = $1 AND deleted_at IS NULL
`

func (q *Queries) ListPlaidAccountIDsByConnectionID(ctx context.Context, plaidConnectionID uuid.UUID) ([]uuid.UUID, error) {
	rows, err := q.db.Query(ctx, listPlaidAccountIDsByConnectionID, plaidConnectionID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []uuid.UUID
	for rows.Next() {
		var id uuid.UUID
		if err := rows.Scan(&id); err != nil {
			return nil, err
		}
		items = append(items, id)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTransactionsByUserID = `-- name: ListTransactionsByUserID :many
SELECT id, user_id, plaid_account_id, plaid_transaction_id, date, amount, name, expense_category_id, pending, created_at, updated_at, deleted_at, expense_id FROM transactions
WHERE user_id = $1
  AND deleted_at IS NULL
  AND date >= $2
  AND date <= $3
ORDER BY date DESC
`

type ListTransactionsByUserIDParams struct {
	UserID   uuid.UUID   `json:"user_id"`
	FromDate pgtype.Date `json:"from_date"`
	ToDate   pgtype.Date `json:"to_date"`
}

func (q *Queries) ListTransactionsByUserID(ctx context.Context, arg ListTransactionsByUserIDParams) ([]Transaction, error) {
	rows, err := q.db.Query(ctx, listTransactionsByUserID, arg.UserID, arg.FromDate, arg.ToDate)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Transaction
	for rows.Next() {
		var i Transaction
		if err := rows.Scan(
			&i.ID,
			&i.UserID,
			&i.PlaidAccountID,
			&i.PlaidTransactionID,
			&i.Date,
			&i.Amount,
			&i.Name,
			&i.ExpenseCategoryID,
			&i.Pending,
			&i.CreatedAt,
			&i.UpdatedAt,
			&i.DeletedAt,
			&i.ExpenseID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const setTransactionExpense = `-- name: SetTransactionExpense :one
UPDATE transactions
SET expense_id = $1,
    updated_at = now()
WHERE id = $2 AND user_id = $3 AND deleted_at IS NULL
RETURNING id, user_id, plaid_account_id, plaid_transaction_id, date, amount, name, expense_category_id, pending, created_at, updated_at, deleted_at, expense_id
`

type SetTransactionExpenseParams struct {
	ExpenseID pgtype.UUID `json:"expense_id"`
	ID        uuid.UUID   `json:"id"`
	UserID    uuid.UUID   `json:"user_id"`
}

func (q *Queries) SetTransactionExpense(ctx context.Context, arg SetTransactionExpenseParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, setTransactionExpense, arg.ExpenseID, arg.ID, arg.UserID)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaidAccountID,
		&i.PlaidTransactionID,
		&i.Date,
		&i.Amount,
		&i.Name,
		&i.ExpenseCategoryID,
		&i.Pending,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpenseID,
	)
	return i, err
}

const softDeleteTransaction = `-- name: SoftDeleteTransaction :execrows
UPDATE transactions
SET deleted_at = now(), updated_at = now()
WHERE id = $1 AND user_id = $2 AND deleted_at IS NULL
`

type SoftDeleteTransactionParams struct {
	ID     uuid.UUID `json:"id"`
	UserID uuid.UUID `json:"user_id"`
}

func (q *Queries) SoftDeleteTransaction(ctx context.Context, arg SoftDeleteTransactionParams) (int64, error) {
	result, err := q.db.Exec(ctx, softDeleteTransaction, arg.ID, arg.UserID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertPlaidTransaction = `-- name: UpsertPlaidTransaction :one
INSERT INTO transactions (
    user_id,
    plaid_account_id,
    plaid_transaction_id,
    date,
    amount,
    name,
    pending
) VALUES (
    $1, $2, $3, $4, $5, $6, $7
)
ON CONFLICT (plaid_transaction_id) WHERE deleted_at IS NULL DO UPDATE SET
    plaid_account_id = EXCLUDED.plaid_account_id,
    date = EXCLUDED.date,
    amount = EXCLUDED.amount,
    name = EXCLUDED.name,
    pending = EXCLUDED.pending,
    updated_at = now()
RETURNING id, user_id, plaid_account_id, plaid_transaction_id, date, amount, name, expense_category_id, pending, created_at, updated_at, deleted_at, expense_id
`

type UpsertPlaidTransactionParams struct {
	UserID             uuid.UUID       `json:"user_id"`
	PlaidAccountID     pgtype.UUID     `json:"plaid_account_id"`
	PlaidTransactionID *string         `json:"plaid_transaction_id"`
	Date               pgtype.Date     `json:"date"`
	Amount             decimal.Decimal `json:"amount"`
	Name               string          `json:"name"`
	Pending            bool            `json:"pending"`
}

func (q *Queries) UpsertPlaidTransaction(ctx context.Context, arg UpsertPlaidTransactionParams) (Transaction, error) {
	row := q.db.QueryRow(ctx, upsertPlaidTransaction,
		arg.UserID,
		arg.PlaidAccountID,
		arg.PlaidTransactionID,
		arg.Date,
		arg.Amount,
		arg.Name,
		arg.Pending,
	)
	var i Transaction
	err := row.Scan(
		&i.ID,
		&i.UserID,
		&i.PlaidAccountID,
		&i.PlaidTransactionID,
		&i.Date,
		&i.Amount,
		&i.Name,
		&i.ExpenseCategoryID,
		&i.Pending,
		&i.CreatedAt,
		&i.UpdatedAt,
		&i.DeletedAt,
		&i.ExpenseID,
	)
	return i, err
}
