services:
  webApp:
    image: breeze-web
    build: ./Breeze.Web
    ports:
      - 5173:5173
    volumes:
      - ./Breeze.Web:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
  webApi:
    image: breeze-api
    build: ./Breeze.Api
    ports:
      - 5001:80
    volumes:
      - ./Breeze.Api:/app/src
      - ./Breeze.Data:/app/src
      - ./Breeze.Domain:/app/src
    environment:
      - CHOKIDAR_USEPOLLING=true
