type Query {
  health: Health!
  user(id: ID!): User
  me: User
  users: [User!]!
  asset(id: ID!): Asset
  assets(userId: ID!): [Asset!]!
  taxBracket(id: ID!): TaxBracket
  taxBrackets(year: Int!, filingStatus: FilingStatus!): [TaxBracket!]!
}

type Mutation {
  createUser(input: CreateUserInput!): User!
  updateUser(input: UpdateUserInput!): User!
  deleteUser(id: ID!): Boolean!
  createAsset(input: CreateAssetInput!): Asset!
  updateAsset(input: UpdateAssetInput!): Asset!
  deleteAsset(id: ID!): Boolean!
  createTaxBracket(input: CreateTaxBracketInput!): TaxBracket!
  updateTaxBracket(input: UpdateTaxBracketInput!): TaxBracket!
  deleteTaxBracket(id: ID!): Boolean!
}

type Health {
  status: String!
  timestamp: String!
}

enum ReturnType {
  REAL
  NOMINAL
}

enum DeductionType {
  STANDARD
  ITEMIZED
}

enum FilingStatus {
  SINGLE
  MFJ
  MFS
  HOH
}

enum PayoffStrategy {
  AVALANCHE
  SNOWBALL
}

enum AssetType {
  CASH
  INVESTMENT
  RETIREMENT
  REAL_ESTATE
  VEHICLE
  OTHER
}

type User {
  id: ID!
  identityProviderId: String!
  email: String!
  returnType: ReturnType!
  safeWithdrawalRate: String!
  currencyType: String!
  inflationRate: String!
  deductionType: DeductionType!
  deductionAmount: String
  maxTaxBracketId: ID
  filingStatus: FilingStatus!
  payoffStrategy: PayoffStrategy!
  createdAt: String!
  updatedAt: String!
}

input CreateUserInput {
  identityProviderId: String!
  email: String!
  returnType: ReturnType!
  safeWithdrawalRate: String!
  currencyType: String!
  inflationRate: String!
  deductionType: DeductionType!
  deductionAmount: String
  maxTaxBracketId: ID
  filingStatus: FilingStatus!
  payoffStrategy: PayoffStrategy!
}

input UpdateUserInput {
  id: ID!
  identityProviderId: String!
  email: String!
  returnType: ReturnType!
  safeWithdrawalRate: String!
  currencyType: String!
  inflationRate: String!
  deductionType: DeductionType!
  deductionAmount: String
  maxTaxBracketId: ID
  filingStatus: FilingStatus!
  payoffStrategy: PayoffStrategy!
}

type Asset {
  id: ID!
  userId: ID!
  name: String!
  assetType: AssetType!
  currentValue: String!
  lastValueUpdatedAt: String!
  createdAt: String!
  updatedAt: String!
}

type TaxBracket {
  id: ID!
  year: Int!
  filingStatus: FilingStatus!
  minimumAmount: String!
  maximumAmount: String
  rate: String!
  createdAt: String!
  updatedAt: String!
}

input CreateTaxBracketInput {
  year: Int!
  filingStatus: FilingStatus!
  minimumAmount: String!
  maximumAmount: String
  rate: String!
}

input UpdateTaxBracketInput {
  id: ID!
  year: Int!
  filingStatus: FilingStatus!
  minimumAmount: String!
  maximumAmount: String
  rate: String!
}

input CreateAssetInput {
  userId: ID!
  name: String!
  assetType: AssetType!
  currentValue: String!
}

input UpdateAssetInput {
  id: ID!
  name: String!
  assetType: AssetType!
  currentValue: String!
}
