package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.95

import (
	"context"
	"errors"
	"fmt"
	"log/slog"
	"time"

	"breeze.api/graph/generated"
	"breeze.api/graph/model"
	"breeze.api/internal/db/sqlc"
	"breeze.api/internal/middleware"
	"breeze.api/internal/service"
	"github.com/google/uuid"
	"github.com/govalues/decimal"
	"github.com/jackc/pgx/v5/pgtype"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	svcInput, err := createUserInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	user, err := r.UserService.GetOrCreate(ctx, svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapUserToModel(user), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	svcInput, err := updateUserInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	user, err := r.UserService.Update(ctx, svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapUserToModel(user), nil
}

// CreateAsset is the resolver for the createAsset field.
func (r *mutationResolver) CreateAsset(ctx context.Context, input model.CreateAssetInput) (*model.Asset, error) {
	svcInput, err := createAssetInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		svcInput.UserID = resolvedID
	}

	asset, err := r.AssetService.Create(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapAssetToModel(asset), nil
}

// UpdateAsset is the resolver for the updateAsset field.
func (r *mutationResolver) UpdateAsset(ctx context.Context, input model.UpdateAssetInput) (*model.Asset, error) {
	svcInput, err := updateAssetInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	asset, err := r.AssetService.Update(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapAssetToModel(asset), nil
}

// DeleteAsset is the resolver for the deleteAsset field.
func (r *mutationResolver) DeleteAsset(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid asset id: %w", err)
	}

	err = r.AssetService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}

	return true, nil
}

// CreateLiability is the resolver for the createLiability field.
func (r *mutationResolver) CreateLiability(ctx context.Context, input model.CreateLiabilityInput) (*model.Liability, error) {
	svcInput, err := createLiabilityInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		svcInput.UserID = resolvedID
	}

	liability, err := r.LiabilityService.Create(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapLiabilityToModel(liability), nil
}

// UpdateLiability is the resolver for the updateLiability field.
func (r *mutationResolver) UpdateLiability(ctx context.Context, input model.UpdateLiabilityInput) (*model.Liability, error) {
	svcInput, err := updateLiabilityInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	liability, err := r.LiabilityService.Update(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapLiabilityToModel(liability), nil
}

// DeleteLiability is the resolver for the deleteLiability field.
func (r *mutationResolver) DeleteLiability(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid liability id: %w", err)
	}

	err = r.LiabilityService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}

	return true, nil
}

// CreateBudget is the resolver for the createBudget field.
func (r *mutationResolver) CreateBudget(ctx context.Context, input model.CreateBudgetInput) (*model.Budget, error) {
	svcInput, err := createBudgetInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		svcInput.UserID = resolvedID
	}

	// If a budget already exists for this user + month, update it instead.
	existing, lookupErr := r.BudgetService.GetByDate(ctx, svcInput.UserID, svcInput.Date)
	if lookupErr == nil {
		slog.Info("CreateBudget: updating existing budget", "budgetId", existing.ID.String(), "existingIncome", existing.MonthlyIncome.String())
		budget, updateErr := r.BudgetService.Update(ctx, &service.UpdateBudgetInput{
			ID:              existing.ID,
			MonthlyIncome:   svcInput.MonthlyIncome,
			MonthlyExpenses: svcInput.MonthlyExpenses,
		})
		if updateErr != nil {
			return nil, r.mapErr(ctx, updateErr)
		}
		slog.Info("CreateBudget: after initial update", "monthlyIncome", budget.MonthlyIncome.String())

		// Remove old recurring-generated incomes so regeneration is idempotent.
		_ = removeRecurringIncomesForBudget(ctx, r.IncomeService, budget.ID)
		if genErr := generateIncomesForBudget(ctx, r.RecurringIncomeService, r.IncomeService, svcInput.UserID, budget.ID, svcInput.Date); genErr != nil {
			slog.Warn("failed to generate recurring incomes for budget", "error", genErr)
		}

		// Replace people-payroll incomes (per-person payday net amounts).
		// Omitted input leaves existing payroll rows untouched.
		if input.PayrollIncomes != nil {
			if replaceErr := replacePayrollIncomesForBudget(ctx, r.IncomeService, svcInput.UserID, budget.ID, svcInput.Date, input.PayrollIncomes); replaceErr != nil {
				slog.Warn("failed to replace payroll incomes for budget", "error", replaceErr)
			}
		}

		// Remove old recurring-generated expense categories so regeneration is idempotent.
		_ = removeRecurringExpenseCategoriesForBudget(ctx, r.ExpenseCategoryService, r.ExpenseService, budget.ID)
		if genErr := generateExpenseCategoriesForBudget(ctx, r.RecurringExpenseService, r.ExpenseCategoryService, svcInput.UserID, budget.ID, svcInput.Date); genErr != nil {
			slog.Warn("failed to generate recurring expense categories for budget", "error", genErr)
		}

		budget = recalculateBudgetIncome(ctx, r.IncomeService, r.BudgetService, budget)
		budget = recalculateBudgetExpenses(ctx, r.ExpenseCategoryService, r.BudgetService, budget)
		slog.Info("CreateBudget: final response", "monthlyIncome", budget.MonthlyIncome.String(), "monthlyExpenses", budget.MonthlyExpenses.String())
		return mapBudgetToModel(budget), nil
	}

	budget, err := r.BudgetService.Create(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	// Generate incomes from recurring templates for the new budget month.
	if genErr := generateIncomesForBudget(ctx, r.RecurringIncomeService, r.IncomeService, svcInput.UserID, budget.ID, svcInput.Date); genErr != nil {
		slog.Warn("failed to generate recurring incomes for new budget", "error", genErr)
	}

	// Replace people-payroll incomes (per-person payday net amounts).
	// Omitted input leaves existing payroll rows untouched.
	if input.PayrollIncomes != nil {
		if replaceErr := replacePayrollIncomesForBudget(ctx, r.IncomeService, svcInput.UserID, budget.ID, svcInput.Date, input.PayrollIncomes); replaceErr != nil {
			slog.Warn("failed to replace payroll incomes for new budget", "error", replaceErr)
		}
	}

	// Generate expense categories from recurring templates for the new budget month.
	if genErr := generateExpenseCategoriesForBudget(ctx, r.RecurringExpenseService, r.ExpenseCategoryService, svcInput.UserID, budget.ID, svcInput.Date); genErr != nil {
		slog.Warn("failed to generate recurring expense categories for new budget", "error", genErr)
	}

	budget = recalculateBudgetIncome(ctx, r.IncomeService, r.BudgetService, budget)
	budget = recalculateBudgetExpenses(ctx, r.ExpenseCategoryService, r.BudgetService, budget)
	return mapBudgetToModel(budget), nil
}

// UpdateBudget is the resolver for the updateBudget field.
func (r *mutationResolver) UpdateBudget(ctx context.Context, input model.UpdateBudgetInput) (*model.Budget, error) {
	svcInput, err := updateBudgetInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	budget, err := r.BudgetService.Update(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapBudgetToModel(budget), nil
}

// DeleteBudget is the resolver for the deleteBudget field.
func (r *mutationResolver) DeleteBudget(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid budget id: %w", err)
	}

	err = r.BudgetService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}

	return true, nil
}

// CreateGoal is the resolver for the createGoal field.
func (r *mutationResolver) CreateGoal(ctx context.Context, input model.CreateGoalInput) (*model.Goal, error) {
	svcInput, err := createGoalInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	// Resolve the user from the auth context first (production path).
	// If that fails (local dev without Clerk), use the input userId directly.
	if userID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		svcInput.UserID = userID
	}

	goal, err := r.GoalService.Create(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapGoalToModel(goal), nil
}

// UpdateGoal is the resolver for the updateGoal field.
func (r *mutationResolver) UpdateGoal(ctx context.Context, input model.UpdateGoalInput) (*model.Goal, error) {
	svcInput, err := updateGoalInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	goal, err := r.GoalService.Update(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapGoalToModel(goal), nil
}

// DeleteGoal is the resolver for the deleteGoal field.
func (r *mutationResolver) DeleteGoal(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid goal id: %w", err)
	}

	err = r.GoalService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}

	return true, nil
}

// CreateExpenseCategory is the resolver for the createExpenseCategory field.
func (r *mutationResolver) CreateExpenseCategory(ctx context.Context, input model.CreateExpenseCategoryInput) (*model.ExpenseCategory, error) {
	svcInput, err := createExpenseCategoryInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		svcInput.UserID = resolvedID
	}

	category, err := r.ExpenseCategoryService.Create(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapExpenseCategoryToModel(category), nil
}

// CreateTransaction is the resolver for the createTransaction field.
func (r *mutationResolver) CreateTransaction(ctx context.Context, input model.CreateTransactionInput) (*model.Transaction, error) {
	userID, err := resolveUserIDFromCtx(ctx, r.UserService)
	if err != nil {
		return nil, err
	}

	date, err := parseDate(input.Date)
	if err != nil {
		return nil, fmt.Errorf("invalid date: %w", err)
	}

	amount, err := decimal.Parse(input.Amount)
	if err != nil {
		return nil, fmt.Errorf("invalid amount: %w", err)
	}

	var categoryID *uuid.UUID
	if input.ExpenseCategoryID != nil && *input.ExpenseCategoryID != "" {
		parsed, parseErr := uuid.Parse(*input.ExpenseCategoryID)
		if parseErr != nil {
			return nil, fmt.Errorf("invalid category id: %w", parseErr)
		}
		categoryID = &parsed
	}

	transaction, err := r.TransactionService.Create(ctx, &service.CreateTransactionInput{
		UserID:            userID,
		Date:              date,
		Amount:            amount,
		Name:              input.Name,
		ExpenseCategoryID: categoryID,
	})
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapTransactionToModel(transaction), nil
}

// AssignTransactionCategory is the resolver for the assignTransactionCategory field.
func (r *mutationResolver) AssignTransactionCategory(ctx context.Context, id string, expenseCategoryID *string) (*model.Transaction, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid transaction id: %w", err)
	}

	var categoryID *uuid.UUID
	if expenseCategoryID != nil && *expenseCategoryID != "" {
		parsed, parseErr := uuid.Parse(*expenseCategoryID)
		if parseErr != nil {
			return nil, fmt.Errorf("invalid category id: %w", parseErr)
		}
		categoryID = &parsed
	}

	transaction, err := r.TransactionService.AssignCategory(ctx, parsedID, categoryID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	// Realize the transaction in the budget: a categorized transaction gets a
	// matching expense row (so plan-vs-actual reflects bank spending); clearing
	// the category removes it.
	userID, authErr := resolveUserIDFromCtx(ctx, r.UserService)
	if authErr != nil {
		return nil, authErr
	}
	if syncErr := r.syncTransactionExpense(ctx, userID, transaction); syncErr != nil {
		return nil, r.mapErr(ctx, syncErr)
	}

	return mapTransactionToModel(transaction), nil
}

// DeleteTransaction is the resolver for the deleteTransaction field.
func (r *mutationResolver) DeleteTransaction(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid transaction id: %w", err)
	}

	if err := r.TransactionService.Delete(ctx, parsedID); err != nil {
		return false, r.mapErr(ctx, err)
	}
	return true, nil
}

// UpdateExpenseCategory is the resolver for the updateExpenseCategory field.
func (r *mutationResolver) UpdateExpenseCategory(ctx context.Context, input model.UpdateExpenseCategoryInput) (*model.ExpenseCategory, error) {
	svcInput, err := updateExpenseCategoryInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	category, err := r.ExpenseCategoryService.Update(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapExpenseCategoryToModel(category), nil
}

// DeleteExpenseCategory is the resolver for the deleteExpenseCategory field.
func (r *mutationResolver) DeleteExpenseCategory(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid expense category id: %w", err)
	}

	err = r.ExpenseCategoryService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}

	return true, nil
}

// CreateExpense is the resolver for the createExpense field.
func (r *mutationResolver) CreateExpense(ctx context.Context, input model.CreateExpenseInput) (*model.Expense, error) {
	svcInput, err := createExpenseInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		svcInput.UserID = resolvedID
	}

	expense, err := r.ExpenseService.Create(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapExpenseToModel(expense), nil
}

// UpdateExpense is the resolver for the updateExpense field.
func (r *mutationResolver) UpdateExpense(ctx context.Context, input model.UpdateExpenseInput) (*model.Expense, error) {
	svcInput, err := updateExpenseInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	expense, err := r.ExpenseService.Update(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapExpenseToModel(expense), nil
}

// DeleteExpense is the resolver for the deleteExpense field.
func (r *mutationResolver) DeleteExpense(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid expense id: %w", err)
	}

	err = r.ExpenseService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}

	return true, nil
}

// CreateIncome is the resolver for the createIncome field.
func (r *mutationResolver) CreateIncome(ctx context.Context, input model.CreateIncomeInput) (*model.Income, error) {
	svcInput, err := createIncomeInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		svcInput.UserID = resolvedID
	}

	income, err := r.IncomeService.Create(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapIncomeToModel(income), nil
}

// UpdateIncome is the resolver for the updateIncome field.
func (r *mutationResolver) UpdateIncome(ctx context.Context, input model.UpdateIncomeInput) (*model.Income, error) {
	svcInput, err := updateIncomeInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	income, err := r.IncomeService.Update(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapIncomeToModel(income), nil
}

// DeleteIncome is the resolver for the deleteIncome field.
func (r *mutationResolver) DeleteIncome(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid income id: %w", err)
	}

	err = r.IncomeService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}

	return true, nil
}

// CreateRecurringIncome is the resolver for the createRecurringIncome field.
func (r *mutationResolver) CreateRecurringIncome(ctx context.Context, input model.CreateRecurringIncomeInput) (*model.RecurringIncome, error) {
	svcInput, err := createRecurringIncomeInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		svcInput.UserID = resolvedID
	}

	income, err := r.RecurringIncomeService.Create(ctx, svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapRecurringIncomeToModel(income), nil
}

// UpdateRecurringIncome is the resolver for the updateRecurringIncome field.
func (r *mutationResolver) UpdateRecurringIncome(ctx context.Context, input model.UpdateRecurringIncomeInput) (*model.RecurringIncome, error) {
	svcInput, err := updateRecurringIncomeInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	income, err := r.RecurringIncomeService.Update(ctx, svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapRecurringIncomeToModel(income), nil
}

// DeleteRecurringIncome is the resolver for the deleteRecurringIncome field.
func (r *mutationResolver) DeleteRecurringIncome(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid recurring income id: %w", err)
	}

	err = r.RecurringIncomeService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}

	return true, nil
}

// CreateRecurringExpense is the resolver for the createRecurringExpense field.
func (r *mutationResolver) CreateRecurringExpense(ctx context.Context, input model.CreateRecurringExpenseInput) (*model.RecurringExpense, error) {
	svcInput, err := createRecurringExpenseInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		svcInput.UserID = resolvedID
	}

	expense, err := r.RecurringExpenseService.Create(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapRecurringExpenseToModel(expense), nil
}

// UpdateRecurringExpense is the resolver for the updateRecurringExpense field.
func (r *mutationResolver) UpdateRecurringExpense(ctx context.Context, input model.UpdateRecurringExpenseInput) (*model.RecurringExpense, error) {
	svcInput, err := updateRecurringExpenseInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	expense, err := r.RecurringExpenseService.Update(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapRecurringExpenseToModel(expense), nil
}

// DeleteRecurringExpense is the resolver for the deleteRecurringExpense field.
func (r *mutationResolver) DeleteRecurringExpense(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid recurring expense id: %w", err)
	}

	err = r.RecurringExpenseService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}

	return true, nil
}

// UpsertPlannerPerson is the resolver for the upsertPlannerPerson field.
func (r *mutationResolver) UpsertPlannerPerson(ctx context.Context, input model.UpsertPlannerPersonInput) (*model.PlannerPerson, error) {
	svcInput, err := upsertPlannerPersonInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	if userID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		svcInput.UserID = userID
	}

	person, err := r.PlannerPersonService.Upsert(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapPlannerPersonToModel(person), nil
}

// UpsertPaycheckDeduction is the resolver for the upsertPaycheckDeduction field.
func (r *mutationResolver) UpsertPaycheckDeduction(ctx context.Context, input model.UpsertPaycheckDeductionInput) (*model.PaycheckDeduction, error) {
	svcInput, err := upsertPaycheckDeductionInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	if userID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		svcInput.UserID = userID
	}

	deduction, err := r.PaycheckDeductionService.Upsert(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapPaycheckDeductionToModel(deduction), nil
}

// DeletePaycheckDeduction is the resolver for the deletePaycheckDeduction field.
func (r *mutationResolver) DeletePaycheckDeduction(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid paycheck deduction id: %w", err)
	}

	err = r.PaycheckDeductionService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}

	return true, nil
}

// DeletePlannerPerson is the resolver for the deletePlannerPerson field.
func (r *mutationResolver) DeletePlannerPerson(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid planner person id: %w", err)
	}

	err = r.PlannerPersonService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}

	return true, nil
}

// CreateTaxBracket is the resolver for the createTaxBracket field.
func (r *mutationResolver) CreateTaxBracket(ctx context.Context, input model.CreateTaxBracketInput) (*model.TaxBracket, error) {
	svcInput, err := createTaxBracketInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	bracket, err := r.TaxBracketService.Create(ctx, svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapTaxBracketToModel(bracket), nil
}

// UpdateTaxBracket is the resolver for the updateTaxBracket field.
func (r *mutationResolver) UpdateTaxBracket(ctx context.Context, input model.UpdateTaxBracketInput) (*model.TaxBracket, error) {
	svcInput, err := updateTaxBracketInputFromModel(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	bracket, err := r.TaxBracketService.Update(ctx, svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapTaxBracketToModel(bracket), nil
}

// DeleteTaxBracket is the resolver for the deleteTaxBracket field.
func (r *mutationResolver) DeleteTaxBracket(ctx context.Context, id string) (bool, error) {
	parsedID, err := taxBracketIDFromString(id)
	if err != nil {
		return false, r.mapErr(ctx, err)
	}

	err = r.TaxBracketService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}

	return true, nil
}

// CreateNetWorthSnapshot is the resolver for the createNetWorthSnapshot field.
func (r *mutationResolver) CreateNetWorthSnapshot(ctx context.Context, input model.CreateNetWorthSnapshotInput) (*model.NetWorthSnapshot, error) {
	svcInput, err := mapCreateNetWorthSnapshotInput(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		svcInput.UserID = resolvedID
	}

	snapshot, err := r.NetWorthSnapshotService.Create(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapNetWorthSnapshotToModel(snapshot), nil
}

// UpdateNetWorthSnapshot is the resolver for the updateNetWorthSnapshot field.
func (r *mutationResolver) UpdateNetWorthSnapshot(ctx context.Context, input model.UpdateNetWorthSnapshotInput) (*model.NetWorthSnapshot, error) {
	svcInput, err := mapUpdateNetWorthSnapshotInput(&input)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	snapshot, err := r.NetWorthSnapshotService.Update(ctx, &svcInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapNetWorthSnapshotToModel(snapshot), nil
}

// DeleteNetWorthSnapshot is the resolver for the deleteNetWorthSnapshot field.
func (r *mutationResolver) DeleteNetWorthSnapshot(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid net worth snapshot id: %w", err)
	}

	err = r.NetWorthSnapshotService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}

	return true, nil
}

// ExchangePlaidPublicToken exchanges a Link public token and creates a PlaidConnection.
func (r *mutationResolver) ExchangePlaidPublicToken(ctx context.Context, userID string, publicToken string) (*model.PlaidConnection, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		parsedUserID = resolvedID
	}

	conn, err := r.PlaidService.ExchangePublicToken(ctx, parsedUserID, publicToken)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := &model.PlaidConnection{
		ID:              conn.ID.String(),
		UserID:          conn.UserID.String(),
		Environment:     conn.Environment,
		InstitutionID:   conn.InstitutionID,
		InstitutionName: conn.InstitutionName,
		ItemID:          conn.ItemID,
		CreatedAt:       timestamptzToRFC3339(conn.CreatedAt),
		UpdatedAt:       timestamptzToRFC3339(conn.UpdatedAt),
	}
	return out, nil
}

// SyncPlaidConnection triggers a sync of accounts for a given connection.
func (r *mutationResolver) SyncPlaidConnection(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid connection id: %w", err)
	}
	if err := r.PlaidService.SyncAccounts(ctx, parsedID); err != nil {
		return false, r.mapErr(ctx, err)
	}
	// Bank transactions ride along with every account sync; failures here
	// shouldn't fail the balance sync, so log-and-continue.
	if err := r.PlaidService.SyncTransactions(ctx, parsedID); err != nil {
		middleware.LoggerFromCtx(ctx).Error("sync plaid transactions", "connection", id, "error", err)
	}
	return true, nil
}

// DeletePlaidConnection deletes (soft) a connection.
func (r *mutationResolver) DeletePlaidConnection(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid connection id: %w", err)
	}
	if err := r.PlaidService.Delete(ctx, parsedID); err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, r.mapErr(ctx, err)
	}
	return true, nil
}

// LinkAssetToPlaidAccount is the resolver for the linkAssetToPlaidAccount field.
func (r *mutationResolver) LinkAssetToPlaidAccount(ctx context.Context, assetID string, plaidAccountID string) (bool, error) {
	parsedAssetID, err := uuid.Parse(assetID)
	if err != nil {
		return false, fmt.Errorf("invalid asset id: %w", err)
	}
	parsedPlaidAccountID, err := uuid.Parse(plaidAccountID)
	if err != nil {
		return false, fmt.Errorf("invalid plaid account id: %w", err)
	}
	if err := r.PlaidService.LinkAssetToPlaidAccount(ctx, parsedAssetID, parsedPlaidAccountID); err != nil {
		return false, r.mapErr(ctx, err)
	}
	return true, nil
}

// UnlinkAssetFromPlaidAccount is the resolver for the unlinkAssetFromPlaidAccount field.
func (r *mutationResolver) UnlinkAssetFromPlaidAccount(ctx context.Context, assetID string) (bool, error) {
	parsedAssetID, err := uuid.Parse(assetID)
	if err != nil {
		return false, fmt.Errorf("invalid asset id: %w", err)
	}
	if err := r.PlaidService.UnlinkAssetFromPlaidAccount(ctx, parsedAssetID); err != nil {
		return false, r.mapErr(ctx, err)
	}
	return true, nil
}

// LinkLiabilityToPlaidAccount is the resolver for the linkLiabilityToPlaidAccount field.
func (r *mutationResolver) LinkLiabilityToPlaidAccount(ctx context.Context, liabilityID string, plaidAccountID string) (bool, error) {
	parsedLiabilityID, err := uuid.Parse(liabilityID)
	if err != nil {
		return false, fmt.Errorf("invalid liability id: %w", err)
	}
	parsedPlaidAccountID, err := uuid.Parse(plaidAccountID)
	if err != nil {
		return false, fmt.Errorf("invalid plaid account id: %w", err)
	}
	if err := r.PlaidService.LinkLiabilityToPlaidAccount(ctx, parsedLiabilityID, parsedPlaidAccountID); err != nil {
		return false, r.mapErr(ctx, err)
	}
	return true, nil
}

// UnlinkLiabilityFromPlaidAccount is the resolver for the unlinkLiabilityFromPlaidAccount field.
func (r *mutationResolver) UnlinkLiabilityFromPlaidAccount(ctx context.Context, liabilityID string) (bool, error) {
	parsedLiabilityID, err := uuid.Parse(liabilityID)
	if err != nil {
		return false, fmt.Errorf("invalid liability id: %w", err)
	}
	if err := r.PlaidService.UnlinkLiabilityFromPlaidAccount(ctx, parsedLiabilityID); err != nil {
		return false, r.mapErr(ctx, err)
	}
	return true, nil
}

// UpdateUserSetup is the resolver for the updateUserSetup field.
func (r *mutationResolver) UpdateUserSetup(ctx context.Context, input model.UpdateUserSetupInput) (*model.User, error) {
	userID, err := resolveUserIDFromCtx(ctx, r.UserService)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	parsedID, err := uuid.Parse(input.ID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	// Ensure user can only update their own setup
	if userID != parsedID {
		return nil, fmt.Errorf("unauthorized: cannot update another user's setup")
	}

	setupInput := service.UpdateSetupInput{
		ID: parsedID,
	}

	if input.BudgetEnabled != nil {
		setupInput.BudgetEnabled = input.BudgetEnabled
	}

	if input.MonthlyExpenses != nil {
		monthlyExpenses, err := decimal.Parse(*input.MonthlyExpenses)
		if err != nil {
			return nil, fmt.Errorf("invalid monthly expenses: %w", err)
		}
		setupInput.MonthlyExpenses = &monthlyExpenses
	}

	if input.SetupCompleted != nil {
		setupInput.SetupCompleted = input.SetupCompleted
	}

	if input.DisclaimerAccepted != nil {
		setupInput.DisclaimerAccepted = input.DisclaimerAccepted
	}

	if input.DisclaimerAcceptedAt != nil {
		t, err := time.Parse(time.RFC3339, *input.DisclaimerAcceptedAt)
		if err != nil {
			return nil, fmt.Errorf("invalid disclaimer accepted at: %w", err)
		}
		setupInput.DisclaimerAcceptedAt = &t
	}

	user, err := r.UserService.UpdateSetup(ctx, setupInput)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapUserToModel(user), nil
}

// CreateFinancialOrderSteps is the resolver for the createFinancialOrderSteps field.
func (r *mutationResolver) CreateFinancialOrderSteps(ctx context.Context) ([]*model.Goal, error) {
	userID, err := resolveUserIDFromCtx(ctx, r.UserService)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	goals, err := r.GoalService.CreateFinancialOrderSteps(ctx, userID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	result := make([]*model.Goal, len(goals))
	for i, goal := range goals {
		result[i] = mapGoalToModel(&goal)
	}

	return result, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	health, err := r.HealthService.Get(ctx)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return &model.Health{
		Status:    health.Status,
		Timestamp: health.Timestamp.Format(time.RFC3339),
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	user, err := r.UserService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}

	return mapUserToModel(user), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	identityProviderID := middleware.UserIDFromCtx(ctx)
	if identityProviderID == "" {
		return nil, nil
	}

	user, err := r.UserService.GetByIdentityProviderID(ctx, identityProviderID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}

	return mapUserToModel(user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.List(ctx)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.User, 0, len(users))
	for i := range users {
		user := users[i]
		mapped := mapUserToModel(&user)
		out = append(out, mapped)
	}

	return out, nil
}

// Asset is the resolver for the asset field.
func (r *queryResolver) Asset(ctx context.Context, id string) (*model.Asset, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid asset id: %w", err)
	}

	asset, err := r.AssetService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}

	return mapAssetToModel(asset), nil
}

// Assets is the resolver for the assets field.
func (r *queryResolver) Assets(ctx context.Context, userID string) ([]*model.Asset, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		parsedUserID = resolvedID
	}

	assets, err := r.AssetService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.Asset, 0, len(assets))
	for i := range assets {
		asset := assets[i]
		out = append(out, mapAssetToModel(&asset))
	}

	return out, nil
}

// Liability is the resolver for the liability field.
func (r *queryResolver) Liability(ctx context.Context, id string) (*model.Liability, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid liability id: %w", err)
	}

	liability, err := r.LiabilityService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}

	return mapLiabilityToModel(liability), nil
}

// Liabilities is the resolver for the liabilities field.
func (r *queryResolver) Liabilities(ctx context.Context, userID string) ([]*model.Liability, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		parsedUserID = resolvedID
	}

	liabilities, err := r.LiabilityService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.Liability, 0, len(liabilities))
	for i := range liabilities {
		liability := liabilities[i]
		out = append(out, mapLiabilityToModel(&liability))
	}

	return out, nil
}

// Budget is the resolver for the budget field.
func (r *queryResolver) Budget(ctx context.Context, id string) (*model.Budget, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid budget id: %w", err)
	}

	budget, err := r.BudgetService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}

	return mapBudgetToModel(budget), nil
}

// BudgetByDate is the resolver for the budgetByDate field.
func (r *queryResolver) BudgetByDate(ctx context.Context, userID string, date string) (*model.Budget, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		parsedUserID = resolvedID
	}

	budgetDate, err := time.Parse(time.RFC3339, date)
	if err != nil {
		return nil, fmt.Errorf("invalid budget date: %w", err)
	}

	budget, err := r.BudgetService.GetByDate(ctx, parsedUserID, budgetDate)
	if err != nil {
		if !errors.Is(err, service.ErrNotFound) {
			return nil, r.mapErr(ctx, err)
		}

		// Auto-create a budget for this month when none exists.
		budget, err = r.BudgetService.Create(ctx, &service.CreateBudgetInput{
			UserID:          parsedUserID,
			Date:            budgetDate,
			MonthlyIncome:   decimalZero(),
			MonthlyExpenses: decimalZero(),
		})
		if err != nil {
			return nil, r.mapErr(ctx, err)
		}

		// Generate incomes from recurring templates for the new budget month.
		if genErr := generateIncomesForBudget(ctx, r.RecurringIncomeService, r.IncomeService, parsedUserID, budget.ID, budgetDate); genErr != nil {
			slog.Warn("failed to generate recurring incomes for new budget", "error", genErr)
		}
	}

	return mapBudgetToModel(budget), nil
}

// Budgets is the resolver for the budgets field.
func (r *queryResolver) Budgets(ctx context.Context, userID string) ([]*model.Budget, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		parsedUserID = resolvedID
	}

	budgets, err := r.BudgetService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.Budget, 0, len(budgets))
	for i := range budgets {
		budget := budgets[i]
		out = append(out, mapBudgetToModel(&budget))
	}

	return out, nil
}

// Goal is the resolver for the goal field.
func (r *queryResolver) Goal(ctx context.Context, id string) (*model.Goal, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid goal id: %w", err)
	}

	goal, err := r.GoalService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}

	return mapGoalToModel(goal), nil
}

// Goals is the resolver for the goals field.
func (r *queryResolver) Goals(ctx context.Context, userID string) ([]*model.Goal, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		parsedUserID = resolvedID
	}

	goals, err := r.GoalService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.Goal, 0, len(goals))
	for i := range goals {
		goal := goals[i]
		out = append(out, mapGoalToModel(&goal))
	}

	return out, nil
}

// PlaidConnection is the resolver for the plaidConnection field.
func (r *queryResolver) PlaidConnection(ctx context.Context, id string) (*model.PlaidConnection, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid connection id: %w", err)
	}
	conn, err := r.PlaidService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}
	return mapPlaidConnectionToModel(conn), nil
}

// PlaidConnections is the resolver for the plaidConnections field.
func (r *queryResolver) PlaidConnections(ctx context.Context, userID string) ([]*model.PlaidConnection, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		parsedUserID = resolvedID
	}

	rows, err := r.PlaidService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}
	out := make([]*model.PlaidConnection, 0, len(rows))
	for _, conn := range rows {
		out = append(out, mapPlaidConnectionToModel(&conn))
	}
	return out, nil
}

// PlaidAccounts is the resolver for the plaidAccounts field.
func (r *queryResolver) PlaidAccounts(ctx context.Context, connectionID string) ([]*model.PlaidAccount, error) {
	parsedID, err := uuid.Parse(connectionID)
	if err != nil {
		return nil, fmt.Errorf("invalid connection id: %w", err)
	}
	rows, err := r.PlaidService.ListAccountsByConnectionID(ctx, parsedID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}
	out := make([]*model.PlaidAccount, 0, len(rows))
	for _, a := range rows {
		out = append(out, mapPlaidAccountToModel(&a))
	}
	return out, nil
}

// CreatePlaidLinkToken is the resolver for the createPlaidLinkToken field.
func (r *queryResolver) CreatePlaidLinkToken(ctx context.Context, userID string) (string, error) {
	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		userID = resolvedID.String()
	}

	token, err := r.PlaidService.CreateLinkToken(ctx, userID)
	if err != nil {
		return "", r.mapErr(ctx, err)
	}
	return token, nil
}

// ContributionLimits is the resolver for the contributionLimits field.
func (r *queryResolver) ContributionLimits(ctx context.Context, taxYear int) ([]*model.ContributionLimit, error) {
	limits, err := r.ContributionLimitService.ListByTaxYear(ctx, taxYear)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.ContributionLimit, 0, len(limits))
	for i := range limits {
		out = append(out, mapContributionLimitToModel(&limits[i]))
	}
	return out, nil
}

// ExpenseCategories is the resolver for the expenseCategories field.
func (r *queryResolver) ExpenseCategories(ctx context.Context, budgetID string) ([]*model.ExpenseCategory, error) {
	parsedBudgetID, err := uuid.Parse(budgetID)
	if err != nil {
		return nil, fmt.Errorf("invalid budget id: %w", err)
	}

	categories, err := r.ExpenseCategoryService.ListByBudgetID(ctx, parsedBudgetID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.ExpenseCategory, 0, len(categories))
	for i := range categories {
		category := categories[i]
		out = append(out, mapExpenseCategoryToModel(&category))
	}

	return out, nil
}

// Transactions is the resolver for the transactions field.
func (r *queryResolver) Transactions(ctx context.Context, userID string, fromDate *string, toDate *string) ([]*model.Transaction, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	now := time.Now().UTC()
	from := now.AddDate(0, -3, 0)
	to := now
	if fromDate != nil {
		if parsed, parseErr := parseDate(*fromDate); parseErr == nil {
			from = parsed
		}
	}
	if toDate != nil {
		if parsed, parseErr := parseDate(*toDate); parseErr == nil {
			to = parsed
		}
	}

	transactions, err := r.TransactionService.ListByUserID(ctx, parsedUserID, from, to)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.Transaction, 0, len(transactions))
	for i := range transactions {
		out = append(out, mapTransactionToModel(&transactions[i]))
	}
	return out, nil
}

// Expense is the resolver for the expense field.
func (r *queryResolver) Expense(ctx context.Context, id string) (*model.Expense, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid expense id: %w", err)
	}

	expense, err := r.ExpenseService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}

	return mapExpenseToModel(expense), nil
}

// Expenses is the resolver for the expenses field.
func (r *queryResolver) Expenses(ctx context.Context, budgetID string) ([]*model.Expense, error) {
	parsedBudgetID, err := uuid.Parse(budgetID)
	if err != nil {
		return nil, fmt.Errorf("invalid budget id: %w", err)
	}

	expenses, err := r.ExpenseService.ListByBudgetID(ctx, parsedBudgetID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.Expense, 0, len(expenses))
	for i := range expenses {
		expense := expenses[i]
		out = append(out, mapExpenseToModel(&expense))
	}

	return out, nil
}

// Income is the resolver for the income field.
func (r *queryResolver) Income(ctx context.Context, id string) (*model.Income, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid income id: %w", err)
	}

	income, err := r.IncomeService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}

	return mapIncomeToModel(income), nil
}

// Incomes is the resolver for the incomes field.
func (r *queryResolver) Incomes(ctx context.Context, budgetID string) ([]*model.Income, error) {
	parsedBudgetID, err := uuid.Parse(budgetID)
	if err != nil {
		return nil, fmt.Errorf("invalid budget id: %w", err)
	}

	incomes, err := r.IncomeService.ListByBudgetID(ctx, parsedBudgetID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.Income, 0, len(incomes))
	for i := range incomes {
		income := incomes[i]
		out = append(out, mapIncomeToModel(&income))
	}

	return out, nil
}

// RecurringIncome is the resolver for the recurringIncome field.
func (r *queryResolver) RecurringIncome(ctx context.Context, id string) (*model.RecurringIncome, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid recurring income id: %w", err)
	}

	income, err := r.RecurringIncomeService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}

	return mapRecurringIncomeToModel(income), nil
}

// RecurringIncomes is the resolver for the recurringIncomes field.
func (r *queryResolver) RecurringIncomes(ctx context.Context, userID string) ([]*model.RecurringIncome, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		parsedUserID = resolvedID
	}

	incomes, err := r.RecurringIncomeService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.RecurringIncome, 0, len(incomes))
	for i := range incomes {
		income := incomes[i]
		out = append(out, mapRecurringIncomeToModel(&income))
	}

	return out, nil
}

// RecurringExpense is the resolver for the recurringExpense field.
func (r *queryResolver) RecurringExpense(ctx context.Context, id string) (*model.RecurringExpense, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid recurring expense id: %w", err)
	}

	expense, err := r.RecurringExpenseService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}

	return mapRecurringExpenseToModel(expense), nil
}

// RecurringExpenses is the resolver for the recurringExpenses field.
func (r *queryResolver) RecurringExpenses(ctx context.Context, userID string) ([]*model.RecurringExpense, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		parsedUserID = resolvedID
	}

	expenses, err := r.RecurringExpenseService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.RecurringExpense, 0, len(expenses))
	for i := range expenses {
		expense := expenses[i]
		out = append(out, mapRecurringExpenseToModel(&expense))
	}

	return out, nil
}

// PlannerPeople is the resolver for the plannerPeople field.
func (r *queryResolver) PlannerPeople(ctx context.Context, userID string) ([]*model.PlannerPerson, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		parsedUserID = resolvedID
	}

	people, err := r.PlannerPersonService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.PlannerPerson, 0, len(people))
	for i := range people {
		person := people[i]
		out = append(out, mapPlannerPersonToModel(&person))
	}

	return out, nil
}

// PaycheckDeductions is the resolver for the paycheckDeductions field.
func (r *queryResolver) PaycheckDeductions(ctx context.Context, personID string) ([]*model.PaycheckDeduction, error) {
	parsedPersonID, err := uuid.Parse(personID)
	if err != nil {
		return nil, fmt.Errorf("invalid person id: %w", err)
	}

	userID := parsedPersonID
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		userID = resolvedID
	}

	deductions, err := r.PaycheckDeductionService.ListByPersonID(ctx, userID, parsedPersonID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	models := make([]*model.PaycheckDeduction, 0, len(deductions))
	for i := range deductions {
		models = append(models, mapPaycheckDeductionToModel(&deductions[i]))
	}
	return models, nil
}

// PaycheckDeductionsByUser is the resolver for the paycheckDeductionsByUser field.
func (r *queryResolver) PaycheckDeductionsByUser(ctx context.Context, userID string) ([]*model.PaycheckDeduction, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		parsedUserID = resolvedID
	}

	deductions, err := r.PaycheckDeductionService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	models := make([]*model.PaycheckDeduction, 0, len(deductions))
	for i := range deductions {
		models = append(models, mapPaycheckDeductionToModel(&deductions[i]))
	}
	return models, nil
}

// TaxBracket is the resolver for the taxBracket field.
func (r *queryResolver) TaxBracket(ctx context.Context, id string) (*model.TaxBracket, error) {
	parsedID, err := taxBracketIDFromString(id)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	bracket, err := r.TaxBracketService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}

	return mapTaxBracketToModel(bracket), nil
}

// TaxBrackets is the resolver for the taxBrackets field.
func (r *queryResolver) TaxBrackets(ctx context.Context, year int, filingStatus model.FilingStatus) ([]*model.TaxBracket, error) {
	serviceYear, err := taxBracketYearFromInput(year)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	brackets, err := r.TaxBracketService.ListByYearAndFilingStatus(ctx, serviceYear, sqlc.FilingStatus(filingStatus))
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.TaxBracket, 0, len(brackets))
	for i := range brackets {
		bracket := brackets[i]
		out = append(out, mapTaxBracketToModel(&bracket))
	}

	return out, nil
}

// TaxYearData is the resolver for the taxYearData field.
func (r *queryResolver) TaxYearData(ctx context.Context, year *int, filingStatus model.FilingStatus) (*model.TaxYearData, error) {
	var serviceYear *int32
	if year != nil {
		parsed, err := taxBracketYearFromInput(*year)
		if err != nil {
			return nil, r.mapErr(ctx, err)
		}
		serviceYear = &parsed
	}

	data, err := r.TaxYearService.GetTaxYearData(ctx, serviceYear, sqlc.FilingStatus(filingStatus))
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	return mapTaxYearDataToModel(data), nil
}

// EstimateTaxesForYear is the resolver for the estimateTaxesForYear field.
func (r *queryResolver) EstimateTaxesForYear(ctx context.Context, year int, filingStatus model.FilingStatus, income string, deduction *string) (*model.TaxEstimate, error) {
	// Parse income as decimal
	incomeDecimal, err := decimalFromString(income)
	if err != nil {
		return nil, fmt.Errorf("parse income: %w", err)
	}

	// Parse optional deduction
	var deductionNumeric *pgtype.Numeric
	if deduction != nil {
		deductionNumeric, err = pgNumericFromString(*deduction)
		if err != nil {
			return nil, fmt.Errorf("parse deduction: %w", err)
		}
	}

	// Convert year to int32
	yearInt32 := int32(year)

	// Convert FilingStatus from model to sqlc
	sqlcFilingStatus := parseFilingStatus(filingStatus)

	// Call service to estimate taxes
	est, err := r.TaxPlanningService.EstimateForYear(ctx, yearInt32, sqlcFilingStatus, incomeDecimal, deductionNumeric)
	if err != nil {
		return nil, fmt.Errorf("estimate taxes: %w", err)
	}

	// Map to GraphQL model
	return mapTaxEstimateToModel(est), nil
}

// CalculateRetirementLadder is the resolver for the calculateRetirementLadder field.
func (r *queryResolver) CalculateRetirementLadder(ctx context.Context, initialBalance string, annualExpenses string, currentAge int, firstWithdrawalAge int, isRoth bool, year int, filingStatus model.FilingStatus, yearsToProject *int) (*model.RetirementLadderProjection, error) {
	// Parse and validate inputs
	balDecimal, expDecimal, yearInt32, sqlcFilingStatus, err := parseRetirementLadderInput(initialBalance, annualExpenses, currentAge, firstWithdrawalAge, isRoth, year, filingStatus)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	// Default yearsToProject to 20 if not specified
	projectYears := 20
	if yearsToProject != nil && *yearsToProject > 0 {
		projectYears = *yearsToProject
	}

	// Call service to calculate ladder projection
	proj, err := r.RetirementLadderService.CalculateLadderProjection(
		ctx,
		balDecimal,
		expDecimal,
		currentAge,
		firstWithdrawalAge,
		isRoth,
		yearInt32,
		sqlcFilingStatus,
		projectYears,
	)
	if err != nil {
		return nil, fmt.Errorf("calculate retirement ladder: %w", err)
	}

	// Map to GraphQL model
	return mapRetirementLadderProjectionToModel(proj), nil
}

// NetWorthSnapshot is the resolver for the netWorthSnapshot field.
func (r *queryResolver) NetWorthSnapshot(ctx context.Context, id string) (*model.NetWorthSnapshot, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid net worth snapshot id: %w", err)
	}

	snapshot, err := r.NetWorthSnapshotService.Get(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}

	return mapNetWorthSnapshotToModel(snapshot), nil
}

// NetWorthSnapshotByDate is the resolver for the netWorthSnapshotByDate field.
func (r *queryResolver) NetWorthSnapshotByDate(ctx context.Context, userID string, date string) (*model.NetWorthSnapshot, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		parsedUserID = resolvedID
	}

	snapshotDate, err := time.Parse(time.RFC3339, date)
	if err != nil {
		return nil, fmt.Errorf("invalid snapshot date: %w", err)
	}

	snapshot, err := r.NetWorthSnapshotService.GetByDate(ctx, parsedUserID, snapshotDate)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, r.mapErr(ctx, err)
	}

	return mapNetWorthSnapshotToModel(snapshot), nil
}

// NetWorthSnapshots is the resolver for the netWorthSnapshots field.
func (r *queryResolver) NetWorthSnapshots(ctx context.Context, userID string) ([]*model.NetWorthSnapshot, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	// Resolve the authenticated user from context when available.
	if resolvedID, authErr := resolveUserIDFromCtx(ctx, r.UserService); authErr == nil {
		parsedUserID = resolvedID
	}

	snapshots, err := r.NetWorthSnapshotService.List(ctx, parsedUserID)
	if err != nil {
		return nil, r.mapErr(ctx, err)
	}

	out := make([]*model.NetWorthSnapshot, 0, len(snapshots))
	for i := range snapshots {
		snapshot := snapshots[i]
		out = append(out, mapNetWorthSnapshotToModel(&snapshot))
	}

	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type (
	mutationResolver struct{ *Resolver }
	queryResolver    struct{ *Resolver }
)
