package graph

// This file will be automatically regenerated based on the schema, any resolver
// implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.89

import (
	"context"
	"errors"
	"fmt"
	"time"

	"breeze.api/graph/generated"
	"breeze.api/graph/model"
	"breeze.api/internal/db/sqlc"
	"breeze.api/internal/middleware"
	"breeze.api/internal/service"
	"github.com/google/uuid"
)

// CreateUser is the resolver for the createUser field.
func (r *mutationResolver) CreateUser(ctx context.Context, input model.CreateUserInput) (*model.User, error) {
	svcInput, err := createUserInputFromModel(input)
	if err != nil {
		return nil, err
	}

	user, err := r.UserService.Create(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapUserToModel(user), nil
}

// UpdateUser is the resolver for the updateUser field.
func (r *mutationResolver) UpdateUser(ctx context.Context, input model.UpdateUserInput) (*model.User, error) {
	svcInput, err := updateUserInputFromModel(input)
	if err != nil {
		return nil, err
	}

	user, err := r.UserService.Update(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapUserToModel(user), nil
}

// DeleteUser is the resolver for the deleteUser field.
func (r *mutationResolver) DeleteUser(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid user id: %w", err)
	}

	err = r.UserService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// CreateAsset is the resolver for the createAsset field.
func (r *mutationResolver) CreateAsset(ctx context.Context, input model.CreateAssetInput) (*model.Asset, error) {
	svcInput, err := createAssetInputFromModel(input)
	if err != nil {
		return nil, err
	}

	asset, err := r.AssetService.Create(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapAssetToModel(asset), nil
}

// UpdateAsset is the resolver for the updateAsset field.
func (r *mutationResolver) UpdateAsset(ctx context.Context, input model.UpdateAssetInput) (*model.Asset, error) {
	svcInput, err := updateAssetInputFromModel(input)
	if err != nil {
		return nil, err
	}

	asset, err := r.AssetService.Update(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapAssetToModel(asset), nil
}

// DeleteAsset is the resolver for the deleteAsset field.
func (r *mutationResolver) DeleteAsset(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid asset id: %w", err)
	}

	err = r.AssetService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// CreateLiability is the resolver for the createLiability field.
func (r *mutationResolver) CreateLiability(ctx context.Context, input model.CreateLiabilityInput) (*model.Liability, error) {
	svcInput, err := createLiabilityInputFromModel(input)
	if err != nil {
		return nil, err
	}

	liability, err := r.LiabilityService.Create(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapLiabilityToModel(liability), nil
}

// UpdateLiability is the resolver for the updateLiability field.
func (r *mutationResolver) UpdateLiability(ctx context.Context, input model.UpdateLiabilityInput) (*model.Liability, error) {
	svcInput, err := updateLiabilityInputFromModel(input)
	if err != nil {
		return nil, err
	}

	liability, err := r.LiabilityService.Update(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapLiabilityToModel(liability), nil
}

// DeleteLiability is the resolver for the deleteLiability field.
func (r *mutationResolver) DeleteLiability(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid liability id: %w", err)
	}

	err = r.LiabilityService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// CreateBudget is the resolver for the createBudget field.
func (r *mutationResolver) CreateBudget(ctx context.Context, input model.CreateBudgetInput) (*model.Budget, error) {
	svcInput, err := createBudgetInputFromModel(input)
	if err != nil {
		return nil, err
	}

	budget, err := r.BudgetService.Create(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapBudgetToModel(budget), nil
}

// UpdateBudget is the resolver for the updateBudget field.
func (r *mutationResolver) UpdateBudget(ctx context.Context, input model.UpdateBudgetInput) (*model.Budget, error) {
	svcInput, err := updateBudgetInputFromModel(input)
	if err != nil {
		return nil, err
	}

	budget, err := r.BudgetService.Update(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapBudgetToModel(budget), nil
}

// DeleteBudget is the resolver for the deleteBudget field.
func (r *mutationResolver) DeleteBudget(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid budget id: %w", err)
	}

	err = r.BudgetService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// CreateGoal is the resolver for the createGoal field.
func (r *mutationResolver) CreateGoal(ctx context.Context, input model.CreateGoalInput) (*model.Goal, error) {
	svcInput, err := createGoalInputFromModel(input)
	if err != nil {
		return nil, err
	}

	goal, err := r.GoalService.Create(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapGoalToModel(goal), nil
}

// UpdateGoal is the resolver for the updateGoal field.
func (r *mutationResolver) UpdateGoal(ctx context.Context, input model.UpdateGoalInput) (*model.Goal, error) {
	svcInput, err := updateGoalInputFromModel(input)
	if err != nil {
		return nil, err
	}

	goal, err := r.GoalService.Update(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapGoalToModel(goal), nil
}

// DeleteGoal is the resolver for the deleteGoal field.
func (r *mutationResolver) DeleteGoal(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid goal id: %w", err)
	}

	err = r.GoalService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// CreateRetirementAccount is the resolver for the createRetirementAccount field.
func (r *mutationResolver) CreateRetirementAccount(ctx context.Context, input model.CreateRetirementAccountInput) (*model.RetirementAccount, error) {
	svcInput, err := createRetirementAccountInputFromModel(input)
	if err != nil {
		return nil, err
	}

	account, err := r.RetirementService.Create(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapRetirementAccountToModel(account), nil
}

// UpdateRetirementAccount is the resolver for the updateRetirementAccount field.
func (r *mutationResolver) UpdateRetirementAccount(ctx context.Context, input model.UpdateRetirementAccountInput) (*model.RetirementAccount, error) {
	svcInput, err := updateRetirementAccountInputFromModel(input)
	if err != nil {
		return nil, err
	}

	account, err := r.RetirementService.Update(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapRetirementAccountToModel(account), nil
}

// DeleteRetirementAccount is the resolver for the deleteRetirementAccount field.
func (r *mutationResolver) DeleteRetirementAccount(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid retirement account id: %w", err)
	}

	err = r.RetirementService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// AddContribution is the resolver for the addContribution field.
func (r *mutationResolver) AddContribution(ctx context.Context, input model.AddContributionInput) (*model.ContributionEntry, error) {
	svcInput, err := addContributionInputFromModel(input)
	if err != nil {
		return nil, err
	}

	entry, err := r.RetirementService.AddContribution(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapContributionEntryToModel(entry), nil
}

// CreateExpenseCategory is the resolver for the createExpenseCategory field.
func (r *mutationResolver) CreateExpenseCategory(ctx context.Context, input model.CreateExpenseCategoryInput) (*model.ExpenseCategory, error) {
	svcInput, err := createExpenseCategoryInputFromModel(input)
	if err != nil {
		return nil, err
	}

	category, err := r.ExpenseCategoryService.Create(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapExpenseCategoryToModel(category), nil
}

// UpdateExpenseCategory is the resolver for the updateExpenseCategory field.
func (r *mutationResolver) UpdateExpenseCategory(ctx context.Context, input model.UpdateExpenseCategoryInput) (*model.ExpenseCategory, error) {
	svcInput, err := updateExpenseCategoryInputFromModel(input)
	if err != nil {
		return nil, err
	}

	category, err := r.ExpenseCategoryService.Update(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapExpenseCategoryToModel(category), nil
}

// DeleteExpenseCategory is the resolver for the deleteExpenseCategory field.
func (r *mutationResolver) DeleteExpenseCategory(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid expense category id: %w", err)
	}

	err = r.ExpenseCategoryService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// CreateExpense is the resolver for the createExpense field.
func (r *mutationResolver) CreateExpense(ctx context.Context, input model.CreateExpenseInput) (*model.Expense, error) {
	svcInput, err := createExpenseInputFromModel(input)
	if err != nil {
		return nil, err
	}

	expense, err := r.ExpenseService.Create(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapExpenseToModel(expense), nil
}

// UpdateExpense is the resolver for the updateExpense field.
func (r *mutationResolver) UpdateExpense(ctx context.Context, input model.UpdateExpenseInput) (*model.Expense, error) {
	svcInput, err := updateExpenseInputFromModel(input)
	if err != nil {
		return nil, err
	}

	expense, err := r.ExpenseService.Update(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapExpenseToModel(expense), nil
}

// DeleteExpense is the resolver for the deleteExpense field.
func (r *mutationResolver) DeleteExpense(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid expense id: %w", err)
	}

	err = r.ExpenseService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// CreateIncome is the resolver for the createIncome field.
func (r *mutationResolver) CreateIncome(ctx context.Context, input model.CreateIncomeInput) (*model.Income, error) {
	svcInput, err := createIncomeInputFromModel(input)
	if err != nil {
		return nil, err
	}

	income, err := r.IncomeService.Create(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapIncomeToModel(income), nil
}

// UpdateIncome is the resolver for the updateIncome field.
func (r *mutationResolver) UpdateIncome(ctx context.Context, input model.UpdateIncomeInput) (*model.Income, error) {
	svcInput, err := updateIncomeInputFromModel(input)
	if err != nil {
		return nil, err
	}

	income, err := r.IncomeService.Update(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapIncomeToModel(income), nil
}

// DeleteIncome is the resolver for the deleteIncome field.
func (r *mutationResolver) DeleteIncome(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid income id: %w", err)
	}

	err = r.IncomeService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// CreateRecurringIncome is the resolver for the createRecurringIncome field.
func (r *mutationResolver) CreateRecurringIncome(ctx context.Context, input model.CreateRecurringIncomeInput) (*model.RecurringIncome, error) {
	svcInput, err := createRecurringIncomeInputFromModel(input)
	if err != nil {
		return nil, err
	}

	income, err := r.RecurringIncomeService.Create(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapRecurringIncomeToModel(income), nil
}

// UpdateRecurringIncome is the resolver for the updateRecurringIncome field.
func (r *mutationResolver) UpdateRecurringIncome(ctx context.Context, input model.UpdateRecurringIncomeInput) (*model.RecurringIncome, error) {
	svcInput, err := updateRecurringIncomeInputFromModel(input)
	if err != nil {
		return nil, err
	}

	income, err := r.RecurringIncomeService.Update(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapRecurringIncomeToModel(income), nil
}

// DeleteRecurringIncome is the resolver for the deleteRecurringIncome field.
func (r *mutationResolver) DeleteRecurringIncome(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid recurring income id: %w", err)
	}

	err = r.RecurringIncomeService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// CreateTaxBracket is the resolver for the createTaxBracket field.
func (r *mutationResolver) CreateTaxBracket(ctx context.Context, input model.CreateTaxBracketInput) (*model.TaxBracket, error) {
	svcInput, err := createTaxBracketInputFromModel(input)
	if err != nil {
		return nil, err
	}

	bracket, err := r.TaxBracketService.Create(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapTaxBracketToModel(bracket), nil
}

// UpdateTaxBracket is the resolver for the updateTaxBracket field.
func (r *mutationResolver) UpdateTaxBracket(ctx context.Context, input model.UpdateTaxBracketInput) (*model.TaxBracket, error) {
	svcInput, err := updateTaxBracketInputFromModel(input)
	if err != nil {
		return nil, err
	}

	bracket, err := r.TaxBracketService.Update(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapTaxBracketToModel(bracket), nil
}

// DeleteTaxBracket is the resolver for the deleteTaxBracket field.
func (r *mutationResolver) DeleteTaxBracket(ctx context.Context, id string) (bool, error) {
	parsedID, err := taxBracketIDFromString(id)
	if err != nil {
		return false, err
	}

	err = r.TaxBracketService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// CreateNetWorthSnapshot is the resolver for the createNetWorthSnapshot field.
func (r *mutationResolver) CreateNetWorthSnapshot(ctx context.Context, input model.CreateNetWorthSnapshotInput) (*model.NetWorthSnapshot, error) {
	svcInput, err := mapCreateNetWorthSnapshotInput(input)
	if err != nil {
		return nil, err
	}

	snapshot, err := r.NetWorthSnapshotService.Create(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapNetWorthSnapshotToModel(snapshot), nil
}

// UpdateNetWorthSnapshot is the resolver for the updateNetWorthSnapshot field.
func (r *mutationResolver) UpdateNetWorthSnapshot(ctx context.Context, input model.UpdateNetWorthSnapshotInput) (*model.NetWorthSnapshot, error) {
	svcInput, err := mapUpdateNetWorthSnapshotInput(input)
	if err != nil {
		return nil, err
	}

	snapshot, err := r.NetWorthSnapshotService.Update(ctx, svcInput)
	if err != nil {
		return nil, err
	}

	return mapNetWorthSnapshotToModel(snapshot), nil
}

// DeleteNetWorthSnapshot is the resolver for the deleteNetWorthSnapshot field.
func (r *mutationResolver) DeleteNetWorthSnapshot(ctx context.Context, id string) (bool, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return false, fmt.Errorf("invalid net worth snapshot id: %w", err)
	}

	err = r.NetWorthSnapshotService.Delete(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return false, nil
		}
		return false, err
	}

	return true, nil
}

// Health is the resolver for the health field.
func (r *queryResolver) Health(ctx context.Context) (*model.Health, error) {
	health, err := r.HealthService.Get(ctx)
	if err != nil {
		return nil, err
	}

	return &model.Health{
		Status:    health.Status,
		Timestamp: health.Timestamp.Format(time.RFC3339),
	}, nil
}

// User is the resolver for the user field.
func (r *queryResolver) User(ctx context.Context, id string) (*model.User, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	user, err := r.UserService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapUserToModel(user), nil
}

// Me is the resolver for the me field.
func (r *queryResolver) Me(ctx context.Context) (*model.User, error) {
	identityProviderID := middleware.UserIDFromCtx(ctx)
	if identityProviderID == "" {
		return nil, nil
	}

	user, err := r.UserService.GetByIdentityProviderID(ctx, identityProviderID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapUserToModel(user), nil
}

// Users is the resolver for the users field.
func (r *queryResolver) Users(ctx context.Context) ([]*model.User, error) {
	users, err := r.UserService.List(ctx)
	if err != nil {
		return nil, err
	}

	out := make([]*model.User, 0, len(users))
	for i := range users {
		user := users[i]
		mapped := mapUserToModel(&user)
		out = append(out, mapped)
	}

	return out, nil
}

// Asset is the resolver for the asset field.
func (r *queryResolver) Asset(ctx context.Context, id string) (*model.Asset, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid asset id: %w", err)
	}

	asset, err := r.AssetService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapAssetToModel(asset), nil
}

// Assets is the resolver for the assets field.
func (r *queryResolver) Assets(ctx context.Context, userID string) ([]*model.Asset, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	assets, err := r.AssetService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Asset, 0, len(assets))
	for i := range assets {
		asset := assets[i]
		out = append(out, mapAssetToModel(&asset))
	}

	return out, nil
}

// Liability is the resolver for the liability field.
func (r *queryResolver) Liability(ctx context.Context, id string) (*model.Liability, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid liability id: %w", err)
	}

	liability, err := r.LiabilityService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapLiabilityToModel(liability), nil
}

// Liabilities is the resolver for the liabilities field.
func (r *queryResolver) Liabilities(ctx context.Context, userID string) ([]*model.Liability, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	liabilities, err := r.LiabilityService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Liability, 0, len(liabilities))
	for i := range liabilities {
		liability := liabilities[i]
		out = append(out, mapLiabilityToModel(&liability))
	}

	return out, nil
}

// Budget is the resolver for the budget field.
func (r *queryResolver) Budget(ctx context.Context, id string) (*model.Budget, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid budget id: %w", err)
	}

	budget, err := r.BudgetService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapBudgetToModel(budget), nil
}

// BudgetByDate is the resolver for the budgetByDate field.
func (r *queryResolver) BudgetByDate(ctx context.Context, userID string, date string) (*model.Budget, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	budgetDate, err := time.Parse(time.RFC3339, date)
	if err != nil {
		return nil, fmt.Errorf("invalid budget date: %w", err)
	}

	budget, err := r.BudgetService.GetByDate(ctx, parsedUserID, budgetDate)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapBudgetToModel(budget), nil
}

// Budgets is the resolver for the budgets field.
func (r *queryResolver) Budgets(ctx context.Context, userID string) ([]*model.Budget, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	budgets, err := r.BudgetService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Budget, 0, len(budgets))
	for i := range budgets {
		budget := budgets[i]
		out = append(out, mapBudgetToModel(&budget))
	}

	return out, nil
}

// Goal is the resolver for the goal field.
func (r *queryResolver) Goal(ctx context.Context, id string) (*model.Goal, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid goal id: %w", err)
	}

	goal, err := r.GoalService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapGoalToModel(goal), nil
}

// Goals is the resolver for the goals field.
func (r *queryResolver) Goals(ctx context.Context, userID string) ([]*model.Goal, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	goals, err := r.GoalService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Goal, 0, len(goals))
	for i := range goals {
		goal := goals[i]
		out = append(out, mapGoalToModel(&goal))
	}

	return out, nil
}

// RetirementAccount is the resolver for the retirementAccount field.
func (r *queryResolver) RetirementAccount(ctx context.Context, id string) (*model.RetirementAccount, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid retirement account id: %w", err)
	}

	account, err := r.RetirementService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapRetirementAccountToModel(account), nil
}

// RetirementAccounts is the resolver for the retirementAccounts field.
func (r *queryResolver) RetirementAccounts(ctx context.Context, userID string) ([]*model.RetirementAccount, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	accounts, err := r.RetirementService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.RetirementAccount, 0, len(accounts))
	for i := range accounts {
		account := accounts[i]
		out = append(out, mapRetirementAccountToModel(&account))
	}

	return out, nil
}

// ContributionProgress is the resolver for the contributionProgress field.
func (r *queryResolver) ContributionProgress(ctx context.Context, retirementAccountID string, taxYear int) (*model.ContributionProgress, error) {
	parsedID, err := uuid.Parse(retirementAccountID)
	if err != nil {
		return nil, fmt.Errorf("invalid retirement account id: %w", err)
	}

	progress, err := r.RetirementService.GetContributionProgress(ctx, parsedID, taxYear)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, fmt.Errorf("retirement account not found")
		}
		return nil, err
	}

	return mapContributionProgressToModel(progress), nil
}

// ExpenseCategory is the resolver for the expenseCategory field.
func (r *queryResolver) ExpenseCategory(ctx context.Context, id string) (*model.ExpenseCategory, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid expense category id: %w", err)
	}

	category, err := r.ExpenseCategoryService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapExpenseCategoryToModel(category), nil
}

// ExpenseCategories is the resolver for the expenseCategories field.
func (r *queryResolver) ExpenseCategories(ctx context.Context, budgetID string) ([]*model.ExpenseCategory, error) {
	parsedBudgetID, err := uuid.Parse(budgetID)
	if err != nil {
		return nil, fmt.Errorf("invalid budget id: %w", err)
	}

	categories, err := r.ExpenseCategoryService.ListByBudgetID(ctx, parsedBudgetID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.ExpenseCategory, 0, len(categories))
	for i := range categories {
		category := categories[i]
		out = append(out, mapExpenseCategoryToModel(&category))
	}

	return out, nil
}

// Expense is the resolver for the expense field.
func (r *queryResolver) Expense(ctx context.Context, id string) (*model.Expense, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid expense id: %w", err)
	}

	expense, err := r.ExpenseService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapExpenseToModel(expense), nil
}

// Expenses is the resolver for the expenses field.
func (r *queryResolver) Expenses(ctx context.Context, budgetID string) ([]*model.Expense, error) {
	parsedBudgetID, err := uuid.Parse(budgetID)
	if err != nil {
		return nil, fmt.Errorf("invalid budget id: %w", err)
	}

	expenses, err := r.ExpenseService.ListByBudgetID(ctx, parsedBudgetID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Expense, 0, len(expenses))
	for i := range expenses {
		expense := expenses[i]
		out = append(out, mapExpenseToModel(&expense))
	}

	return out, nil
}

// Income is the resolver for the income field.
func (r *queryResolver) Income(ctx context.Context, id string) (*model.Income, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid income id: %w", err)
	}

	income, err := r.IncomeService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapIncomeToModel(income), nil
}

// Incomes is the resolver for the incomes field.
func (r *queryResolver) Incomes(ctx context.Context, budgetID string) ([]*model.Income, error) {
	parsedBudgetID, err := uuid.Parse(budgetID)
	if err != nil {
		return nil, fmt.Errorf("invalid budget id: %w", err)
	}

	incomes, err := r.IncomeService.ListByBudgetID(ctx, parsedBudgetID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.Income, 0, len(incomes))
	for i := range incomes {
		income := incomes[i]
		out = append(out, mapIncomeToModel(&income))
	}

	return out, nil
}

// RecurringIncome is the resolver for the recurringIncome field.
func (r *queryResolver) RecurringIncome(ctx context.Context, id string) (*model.RecurringIncome, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid recurring income id: %w", err)
	}

	income, err := r.RecurringIncomeService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapRecurringIncomeToModel(income), nil
}

// RecurringIncomes is the resolver for the recurringIncomes field.
func (r *queryResolver) RecurringIncomes(ctx context.Context, userID string) ([]*model.RecurringIncome, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	incomes, err := r.RecurringIncomeService.ListByUserID(ctx, parsedUserID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.RecurringIncome, 0, len(incomes))
	for i := range incomes {
		income := incomes[i]
		out = append(out, mapRecurringIncomeToModel(&income))
	}

	return out, nil
}

// TaxBracket is the resolver for the taxBracket field.
func (r *queryResolver) TaxBracket(ctx context.Context, id string) (*model.TaxBracket, error) {
	parsedID, err := taxBracketIDFromString(id)
	if err != nil {
		return nil, err
	}

	bracket, err := r.TaxBracketService.GetByID(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapTaxBracketToModel(bracket), nil
}

// TaxBrackets is the resolver for the taxBrackets field.
func (r *queryResolver) TaxBrackets(ctx context.Context, year int, filingStatus model.FilingStatus) ([]*model.TaxBracket, error) {
	serviceYear, err := taxBracketYearFromInput(year)
	if err != nil {
		return nil, err
	}

	brackets, err := r.TaxBracketService.ListByYearAndFilingStatus(ctx, serviceYear, sqlc.FilingStatus(filingStatus))
	if err != nil {
		return nil, err
	}

	out := make([]*model.TaxBracket, 0, len(brackets))
	for i := range brackets {
		bracket := brackets[i]
		out = append(out, mapTaxBracketToModel(&bracket))
	}

	return out, nil
}

// NetWorthSnapshot is the resolver for the netWorthSnapshot field.
func (r *queryResolver) NetWorthSnapshot(ctx context.Context, id string) (*model.NetWorthSnapshot, error) {
	parsedID, err := uuid.Parse(id)
	if err != nil {
		return nil, fmt.Errorf("invalid net worth snapshot id: %w", err)
	}

	snapshot, err := r.NetWorthSnapshotService.Get(ctx, parsedID)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapNetWorthSnapshotToModel(snapshot), nil
}

// NetWorthSnapshotByDate is the resolver for the netWorthSnapshotByDate field.
func (r *queryResolver) NetWorthSnapshotByDate(ctx context.Context, userID string, date string) (*model.NetWorthSnapshot, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	snapshotDate, err := time.Parse(time.RFC3339, date)
	if err != nil {
		return nil, fmt.Errorf("invalid snapshot date: %w", err)
	}

	snapshot, err := r.NetWorthSnapshotService.GetByDate(ctx, parsedUserID, snapshotDate)
	if err != nil {
		if errors.Is(err, service.ErrNotFound) {
			return nil, nil
		}
		return nil, err
	}

	return mapNetWorthSnapshotToModel(snapshot), nil
}

// NetWorthSnapshots is the resolver for the netWorthSnapshots field.
func (r *queryResolver) NetWorthSnapshots(ctx context.Context, userID string) ([]*model.NetWorthSnapshot, error) {
	parsedUserID, err := uuid.Parse(userID)
	if err != nil {
		return nil, fmt.Errorf("invalid user id: %w", err)
	}

	snapshots, err := r.NetWorthSnapshotService.List(ctx, parsedUserID)
	if err != nil {
		return nil, err
	}

	out := make([]*model.NetWorthSnapshot, 0, len(snapshots))
	for i := range snapshots {
		snapshot := snapshots[i]
		out = append(out, mapNetWorthSnapshotToModel(&snapshot))
	}

	return out, nil
}

// Mutation returns generated.MutationResolver implementation.
func (r *Resolver) Mutation() generated.MutationResolver { return &mutationResolver{r} }

// Query returns generated.QueryResolver implementation.
func (r *Resolver) Query() generated.QueryResolver { return &queryResolver{r} }

type mutationResolver struct{ *Resolver }
type queryResolver struct{ *Resolver }
