FROM node:22-alpine

# Enable Corepack for Yarn support
RUN corepack enable

WORKDIR /app

# Copy package files
COPY ./yarn.lock .
COPY ./package.json .
COPY ./.yarnrc.yml .
COPY ./.yarn ./.yarn

# Install dependencies
RUN yarn install --immutable

# Copy application code
COPY . .

EXPOSE 5173

CMD ["yarn", "dev", "--host"]
