import { Budget } from '../models/budget'

export const FakeBudget: Budget = {
	id: 1,
	userId: '12ads2',
	date: new Date(Date.now()),
	monthlyIncome: 4000,
	monthlyExpenses: 2500,
	categories: [
		{
			id: 1,
			name: 'Rent',
			userId: '12ads2',
			budgetId: 1,
			curentSpend: 1000,
			amount: 1000,
			expenses: [
				{
					id: 6,
					name: 'rent',
					amount: 120,
					date: new Date(Date.now()),
					categoryId: 1,
					userId: '12ads2',
				},
			],
		},
		{
			id: 2,
			name: 'Food',
			userId: '12ads2',
			budgetId: 1,
			curentSpend: 250,
			amount: 500,
			expenses: [
				{
					id: 4,
					name: 'kroger',
					amount: 120,
					date: new Date(Date.now()),
					categoryId: 2,
					userId: '12ads2',
				},
				{
					id: 5,
					name: 'costco',
					amount: 130,
					date: new Date(Date.now()),
					categoryId: 2,
					userId: '12ads2',
				},
			],
		},
		{
			id: 3,
			name: 'Insurance',
			userId: '12ads2',
			budgetId: 1,
			curentSpend: 100,
			amount: 130,
			expenses: [
				{
					id: 3,
					name: 'insurance',
					amount: 100,
					date: new Date(Date.now()),
					categoryId: 3,
					userId: '12ads2',
				},
			],
		},
		{
			id: 4,
			name: 'Utilities',
			userId: '12ads2',
			budgetId: 1,
			curentSpend: 300,
			amount: 350,
			expenses: [
				{
					id: 1,
					name: 'gas',
					amount: 120,
					date: new Date(Date.now()),
					categoryId: 4,
					userId: '12ads2',
				},
				{
					id: 2,
					name: 'electric',
					amount: 180,
					date: new Date(Date.now()),
					categoryId: 4,
					userId: '12ads2',
				},
			],
		},
	],
	incomes: [
		{
			id: 1,
			userId: '12ads2',
			name: 'work',
			date: new Date(Date.now()),
			amount: 3000,
			budgetId: 1,
		},
		{
			id: 2,
			userId: '12ads2',
			name: 'side hustle',
			date: new Date(Date.now()),
			amount: 1000,
			budgetId: 1,
		},
	],
}
