version: "2"
linters:
  enable:
    - errorlint
    - gocritic
  settings:
    errorlint:
      errorf: true
      asserts: true
      comparison: true
    gocritic:
      enabled-tags:
        - diagnostic
        - style
        - performance
      disabled-checks:
        - hugeParam
        - rangeValCopy
        - exitAfterDefer
        - ifElseChain
        - paramTypeCombine
        - tooManyResultsChecker
    govet:
      enable:
        - shadow
  exclusions:
    generated: lax
    presets:
      - comments
      - common-false-positives
      - legacy
      - std-error-handling
    rules:
      - linters:
          - errcheck
        path: _test\.go
    paths:
      - internal/db/sqlc
      - graph/generated
      - graph/model
      - third_party$
      - builtin$
      - examples$
formatters:
  enable:
    - gofmt
  exclusions:
    generated: lax
    paths:
      - internal/db/sqlc
      - graph/generated
      - graph/model
      - third_party$
      - builtin$
      - examples$
