// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"bytes"
	"fmt"
	"io"
	"strconv"
)

type Asset struct {
	ID                 string    `json:"id"`
	UserID             string    `json:"userId"`
	Name               string    `json:"name"`
	AssetType          AssetType `json:"assetType"`
	CurrentValue       string    `json:"currentValue"`
	LastValueUpdatedAt string    `json:"lastValueUpdatedAt"`
	CreatedAt          string    `json:"createdAt"`
	UpdatedAt          string    `json:"updatedAt"`
}

type Budget struct {
	ID              string `json:"id"`
	UserID          string `json:"userId"`
	Date            string `json:"date"`
	MonthlyIncome   string `json:"monthlyIncome"`
	MonthlyExpenses string `json:"monthlyExpenses"`
	CreatedAt       string `json:"createdAt"`
	UpdatedAt       string `json:"updatedAt"`
}

type CreateAssetInput struct {
	UserID       string    `json:"userId"`
	Name         string    `json:"name"`
	AssetType    AssetType `json:"assetType"`
	CurrentValue string    `json:"currentValue"`
}

type CreateBudgetInput struct {
	UserID          string `json:"userId"`
	Date            string `json:"date"`
	MonthlyIncome   string `json:"monthlyIncome"`
	MonthlyExpenses string `json:"monthlyExpenses"`
}

type CreateExpenseCategoryInput struct {
	UserID       string `json:"userId"`
	BudgetID     string `json:"budgetId"`
	Name         string `json:"name"`
	Allocation   string `json:"allocation"`
	CurrentSpend string `json:"currentSpend"`
}

type CreateExpenseInput struct {
	UserID      string               `json:"userId"`
	BudgetID    string               `json:"budgetId"`
	Amount      string               `json:"amount"`
	Date        string               `json:"date"`
	Description string               `json:"description"`
	Splits      []*ExpenseSplitInput `json:"splits"`
}

type CreateIncomeInput struct {
	UserID               string           `json:"userId"`
	BudgetID             string           `json:"budgetId"`
	Name                 string           `json:"name"`
	Amount               string           `json:"amount"`
	Date                 string           `json:"date"`
	SourceType           IncomeSourceType `json:"sourceType"`
	SourceTemplateID     *string          `json:"sourceTemplateId,omitempty"`
	SourceOccurrenceDate *string          `json:"sourceOccurrenceDate,omitempty"`
	GenerationMonth      *string          `json:"generationMonth,omitempty"`
}

type CreateLiabilityInput struct {
	UserID             string        `json:"userId"`
	Name               string        `json:"name"`
	LiabilityType      LiabilityType `json:"liabilityType"`
	CurrentBalance     string        `json:"currentBalance"`
	InterestRate       string        `json:"interestRate"`
	MinimumPayment     string        `json:"minimumPayment"`
	TargetExtraPayment string        `json:"targetExtraPayment"`
	PayoffPriority     int           `json:"payoffPriority"`
}

type CreateNetWorthSnapshotInput struct {
	UserID           string `json:"userId"`
	SnapshotDate     string `json:"snapshotDate"`
	TotalAssets      string `json:"totalAssets"`
	TotalLiabilities string `json:"totalLiabilities"`
	NetWorth         string `json:"netWorth"`
}

type CreateRecurringIncomeInput struct {
	UserID             string             `json:"userId"`
	Name               string             `json:"name"`
	Amount             string             `json:"amount"`
	RecurrenceInterval RecurrenceInterval `json:"recurrenceInterval"`
	PaydayDayOfMonth   *int               `json:"paydayDayOfMonth,omitempty"`
	StartDate          string             `json:"startDate"`
	EndDate            *string            `json:"endDate,omitempty"`
}

type CreateTaxBracketInput struct {
	Year          int          `json:"year"`
	FilingStatus  FilingStatus `json:"filingStatus"`
	MinimumAmount string       `json:"minimumAmount"`
	MaximumAmount *string      `json:"maximumAmount,omitempty"`
	Rate          string       `json:"rate"`
}

type CreateUserInput struct {
	IdentityProviderID string         `json:"identityProviderId"`
	Email              string         `json:"email"`
	ReturnType         ReturnType     `json:"returnType"`
	SafeWithdrawalRate string         `json:"safeWithdrawalRate"`
	CurrencyType       string         `json:"currencyType"`
	InflationRate      string         `json:"inflationRate"`
	DeductionType      DeductionType  `json:"deductionType"`
	DeductionAmount    *string        `json:"deductionAmount,omitempty"`
	MaxTaxBracketID    *string        `json:"maxTaxBracketId,omitempty"`
	FilingStatus       FilingStatus   `json:"filingStatus"`
	PayoffStrategy     PayoffStrategy `json:"payoffStrategy"`
}

type Expense struct {
	ID          string          `json:"id"`
	UserID      string          `json:"userId"`
	BudgetID    string          `json:"budgetId"`
	Amount      string          `json:"amount"`
	Date        string          `json:"date"`
	Description string          `json:"description"`
	Splits      []*ExpenseSplit `json:"splits"`
	CreatedAt   string          `json:"createdAt"`
	UpdatedAt   string          `json:"updatedAt"`
}

type ExpenseCategory struct {
	ID           string `json:"id"`
	UserID       string `json:"userId"`
	BudgetID     string `json:"budgetId"`
	Name         string `json:"name"`
	Allocation   string `json:"allocation"`
	CurrentSpend string `json:"currentSpend"`
	CreatedAt    string `json:"createdAt"`
	UpdatedAt    string `json:"updatedAt"`
}

type ExpenseSplit struct {
	ID          string  `json:"id"`
	ExpenseID   string  `json:"expenseId"`
	CategoryID  string  `json:"categoryId"`
	Amount      string  `json:"amount"`
	Description *string `json:"description,omitempty"`
	CreatedAt   string  `json:"createdAt"`
	UpdatedAt   string  `json:"updatedAt"`
}

type ExpenseSplitInput struct {
	CategoryID  string  `json:"categoryId"`
	Amount      string  `json:"amount"`
	Description *string `json:"description,omitempty"`
}

type Health struct {
	Status    string `json:"status"`
	Timestamp string `json:"timestamp"`
}

type Income struct {
	ID                   string           `json:"id"`
	UserID               string           `json:"userId"`
	BudgetID             string           `json:"budgetId"`
	Name                 string           `json:"name"`
	Amount               string           `json:"amount"`
	Date                 string           `json:"date"`
	SourceType           IncomeSourceType `json:"sourceType"`
	SourceTemplateID     *string          `json:"sourceTemplateId,omitempty"`
	SourceOccurrenceDate *string          `json:"sourceOccurrenceDate,omitempty"`
	GenerationMonth      *string          `json:"generationMonth,omitempty"`
	CreatedAt            string           `json:"createdAt"`
	UpdatedAt            string           `json:"updatedAt"`
}

type Liability struct {
	ID                   string        `json:"id"`
	UserID               string        `json:"userId"`
	Name                 string        `json:"name"`
	LiabilityType        LiabilityType `json:"liabilityType"`
	CurrentBalance       string        `json:"currentBalance"`
	InterestRate         string        `json:"interestRate"`
	MinimumPayment       string        `json:"minimumPayment"`
	TargetExtraPayment   string        `json:"targetExtraPayment"`
	PayoffPriority       int           `json:"payoffPriority"`
	LastBalanceUpdatedAt string        `json:"lastBalanceUpdatedAt"`
	CreatedAt            string        `json:"createdAt"`
	UpdatedAt            string        `json:"updatedAt"`
}

type Mutation struct {
}

type NetWorthSnapshot struct {
	ID               string `json:"id"`
	UserID           string `json:"userId"`
	SnapshotDate     string `json:"snapshotDate"`
	TotalAssets      string `json:"totalAssets"`
	TotalLiabilities string `json:"totalLiabilities"`
	NetWorth         string `json:"netWorth"`
	CreatedAt        string `json:"createdAt"`
	UpdatedAt        string `json:"updatedAt"`
}

type Query struct {
}

type RecurringIncome struct {
	ID                 string             `json:"id"`
	UserID             string             `json:"userId"`
	Name               string             `json:"name"`
	Amount             string             `json:"amount"`
	RecurrenceInterval RecurrenceInterval `json:"recurrenceInterval"`
	PaydayDayOfMonth   *int               `json:"paydayDayOfMonth,omitempty"`
	StartDate          string             `json:"startDate"`
	EndDate            *string            `json:"endDate,omitempty"`
	CreatedAt          string             `json:"createdAt"`
	UpdatedAt          string             `json:"updatedAt"`
}

type TaxBracket struct {
	ID            string       `json:"id"`
	Year          int          `json:"year"`
	FilingStatus  FilingStatus `json:"filingStatus"`
	MinimumAmount string       `json:"minimumAmount"`
	MaximumAmount *string      `json:"maximumAmount,omitempty"`
	Rate          string       `json:"rate"`
	CreatedAt     string       `json:"createdAt"`
	UpdatedAt     string       `json:"updatedAt"`
}

type UpdateAssetInput struct {
	ID           string    `json:"id"`
	Name         string    `json:"name"`
	AssetType    AssetType `json:"assetType"`
	CurrentValue string    `json:"currentValue"`
}

type UpdateBudgetInput struct {
	ID              string `json:"id"`
	MonthlyIncome   string `json:"monthlyIncome"`
	MonthlyExpenses string `json:"monthlyExpenses"`
}

type UpdateExpenseCategoryInput struct {
	ID           string `json:"id"`
	Name         string `json:"name"`
	Allocation   string `json:"allocation"`
	CurrentSpend string `json:"currentSpend"`
}

type UpdateExpenseInput struct {
	ID          string               `json:"id"`
	Amount      string               `json:"amount"`
	Date        string               `json:"date"`
	Description string               `json:"description"`
	Splits      []*ExpenseSplitInput `json:"splits"`
}

type UpdateIncomeInput struct {
	ID                   string           `json:"id"`
	Name                 string           `json:"name"`
	Amount               string           `json:"amount"`
	Date                 string           `json:"date"`
	SourceType           IncomeSourceType `json:"sourceType"`
	SourceTemplateID     *string          `json:"sourceTemplateId,omitempty"`
	SourceOccurrenceDate *string          `json:"sourceOccurrenceDate,omitempty"`
	GenerationMonth      *string          `json:"generationMonth,omitempty"`
}

type UpdateLiabilityInput struct {
	ID                 string        `json:"id"`
	Name               string        `json:"name"`
	LiabilityType      LiabilityType `json:"liabilityType"`
	CurrentBalance     string        `json:"currentBalance"`
	InterestRate       string        `json:"interestRate"`
	MinimumPayment     string        `json:"minimumPayment"`
	TargetExtraPayment string        `json:"targetExtraPayment"`
	PayoffPriority     int           `json:"payoffPriority"`
}

type UpdateNetWorthSnapshotInput struct {
	ID               string  `json:"id"`
	TotalAssets      *string `json:"totalAssets,omitempty"`
	TotalLiabilities *string `json:"totalLiabilities,omitempty"`
	NetWorth         *string `json:"netWorth,omitempty"`
}

type UpdateRecurringIncomeInput struct {
	ID                 string             `json:"id"`
	Name               string             `json:"name"`
	Amount             string             `json:"amount"`
	RecurrenceInterval RecurrenceInterval `json:"recurrenceInterval"`
	PaydayDayOfMonth   *int               `json:"paydayDayOfMonth,omitempty"`
	StartDate          string             `json:"startDate"`
	EndDate            *string            `json:"endDate,omitempty"`
}

type UpdateTaxBracketInput struct {
	ID            string       `json:"id"`
	Year          int          `json:"year"`
	FilingStatus  FilingStatus `json:"filingStatus"`
	MinimumAmount string       `json:"minimumAmount"`
	MaximumAmount *string      `json:"maximumAmount,omitempty"`
	Rate          string       `json:"rate"`
}

type UpdateUserInput struct {
	ID                 string         `json:"id"`
	IdentityProviderID string         `json:"identityProviderId"`
	Email              string         `json:"email"`
	ReturnType         ReturnType     `json:"returnType"`
	SafeWithdrawalRate string         `json:"safeWithdrawalRate"`
	CurrencyType       string         `json:"currencyType"`
	InflationRate      string         `json:"inflationRate"`
	DeductionType      DeductionType  `json:"deductionType"`
	DeductionAmount    *string        `json:"deductionAmount,omitempty"`
	MaxTaxBracketID    *string        `json:"maxTaxBracketId,omitempty"`
	FilingStatus       FilingStatus   `json:"filingStatus"`
	PayoffStrategy     PayoffStrategy `json:"payoffStrategy"`
}

type User struct {
	ID                 string         `json:"id"`
	IdentityProviderID string         `json:"identityProviderId"`
	Email              string         `json:"email"`
	ReturnType         ReturnType     `json:"returnType"`
	SafeWithdrawalRate string         `json:"safeWithdrawalRate"`
	CurrencyType       string         `json:"currencyType"`
	InflationRate      string         `json:"inflationRate"`
	DeductionType      DeductionType  `json:"deductionType"`
	DeductionAmount    *string        `json:"deductionAmount,omitempty"`
	MaxTaxBracketID    *string        `json:"maxTaxBracketId,omitempty"`
	FilingStatus       FilingStatus   `json:"filingStatus"`
	PayoffStrategy     PayoffStrategy `json:"payoffStrategy"`
	CreatedAt          string         `json:"createdAt"`
	UpdatedAt          string         `json:"updatedAt"`
}

type AssetType string

const (
	AssetTypeCash       AssetType = "CASH"
	AssetTypeInvestment AssetType = "INVESTMENT"
	AssetTypeRetirement AssetType = "RETIREMENT"
	AssetTypeRealEstate AssetType = "REAL_ESTATE"
	AssetTypeVehicle    AssetType = "VEHICLE"
	AssetTypeOther      AssetType = "OTHER"
)

var AllAssetType = []AssetType{
	AssetTypeCash,
	AssetTypeInvestment,
	AssetTypeRetirement,
	AssetTypeRealEstate,
	AssetTypeVehicle,
	AssetTypeOther,
}

func (e AssetType) IsValid() bool {
	switch e {
	case AssetTypeCash, AssetTypeInvestment, AssetTypeRetirement, AssetTypeRealEstate, AssetTypeVehicle, AssetTypeOther:
		return true
	}
	return false
}

func (e AssetType) String() string {
	return string(e)
}

func (e *AssetType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = AssetType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid AssetType", str)
	}
	return nil
}

func (e AssetType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *AssetType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e AssetType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type DeductionType string

const (
	DeductionTypeStandard DeductionType = "STANDARD"
	DeductionTypeItemized DeductionType = "ITEMIZED"
)

var AllDeductionType = []DeductionType{
	DeductionTypeStandard,
	DeductionTypeItemized,
}

func (e DeductionType) IsValid() bool {
	switch e {
	case DeductionTypeStandard, DeductionTypeItemized:
		return true
	}
	return false
}

func (e DeductionType) String() string {
	return string(e)
}

func (e *DeductionType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = DeductionType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid DeductionType", str)
	}
	return nil
}

func (e DeductionType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *DeductionType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e DeductionType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type FilingStatus string

const (
	FilingStatusSingle FilingStatus = "SINGLE"
	FilingStatusMfj    FilingStatus = "MFJ"
	FilingStatusMfs    FilingStatus = "MFS"
	FilingStatusHoh    FilingStatus = "HOH"
)

var AllFilingStatus = []FilingStatus{
	FilingStatusSingle,
	FilingStatusMfj,
	FilingStatusMfs,
	FilingStatusHoh,
}

func (e FilingStatus) IsValid() bool {
	switch e {
	case FilingStatusSingle, FilingStatusMfj, FilingStatusMfs, FilingStatusHoh:
		return true
	}
	return false
}

func (e FilingStatus) String() string {
	return string(e)
}

func (e *FilingStatus) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = FilingStatus(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid FilingStatus", str)
	}
	return nil
}

func (e FilingStatus) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *FilingStatus) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e FilingStatus) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type IncomeSourceType string

const (
	IncomeSourceTypeManual            IncomeSourceType = "MANUAL"
	IncomeSourceTypeRecurringTemplate IncomeSourceType = "RECURRING_TEMPLATE"
)

var AllIncomeSourceType = []IncomeSourceType{
	IncomeSourceTypeManual,
	IncomeSourceTypeRecurringTemplate,
}

func (e IncomeSourceType) IsValid() bool {
	switch e {
	case IncomeSourceTypeManual, IncomeSourceTypeRecurringTemplate:
		return true
	}
	return false
}

func (e IncomeSourceType) String() string {
	return string(e)
}

func (e *IncomeSourceType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = IncomeSourceType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid IncomeSourceType", str)
	}
	return nil
}

func (e IncomeSourceType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *IncomeSourceType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e IncomeSourceType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type LiabilityType string

const (
	LiabilityTypeMortgage     LiabilityType = "MORTGAGE"
	LiabilityTypeCreditCard   LiabilityType = "CREDIT_CARD"
	LiabilityTypeStudentLoan  LiabilityType = "STUDENT_LOAN"
	LiabilityTypeAutoLoan     LiabilityType = "AUTO_LOAN"
	LiabilityTypePersonalLoan LiabilityType = "PERSONAL_LOAN"
	LiabilityTypeOther        LiabilityType = "OTHER"
)

var AllLiabilityType = []LiabilityType{
	LiabilityTypeMortgage,
	LiabilityTypeCreditCard,
	LiabilityTypeStudentLoan,
	LiabilityTypeAutoLoan,
	LiabilityTypePersonalLoan,
	LiabilityTypeOther,
}

func (e LiabilityType) IsValid() bool {
	switch e {
	case LiabilityTypeMortgage, LiabilityTypeCreditCard, LiabilityTypeStudentLoan, LiabilityTypeAutoLoan, LiabilityTypePersonalLoan, LiabilityTypeOther:
		return true
	}
	return false
}

func (e LiabilityType) String() string {
	return string(e)
}

func (e *LiabilityType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = LiabilityType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid LiabilityType", str)
	}
	return nil
}

func (e LiabilityType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *LiabilityType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e LiabilityType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type PayoffStrategy string

const (
	PayoffStrategyAvalanche PayoffStrategy = "AVALANCHE"
	PayoffStrategySnowball  PayoffStrategy = "SNOWBALL"
)

var AllPayoffStrategy = []PayoffStrategy{
	PayoffStrategyAvalanche,
	PayoffStrategySnowball,
}

func (e PayoffStrategy) IsValid() bool {
	switch e {
	case PayoffStrategyAvalanche, PayoffStrategySnowball:
		return true
	}
	return false
}

func (e PayoffStrategy) String() string {
	return string(e)
}

func (e *PayoffStrategy) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = PayoffStrategy(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid PayoffStrategy", str)
	}
	return nil
}

func (e PayoffStrategy) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *PayoffStrategy) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e PayoffStrategy) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type RecurrenceInterval string

const (
	RecurrenceIntervalNone      RecurrenceInterval = "NONE"
	RecurrenceIntervalWeekly    RecurrenceInterval = "WEEKLY"
	RecurrenceIntervalBiweekly  RecurrenceInterval = "BIWEEKLY"
	RecurrenceIntervalMonthly   RecurrenceInterval = "MONTHLY"
	RecurrenceIntervalQuarterly RecurrenceInterval = "QUARTERLY"
	RecurrenceIntervalYearly    RecurrenceInterval = "YEARLY"
)

var AllRecurrenceInterval = []RecurrenceInterval{
	RecurrenceIntervalNone,
	RecurrenceIntervalWeekly,
	RecurrenceIntervalBiweekly,
	RecurrenceIntervalMonthly,
	RecurrenceIntervalQuarterly,
	RecurrenceIntervalYearly,
}

func (e RecurrenceInterval) IsValid() bool {
	switch e {
	case RecurrenceIntervalNone, RecurrenceIntervalWeekly, RecurrenceIntervalBiweekly, RecurrenceIntervalMonthly, RecurrenceIntervalQuarterly, RecurrenceIntervalYearly:
		return true
	}
	return false
}

func (e RecurrenceInterval) String() string {
	return string(e)
}

func (e *RecurrenceInterval) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = RecurrenceInterval(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid RecurrenceInterval", str)
	}
	return nil
}

func (e RecurrenceInterval) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *RecurrenceInterval) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e RecurrenceInterval) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}

type ReturnType string

const (
	ReturnTypeReal    ReturnType = "REAL"
	ReturnTypeNominal ReturnType = "NOMINAL"
)

var AllReturnType = []ReturnType{
	ReturnTypeReal,
	ReturnTypeNominal,
}

func (e ReturnType) IsValid() bool {
	switch e {
	case ReturnTypeReal, ReturnTypeNominal:
		return true
	}
	return false
}

func (e ReturnType) String() string {
	return string(e)
}

func (e *ReturnType) UnmarshalGQL(v any) error {
	str, ok := v.(string)
	if !ok {
		return fmt.Errorf("enums must be strings")
	}

	*e = ReturnType(str)
	if !e.IsValid() {
		return fmt.Errorf("%s is not a valid ReturnType", str)
	}
	return nil
}

func (e ReturnType) MarshalGQL(w io.Writer) {
	fmt.Fprint(w, strconv.Quote(e.String()))
}

func (e *ReturnType) UnmarshalJSON(b []byte) error {
	s, err := strconv.Unquote(string(b))
	if err != nil {
		return err
	}
	return e.UnmarshalGQL(s)
}

func (e ReturnType) MarshalJSON() ([]byte, error) {
	var buf bytes.Buffer
	e.MarshalGQL(&buf)
	return buf.Bytes(), nil
}
