import { Budget } from '../hooks/BudgetServices'

export const FakeBudget: Budget = {
	id: 1,
	userEmail: 'testUser@test.com',
	year: new Date(Date.now()).getFullYear(),
	month: new Date(Date.now()).getMonth(),
	monthlyIncome: 4000,
	monthlyExpenses: 1540,
	categories: [
		{
			id: 1,
			name: 'Rent',
			userEmail: 'testUser@test.com',
			budgetId: 1,
			currentSpend: 1000,
			allocation: 1000,
			expenses: [
				{
					id: 6,
					name: 'rent',
					amount: 120,
					year: new Date(Date.now()).getFullYear(),
					month: new Date(Date.now()).getMonth(),
					day: new Date(Date.now()).getDate(),
					categoryId: 1,
					userEmail: 'testUser@test.com',
				},
			],
		},
		{
			id: 2,
			name: 'Food',
			userEmail: 'testUser@test.com',
			budgetId: 1,
			currentSpend: 250,
			allocation: 500,
			expenses: [
				{
					id: 4,
					name: 'kroger',
					amount: 120,
					year: new Date(Date.now()).getFullYear(),
					month: new Date(Date.now()).getMonth(),
					day: new Date(Date.now()).getDate(),
					categoryId: 2,
					userEmail: 'testUser@test.com',
				},
				{
					id: 5,
					name: 'costco',
					amount: 130,
					year: new Date(Date.now()).getFullYear(),
					month: new Date(Date.now()).getMonth(),
					day: new Date(Date.now()).getDate(),
					categoryId: 2,
					userEmail: 'testUser@test.com',
				},
			],
		},
		{
			id: 3,
			name: 'Insurance',
			userEmail: 'testUser@test.com',
			budgetId: 1,
			currentSpend: 100,
			allocation: 130,
			expenses: [
				{
					id: 3,
					name: 'insurance',
					amount: 100,
					year: new Date(Date.now()).getFullYear(),
					month: new Date(Date.now()).getMonth(),
					day: new Date(Date.now()).getDate(),
					categoryId: 3,
					userEmail: 'testUser@test.com',
				},
			],
		},
		{
			id: 4,
			name: 'Utilities',
			userEmail: 'testUser@test.com',
			budgetId: 1,
			currentSpend: 300,
			allocation: 350,
			expenses: [
				{
					id: 1,
					name: 'gas',
					amount: 120,
					year: new Date(Date.now()).getFullYear(),
					month: new Date(Date.now()).getMonth(),
					day: new Date(Date.now()).getDate(),
					categoryId: 4,
					userEmail: 'testUser@test.com',
				},
				{
					id: 2,
					name: 'electric',
					amount: 180,
					year: new Date(Date.now()).getFullYear(),
					month: new Date(Date.now()).getMonth(),
					day: new Date(Date.now()).getDate(),
					categoryId: 4,
					userEmail: 'testUser@test.com',
				},
			],
		},
	],
	incomes: [
		{
			id: 1,
			userEmail: 'testUser@test.com',
			name: 'work',
			year: new Date(Date.now()).getFullYear(),
			month: new Date(Date.now()).getMonth(),
			day: new Date(Date.now()).getDate(),
			amount: 3000,
			budgetId: 1,
		},
		{
			id: 2,
			userEmail: 'testUser@test.com',
			name: 'side hustle',
			year: new Date(Date.now()).getFullYear(),
			month: new Date(Date.now()).getMonth(),
			day: new Date(Date.now()).getDate(),
			amount: 1000,
			budgetId: 1,
		},
	],
}
